### ISSUE TITLE
\ifshr@king for \ifshr@nking in multicol

### ISSUE THREAD

**Issue by polysyllabic** [latex3/latex2e#101]
In looking at the code for `\multi@column@out`, I notice that the value of `\ifshr@king` is saved and then restored, when I believe `\ifshr@nking` is intended. I have tried and failed to produce a MWE that shows this to have any real-world consequences, so I'm not sure if it's significant, but perhaps I'm just not triggering the right edge case.

**Comment by FrankMittelbach** [comment]
Clearly a typo on my part. But it is actually more or less dead code anyway which is why you haven't been able to make an MWE. After all the local change to `\ifshr@nking` happens inside the OR so the value is restored when the OR ends. Thus the only possible case that one can construct where its value matters is something like adding a full `multicols` environment inside, say, a heading definition.

At least that would be the only case that I can think of. But since that is technically possible (though more than unlikely) I will no drop the code but correct the typo. Thanks for pointing it out.

**Comment by FrankMittelbach** [comment]
... but in fact a fortunate typo. If corrected it will totally break the code because it is doing the \let inside a conditional branch. So to correct it properly it would need to get hidden so that the \ifshr@nking is not seen while that branch is bypassed at high speed. Thus, given that a full multicols inside a heading is a reather abscure use, I guess I just document this as a limitation.
