### ISSUE TITLE
\MakeUppercase and friends leak

### ISSUE THREAD

**Issue by schlcht** [latex3/latex2e#1021]
## Brief outline of the bug

`\MakeUppercase` and friends no longer typeset their argument in a group. Anything that is inside the argument will thus leak out. This hasn't been the case before (the change must have happened sometime between TL 2021 and 2022).

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\begin{document}
\MakeLowercase{\itshape Hello} World
\end{document}
```

With TL 2021, "World" is in upright shape, while in TL 2022 (and '23), it's in italics.

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/10997393/test.log)

**Comment by eg9** [comment]
I'm not sure that this was ever supported; in other words, the grouping effect was just due to the implementation and not described in any manual.

Besides, I don't think that formatting instruction should be inside `\MakeLowercase`: you want to italicize something _after_ having converted it to lowercase. But, anyway, the current behavior is what I'd expect to begin with.
