### ISSUE TITLE
MakeUppercase fails with "latin letter j with caron" under pdflatex

### ISSUE THREAD

**Issue by gmilde** [latex3/latex2e#1033]
## Brief outline of the bug
Upcasing the letter [j with caron](https://en.wikipedia.org/wiki/J%CC%8C) (U+01F0) leads to
`LaTeX Error: Unicode character ̌ (U+030C) not set up for use with LaTeX.`
and there is no caron on the captital J.
This is a regression from the TL21 behaviour, where there is no error and a caron is placed
on the upcased letter.

This seems related to "ǰ" not having a pre-composed capital variant.
It is similar to the behaviour for some Greek letters with diacritics, that also do not have a capital pre-composed variant (cf. issue #987; however, in contrast to the affected Greek letters, the capital J with caron seems to have a use case).

## Minimal example showing the bug

```latex
\RequirePackage{latexbug} 
\documentclass[a4paper]{article}
\usepackage[T1]{fontenc}
\begin{document}
ǰ → \MakeUppercase{ǰ}
\end{document}
```
## Log file (required) and possibly PDF file  
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) (preloaded format=pdflatex 2023.4.3)  5 APR 2023 02:16
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**case-changing-diacritics.tex
(./case-changing-diacritics.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-03-30>
(/usr/local/texlive/2023/texmf-dist/tex/latex/latexbug/latexbug.sty
Package: latexbug 2022/06/14 v1.0n Bug-classification
)
(/usr/local/texlive/2023/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(/usr/local/texlive/2023/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2022/07/02 v1.4n Standard LaTeX file (size option)
)
\c@part=\count185
\c@section=\count186
\c@subsection=\count187
\c@subsubsection=\count188
\c@paragraph=\count189
\c@subparagraph=\count190
\c@figure=\count191
\c@table=\count192
\abovecaptionskip=\skip48
\belowcaptionskip=\skip49
\bibindent=\dimen140
)
(/usr/local/texlive/2023/texmf-dist/tex/latex/base/fontenc.sty
Package: fontenc 2021/04/29 v2.0v Standard LaTeX package
)
(/usr/local/texlive/2023/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def
File: l3backend-pdftex.def 2023-03-30 L3 backend support: PDF output (pdfTeX)
\l__color_backend_stack_int=\count193
\l__pdf_internal_box=\box51
)
(./case-changing-diacritics.aux)
\openout1 = `case-changing-diacritics.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.

! LaTeX Error: Unicode character ̌ (U+030C)
               not set up for use with LaTeX.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.5 ǰ → \MakeUppercase{ǰ}
                             
? 
[1

{/usr/local/texlive/2023/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
(./case-changing-diacritics.aux) ) 
Here is how much of TeX's memory you used:
 1987 strings out of 477901
 44212 string characters out of 5836985
 1849666 words of memory out of 5000000
 22276 multiletter control sequences out of 15000+600000
 513385 words of font info for 34 fonts, out of 8000000 for 9000
 59 hyphenation exceptions out of 8191
 34i,5n,44p,190b,1309s stack positions out of 10000i,1000n,20000p,200000b,200000s
 </home/milde/.texlive2020/texmf-var/fonts/pk
/ljfour/jknappen/ec/tcrm1000.600pk> </home/milde/.texlive2020/texmf-var/fonts/p
k/ljfour/jknappen/ec/ecrm1000.600pk>
Output written on case-changing-diacritics.pdf (1 page, 2485 bytes).
PDF statistics:
 21 PDF objects out of 1000 (max. 8388607)
 12 compressed objects within 1 object stream
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)

**Comment by josephwright** [comment]
A bit of background (for the record). The older approach both to case changing and more generally to handling UTF-8 chars in pdfTeX was that something like `ǰ` would first be converted to `\u{j}`, then case changing would only apply to the `j`  (here, it would actually be`\j` due to the dot, but that's not generally relevant). The new approach preserves `ǰ` as-is, then looks for the Unicode mapping, which here is to two codepoints, which unfortunately only works in Unicode engines really.

There are a number of codepoints which don't have pre-composed case mappings, and I suppose one could argue that all of them should be special-cased to avoid this issue. It's then a question of how to set that up, which links to the broader topic of providing overrides. I've suggested an interface in the past but that wouldn't have covered this use case as the 'target' is not simple codepoints but rather arbitrary tokens. There's also the slight wrinkle that it's only needed for 8-bit engines, but I think that could be covered. Feels something like
```latex
\DeclareCaseMapping{"01F0}{upper}{\u{J}}
```
would work. So the first question is does that look sensible, and if so what happens about locale-specific mappings (i.e. do they need an interface at all or does one assume that start-of-locale would apply them - some thought would be needed to handle group levels with that.) (@jbezos any thoughts?)

If we can agree a general mechanism, then setting up specific codepoints is easy enough: will just be a question of whether these should be covered at the kernel/`expl3` level or left to users.

**Comment by FrankMittelbach** [comment]
Am 05.04.23 um 09:40 schrieb Joseph Wright:
> A bit of background (for the record). The older approach both to case 
> changing and more generally to handling UTF-8 chars in pdfTeX was that 
> something like |ǰ| would first be converted to |\u{j}|, then case 
> changing would only apply to the |j| (here, it would actually be|\j| due 
> to the dot, but that's not generally relevant). The new approach 
> preserves |ǰ| as-is, then looks for the Unicode mapping, which here is 
> to two codepoints, which unfortunately only works in Unicode engines really.

If I understand this correctly then the core issue is that Unicode 
doesn't contains a slot for LATIN CAPITAL J WITH CARON, correct?

One can argue, that the combination of U+004A U+030C should be the 
result of uppercasing, but equally I guess one can argue that it is 
undefined or maps to itself or ...
> 
> There are a number of codepoints which don't have pre-composed case 
> mappings, and I suppose one could argue that all of them should be 
> special-cased to avoid this issue. It's then a question of how to set 
> that up, which links to the broader topic of providing overrides. I've 
> suggested an interface in the past but that wouldn't have covered this 
> use case as the 'target' is not simple codepoints but rather arbitrary 
> tokens. 

> There's also the slight wrinkle that it's only needed for 8-bit 
> engines, but I think that could be covered. 

If it is meant to over a general overwrite mechanism, then it wouldn't 
necessarily be restricted to 8bit engines, wouldn't it?

> Feels something like
> 
> \DeclareCaseMapping{"01F0}{upper}{\u{J}}
> 
> would work. 

I think so, give or take the interface command name (and perhaps syntax)

Another issue is the reverse mapping.  What do you do if the starting 
point is not a single code point? I mean, what should happen if you 
start from U+004A U+030C  (or from \u{J} for that matter) and want to 
lower case?

probably not much you can do on the pdTeX side, but it feels a bit 
unbalanced if the interface is "one-to-many" but one can't specify 
many-to-one or even many-to-many

**Comment by josephwright** [comment]
> If I understand this correctly then the core issue is that Unicode doesn't contains a slot for LATIN CAPITAL J WITH CARON, correct? One can argue, that the combination of U+004A U+030C should be the result of uppercasing, but equally I guess one can argue that it is undefined or maps to itself or ...

Indeed. With a Unicode engine the U+004A U+030C outcome work (the placement is poor with Latin Modern, but that's also true of the input `\v{J}`, so it's a font issue not a macro one).


> If it is meant to over a general overwrite mechanism, then it wouldn't necessarily be restricted to 8bit engines, wouldn't it?

Indeed, a general mechanism should be exactly that. I meant that the specific situation of single codepoints which map to 'letter + combining char' probably only need to be addressed for 8-bit engines as there really is no gain for the Unicode ones.

> I think so, give or take the interface command name (and perhaps syntax)

Yes, that's why I've not added anything to date. For example, one might argue for `\Declare<type>caseMapping` to avoid the text argument, and there is the issue of whether there should be something locale-specific (and if so, handling the interaction with a locale-independent version). So perhaps

- `\DeclareUppercaseMapping`
- `\DeclareLowercaseMapping`
- `\DeclareTitlecaseMapping`

and

- `\DeclareLocaleUppercaseMapping`
- `\DeclareLocaleLowercaseMapping`
- `\DeclareLocaleTitlecaseMapping`

(We could perhaps hold off on the latter three and see if there is actually a use case.)

> Another issue is the reverse mapping. What do you do if the starting point is not a single code point? I mean, what should happen if you start from U+004A U+030C (or from \u{J} for that matter) and want to lower case? probably not much you can do on the pdTeX side, but it feels a bit unbalanced if the interface is "one-to-many" but one can't specify many-to-one or even many-to-many

Case changing isn't entirely reversible anyway, so to some extent there's not a lot you can do (_e.g._ `ß` -> `SS` when uppercasing at least with classical settings, but `SS` doesn't lowercase to `ß` so that is 'lost'). For U+004A U+030C -> U+006A U+030C -> U+01F0 (or similar) you are really looking at case changing followed by NFC. The latter is something that is handled by Unicode engines but would be pretty awkward to do in pdfTeX in general: there's a non-trivial amount of data needed plus time to check quite a number of Latin/Greek/Cyrillic codepoints (at least). I have got some limited NFC set up in the Greek uppercase code to handle the fact that you have to do NFD there as part of the accent-dropping, but that is a very limited subset of codepoints and is quite predictable.

More generally, doing multi-token replacement with the expandable approach is going to be relatively slow: you've got to check ahead for each token, and that first means ensuring it's not end-of-loop, a brace group or a space. So whilst it's doable I'd not be very keen. I think I'd want a very clear and important use case to offer this in general (as opposed to the focussed special-cases that are already implemented).

**Comment by gmilde** [comment]
> There are a number of codepoints which don't have pre-composed case
> mappings, and I suppose one could argue that all of them should be
> special-cased to avoid this issue. 

I'd argue for the lower claim that case-conversion with 8-bit LaTeX should work "out of the box" for all Unicode characters that are set up (basicly all characters that can be typeset with the selected font encoding(s)).

> If we can agree a general mechanism, then setting up specific code points
> is easy enough: will just be a question of whether these should be covered
> at the kernel/expl3 level or left to users.

This should not be left to users. It could be done, e.g. in the `<fontencoding>.dfu` files alongside the definition of the character.
This way it is automatically only read in when there is a possible use (8-bit TeX with potential use of this character).

> [...] The older approach both to case changing and more generally to handling
> UTF-8 chars in pdfTeX was that something like |ǰ| would first be converted
> to |\v{j}|, then case changing would only apply to the |j| ... 

Thank you for the background information. 
Mind, that the conversion to a LICR is required with 8-bit TeX anyway, the only difference is whether the conversion comes before or after the case change. Furthermore, the mechanism for up-casing LICRs is still required (and works as expected) with both, 8-bit TeX and Xe/LuaTeX, to allow for direct LICR input in the source or by packages.
→ For 8-bit TeX, it would suffice to have a list of characters that should first be convert to LICR and then up-cased.

> [...] one might argue for `\Declare<type>caseMapping` to avoid the text
> argument, and there is the issue of whether there should be something
> locale-specific (and if so, handling the interaction with a
> locale-independent version). 

I prefer `\DeclareUppercaseMapping` over `\DeclareCaseMapping{<key>}{upper}`.
For the default vs. locale, we I can imagine either an optional argument

    \DeclareUppercaseMapping{01F0}{\v J} 
    \DeclareUppercaseMapping{0386}[greek]{\textAlpha} % drop tonos
    
or a command pair similar to the NFSS TextCommands    

    \DeclareDefaultUppercaseMapping{01F0}{\v J} 
    \DeclareUppercaseMapping{0386}[greek]{\textAlpha} % drop tonos


> Another issue is the reverse mapping.

For most occurrences of "base char + combining char", it's relatively easy:
Under 8-bit TeX, combining chars don't work even without chase changing.
With Xe/LuaTeX it already works.

**Comment by jbezos** [comment]
Just to point out I agree with Günter’s comments, particularly “This should not be left to users.” WRT the names, `\DeclareUppercaseMapping` suggests me a general rule, like i → I, while `\DeclareLocaleUppercaseMapping` suggests me a localized rule, like i → İ. I think the syntax proposed by Günter makes more sense.

**Comment by jbezos** [comment]
@josephwright Both are fine for me.

**Comment by gmilde** [comment]
>>     I think the syntax proposed by Günter makes more sense.

> I'm happy to go with that if it's the consensus. Note that either the locale is
> an optional argument and one only needs \DeclareUppercaseMapping, or it's
> mandatory and one also needs \DeclareDefaultUppercaseMapping.

Both alternatives are fine with me -- whatever is easier/simpler to
implement or seems a better fit with the remainder of the interface.

Regarding the "locale" argument: according to my understanding of BCP47,
"el-x-iota" can be read as "try for a rule 'el-x-iota'" and if this does
not exist, try 'el'."

**Comment by josephwright** [comment]
I've now got the right setup in `expl3`: once that is out (later this week), I'll look to add an interface to LaTeX2e.

**Comment by gmilde** [comment]
Am 18.04.23 schrieb Joseph Wright:
> I've now got the right setup in expl3: once that is out (later this
> week), I'll look to add an interface to LaTeX2e.

It seems the interface is now out. 
The related issue [#1033] is marked as closed and
a test with a recent TeXLive update worked for `\MakeUppercase{ǰ}`.

However when trying to use the interface to fix uppercasing of Greek letters
as e.g.

    \DeclareUppercaseMapping{"0390}{\accdialytica{\textIota}}

with the same TeXLive installation, I get

This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) (preloaded format=pdflatex 2023.5.30)  30 MAY 2023 10:09
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**test-case-changing-minimal.tex
(./test-case-changing-minimal.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-05-22>
(/usr/local/texlive/2023/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
[...]
! Undefined control sequence.
l.19 \DeclareUppercaseMapping
                             {"0390}{\accdialytica{\textIota}}
[...]

**Comment by josephwright** [comment]
> > @josephwright  ^^^ it should be \IfNoValueTF in ltfinal
> 
> strange, why isn't there any test that would have caught that?

Tests are for the `expl3` implementation, not the 2e name ;)

**Comment by josephwright** [comment]
See 06733240f2a6eed725752345735501682bc4a6f0

**Comment by gmilde** [comment]
There is a documentation error in the last example of the usrguide:

    - \DeclareLowercaseMapping{xx}{"0049}{\i}
    + \DeclareLowercaseMapping[xx]{"0049}{\i}

Similar for the following lines.

Also, an example for `\CaseSwitch}` would help to find out how to use this
command and what it actually does.

**Comment by josephwright** [comment]
I've corrected the syntax for `\DeclareLowercaseMapping`
