### ISSUE TITLE
Unbalanced \if test in \texttt

### ISSUE THREAD

**Issue by Sophanatprime** [latex3/latex2e#1079]
## Brief outline of the bug

It seems text font commands can not take unbalanced `\if...` test as their argument.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\begin{document}

\texttt{\string\if}
% or
\texttt{\string\else}
% or
\texttt{\string\fi}

\end{document}
```

## Log file (required) and possibly PDF file  
[demo.log](https://github.com/latex3/latex2e/files/11621885/demo5.log)

**Comment by FrankMittelbach** [comment]
This is not a bug, but low-level TeX engine behavior and it is one of the reasons that things like primitive TeX conditionals are not part of the LaTeX document-level syntax. So in short it works as designed.

When you place `\string\if` into an argument of some command you aren't passing in a harmless string `\ i f` with all characters catcoded 12  you are passing in 2 tokens one of it being a low-level conditional. Now if this argument  is used  in the code in a conditional branch that is false, then TeX bypasses everything in this branch at high speed and does not evaluate tokens other than looking for `\if` (or similar conditionals), `\else` or `\fi` to figure out  when the branch ends. So it never sees the `\string` but it sees the `\if` from the argument and therefore believes a new conditional has started.   

There are possibilities to avoid it (by never using low-level conditionals where user input can appear in one of its branches), but this is used all over the place in 2e code which is why this is simply *not supported*.
