### ISSUE TITLE
rolling back from dev to 2023-06-01 errors

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#1089]
## Brief outline of the bug

when rolling back from dev to 2023-06-01 hooks containing hashes error with e.g.

~~~
! Illegal parameter number in definition of \__hook begindocument.
~~~

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\RequirePackage[2023-06-01]{latexrelease}
\documentclass{article}
\AddToHook{begindocument}[test]{\def\blub#1{}}
\begin{document}
abc
\end{document}

```

## Log file (required) and possibly PDF file  
[test-utf8.log](https://github.com/latex3/latex2e/files/11760975/test-utf8.log)

**Comment by muzimuzhi** [comment]
Seems it's because two implementations for `\hook_gput_code:nnn` used different `\IncludeInRelease` labels (the one for 2023/06/01 used `\hook_gput_code_with_args:nnn` while the one for 2020/10/01 used `\hook_gput_code:nnn`), so when rolling back to 2023-06-01, these two implementations are both applied and the latter wins.
https://github.com/latex3/latex2e/blob/aacf72dbfd63e1b147af6507651af6e850b61d2b/base/lthooks.dtx#L3537-L3544
https://github.com/latex3/latex2e/blob/aacf72dbfd63e1b147af6507651af6e850b61d2b/base/lthooks.dtx#L3712-L3715

Simply normalizing both to label `\hook_gput_code:nnn` passes `l3build check -q -c build -e pdftex`, but I didn't check if the two blocks of code are actually replaceable with each other.

**Comment by PhelypeOleinik** [comment]
> Seems it's because two implementations for `\hook_gput_code:nnn` used different `\IncludeInRelease` labels (the one for 2023/06/01 used `\hook_gput_code_with_args:nnn` while the one for 2020/10/01 used `\hook_gput_code:nnn`)

Correct.  And I thought I checked rollback labels before committing...

> Simply normalizing both to label `\hook_gput_code:nnn` passes `l3build check -q -c build -e pdftex` and the example provided in this issue, but I didn't check if the two blocks of code are actually replaceable with each other.

They are.  The 2023/06/01 new versions add `\@@_replacing_args_true/false:` so that the code knows it's supposed to treat `#1` as “parameter `#1`” or as “parameter token `#` + the character `1`”.

Thanks for the debugging!
