### ISSUE TITLE
Wrong number with \text and \int_gincr:N

### ISSUE THREAD

**Issue by F-Matthias** [latex3/latex2e#1107]
## Brief outline of the bug

Using \int_gincr:N results in an incorrect number when used in \text.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{amstext}
\begin{document}
\newcounter{mycounter}
\ExplSyntaxOn
\cs_new:Npn \mymacro #1
  {
    #1
    \addtocounter{mycounter}{1}
    \int_gincr:N \l_tmpa_int
  }
\ExplSyntaxOff
$\text{\mymacro{my text}}$

the counter is \themycounter

this should also be 1 but gives
\ExplSyntaxOn
\int_use:N \l_tmpa_int
\ExplSyntaxOff

The reason why the counter gives 1 is because \verb|\text| uses \verb|\text@|, which sets \verb|\firstchoice@false| and \verb|\stepcounter| uses \verb|\iffirstchoice@|.
\end{document}
```

## Log file (required) and possibly PDF file  

[bug.log](https://github.com/latex3/latex2e/files/12070164/bug.log)
[bug.pdf](https://github.com/latex3/latex2e/files/12070168/bug.pdf)

**Comment by muzimuzhi** [comment]
It's `amstext` that redefines `\stepcounter` and other counter commands to take `\iffirstchoice@` into consideration. But I think it's also not a problem for l3kernel int functions to not take that conditional into consideration.  LaTeX counters are different from both TeX counters and LaTeX3 integers. You get same wrong result (4, instead of 1) using TeX primitives to manipulate counters.

Hence my suggestion is to manually handle `\iffirstchoice@`:
```tex
\cs_new:Npn \mymacro #1
  {
    #1
    \addtocounter{mycounter}{1}
    \legacy_if:nT {firstchoice@}
      { \int_gincr:N \l_tmpa_int }
  }
```

<details><summary>Full example</summary>
<p>

```tex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{amstext}

\newcounter{mycounter}
\ExplSyntaxOn
\cs_new:Npn \mymacro #1
  {
    #1
    \addtocounter{mycounter}{1}
    \legacy_if:nT {firstchoice@}
      { \int_gincr:N \l_tmpa_int }
  }
\ExplSyntaxOff

\begin{document}

$\text{\mymacro{my text}}$

the counter is \themycounter

this should also be 1 but gives
\ExplSyntaxOn
\int_use:N \l_tmpa_int
\ExplSyntaxOff
\end{document}
```

In PDF
```
my text
the counter is 1
this should also be 1 but gives 1
```
</p>
</details>

In another way, with expl3/LaTeX3 being used more and more widely, the need for LaTeX3 interfaces to LaTeX2e user/author command arises.
