### ISSUE TITLE
Error when using forloop and babel spanish option

### ISSUE THREAD

**Issue by jorgepz** [latex3/latex2e#1113]
## Brief outline of the bug
There is an error (`Missing = inserted for \ifnum`) when using the babel spanish option with a forloop in the same document

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}    % <- first line
\documentclass{article}
\usepackage{forloop}
\usepackage[spanish]{babel}
\begin{document}
	Test \newcounter{x}
	\forloop{x}{1}{\value{x} < 10}{ % value of x is 1...9
		\arabic{x}                  % print x in arabic notation
	}
\end{document}
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/12209397/test.log)

**Comment by u-fischer** [comment]
As the log-file tells you you are using third party packages. So please report the error to their maintainer:

~~~~
! Package latexbug Error: Third-party file(s)
(latexbug)                
(latexbug)                This test file uses third-party file(s)
(latexbug)                
(latexbug)                ==============
(latexbug)                forloop.sty
(latexbug)                bblopts.cfg
(latexbug)                spanish.ldf  ->  Javier Bezos 
(latexbug)                    <http://www.texnia.com/contact.html> 
(latexbug)                ==============
(latexbug)                
(latexbug)                So you should contact the authors
(latexbug)                of these files, not the LaTeX Team!
(latexbug)                (Or remove the packages that load
(latexbug)                them, if they are not necessary to
(latexbug)                exhibit the problem).
(latexbug)                
(latexbug)                If you think the bug is in core LaTeX
(latexbug)                (as maintained by the LaTeX Team) but
(latexbug)                these files are needed to demonstrate
(latexbug)                the problem, please continue and mention
(latexbug)                this explicitly in your bug report
(latexbug)                (with an explanation why you think so).
~~~~

**Comment by hvoss49** [comment]
Use. `\shorthandoff{<}`  before the for loop. `<`  is an active character in spanish

**Comment by jorgepz** [comment]
Great! Thanks for the replies. `\shorthandoff{<}` solved this. I guess that this should be reported in the forloop repo and not in the babel one... As soon as I find the repo I will report it.
Thanks again! 👍🏼

**Comment by jbezos** [comment]
@jorgepz Don’t blame `forloop`. It’ a documented behavior of `spanish` for `babel' . See pages 12-13 (in Spanish) and 21 (in English) of its manual.

**Comment by josephwright** [comment]
@jbezos  Back with the old 'can we find a way to have a fixed set of actives' question!

**Comment by jbezos** [comment]
@josephwright Or even ‘can we find a way to have a single active (namely, `"`)’.
