### ISSUE TITLE
graphicx 

### ISSUE THREAD

**Issue by hvoss49** [latex3/latex2e#1178]
## Brief outline of the bug

I inserted by default a doubled `==` for the scaling and was wandering that I got an output with the correct image size but without  the image.  Up-to-date TL2023
With any other character, eg `=!`,  I get the correct warning, but not with `==`

## Minimal example showing the bug

```latex
\documentclass{article}
\usepackage{graphicx}
\begin{document}

\fbox{\includegraphics[scale==0.9]{example-image-a}}

\end{document}```


## Log file (required) and possibly PDF file  

The 2022 dir has the contents of 2023!


```
bash-3.2$ pdflatex grf_test.tex 
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./grf_test.tex
LaTeX2e <2023-11-01>
L3 programming layer <2023-11-01>
(/usr/local/texlive/2022/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(/usr/local/texlive/2022/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2022/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2022/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/local/texlive/2022/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/usr/local/texlive/2022/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
No file grf_test.aux.
(/usr/local/texlive/2022/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/local/texlive/2022/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
(/usr/local/texlive/2022/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
[1{/usr/local/texlive/2022/texmf-var/fonts/map/pdftex/updmap/pdftex.map} </usr/
local/texlive/2022/texmf-dist/tex/latex/mwe/example-image-a.pdf>]
(./grf_test.aux) )</usr/local/texlive/2022/texmf-dist/fonts/type1/public/amsfon
ts/cm/cmr10.pfb></usr/local/texlive/2022/texmf-dist/fonts/type1/public/lm/lmss1
7.pfb>
Output written on grf_test.pdf (1 page, 20805 bytes).
Transcript written on grf_test.log.

```


<img width="285" alt="Bildschirmfoto 2023-11-12 um 14 20 54" src="https://github.com/latex3/latex2e/assets/12891199/4bbedfe5-43a1-4e77-9e03-3f7e18b7f7cc">

**Comment by muzimuzhi** [comment]
It's caused by
- `keyval` packages silently treats `\setkeys{<fam>}{key==val}` the same as `\setkeys{<fam>}{key=}`, with no warning/error.
  With `\setkeys{<fam>}{key==val}`, [`\KV@split key==val==\relax`](https://github.com/latex3/latex2e/blob/6c93a1cd347310b444803dc24cdde458444ba4ce/required/graphics/keyval.dtx#L255-L272) is called, which makes the three argument of `\KV@split` holding "scale", "", and "val==", respectively. `\KV@split` then only checks if its `#3` is empty (on line 265) to determine if default code should be used (corresponding to usage `\setkeys{<fam>}{key}`.
  - The `expl3` key-value interface has such check (for misplaced equal sign), and `pgfkeys` doesn't.
- `graphicx` package acts the same for `scale=` and `scale=1`.
  When `\includegraphics` [doesn't have a second opt-arg](https://github.com/latex3/latex2e/blob/6c93a1cd347310b444803dc24cdde458444ba4ce/required/graphics/graphicx.dtx#L774-L787) (the old syntax in `graphics` package), the `scale` value (`<factor>`) is passed on in [`\Gscale@box{<factor>}[<factor>]{...}`](https://github.com/latex3/latex2e/blob/6c93a1cd347310b444803dc24cdde458444ba4ce/required/graphics/graphicx.dtx#L419-L429), then used as [factor of dimension assignments](https://github.com/latex3/latex2e/blob/6c93a1cd347310b444803dc24cdde458444ba4ce/required/graphics/graphics.dtx#L1983-L1999). Hence an empty `<factor>` acts like `1`.

**Comment by davidcarlisle** [comment]
There are one or two known edge cases in the `keyval` parser, but previously whenever I have tried to change anything. some package somewhere breaks.

I'll look but medium term I suspect we will want to switch the `graphicx`  keyval parsing to the l3keys based parser that's now in the format, that would be safer than changing `keyval.sty`  as it would just affect `\includegraphics` not any package using `keyval`.

We'll look, thanks for the report.



But

**Comment by josephwright** [comment]
@davidcarlisle  I have suggested moving `l3graphics` into `l3kernel`, then we can just use that ;)

**Comment by davidcarlisle** [comment]
I think there are no plans to change the keyval package parser at this time, too much existing code depends on its documented or undocumented features.
