### ISSUE TITLE
minor aesthetic problem: overline in fouriernc

### ISSUE THREAD

**Issue by ryofurue** [latex3/latex2e#121]
## Brief outline of the bug
The line `\overline` produces is a little bit too high with the `fouriernc` package. This is very minor of course and cannot be objectively called a bug.  I just hope that somebody agrees with my aesthetic.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\documentclass{article}
\usepackage{fouriernc}%<-- comment out to compare with default.
\begin{document}
$(\partial\overline{k u'v'}/\partial y)$
\end{document}
```

## Log file (required) and possibly PDF file  
[test.log](https://github.com/latex3/latex2e/files/2822272/test.log)
[test.pdf](https://github.com/latex3/latex2e/files/2822283/test.pdf)

**Comment by eg9** [comment]
This is a choice of whom built the fouriernc fonts.

**Comment by FrankMittelbach** [comment]
if you run your test file with the line
`
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
`
as requested you get:
```

./Ohne-Titel.tex:5: Package latexbug Error: Third-party file(s)
(latexbug)                
(latexbug)                This test file uses third-party file(s)
(latexbug)                
(latexbug)                ==============
(latexbug)                fouriernc.sty
(latexbug)                ==============
(latexbug)                
(latexbug)                So you should contact the authors
(latexbug)                of these files, not the LaTeX Team!
(latexbug)                (Or remove the packages that load
(latexbug)                them, if they are not necessary to
(latexbug)                exhibit the problem).
(latexbug)                

```

we can't fix problems with packages not maintain by us.

**Comment by ryofurue** [comment]
@FrankMittelbach  Thank you very much for pointing me to the correct direction. And sorry for my bogus report.  I guess that this is written in the bug-report guide, which I didn't read carefully.

**Comment by FrankMittelbach** [comment]
@josephwright  could you please update the faq entry about latexbug so that it explicitly states that the test file should contain `\RequirePackage{latexbug}` at the top, not just a reference to another page that says that? Might save everybody some unnecessary time in the future. Perhaps also downplay the GNATS db, since searching in that will get less and less useful (imo)

**Comment by ryofurue** [comment]
I was wondering if you might want to organize the FAQ entry explicitly in two parts.  Something like

**Contributed packages**
What is normally called "LaTeX" consists of the core system and contributed packages. Bugs and requests regarding a contributed package should be directly sent to its maintainer.  Most package maintainers are found at [CTAN](http://ctan.org).

**Core LaTeX system**
Blah blah Blah . . .

**Comment by FrankMittelbach** [comment]
@ryofurue perhaps, but the problem is that core and contributed is not absolutely the right division. Basically, what we accept (and can accept) are simply bug reports on packages we manage. There are certainly other packages that can be reasonably considered "core" but are outside of our control. 

This is why we ask that everybody producing a bug report adds `\RequirePackage{latexbug}` on top and runs the test file with that, because that will then analyse the test file and will tell you whether we can accept the bug (i.e. we manage the used packages) or whether it should be send to somebody else and in many cases (where we know) we try to say where to.
