### ISSUE TITLE
lthooks doc ActivateGenericHook

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex2e#1234]
## Brief outline of the bug

The documentation of `\ActivateGenericHook` says that "This command undoes the effect of `\DisableGenericHook`."
Next example shows that it is not correct. Can you confirm?

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always 
\documentclass{article}
\DisableGenericHook {HOOK}
\ActivateGenericHook {HOOK} % ⟵ WARNING
\AddToHook{HOOK}{}% ⟵ ERROR
\begin{document}
\end{document}
```

**Comment by FrankMittelbach** [comment]
I think that sentence is a leftover from the early days the generic hooks have been developed. The motivation for diabling a generic hooks is for the case that the generic hook simply doesn't work (due to the way the command has been defined). Thus, if that is known the package developer can disable it up front to avoid issues for the user later on. Therefore, I think the sentence just has to be dropped from the documentation and we forgot to do that. @PhelypeOleinik can you confirm?

**Comment by FrankMittelbach** [comment]
or perhaps it was meant to say tha it "does not undo ..."

**Comment by FrankMittelbach** [comment]
updated documentation to correctly reflect the intended behavior.
