### ISSUE TITLE
amsmath: \dddot and \ddddot have spacing issues

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#126]
## Brief outline of the bug

The two amsmath accents shift the base letter vertially (by taking the accent into account --- see placement of R). Also the dots are too far to the left.

Both issues are absent if accents or mathdots package is used.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\usepackage{amsmath} % without fix

\begin{document}
$ S\dot{S} \quad P\ddot{P} \quad Q\dddot{Q} \quad R\ddddot{R} $

$ S\hat{S} \quad P\hat{P} \quad Q\hat{Q} \quad R\hat{R} $
\end{document}
```

## Log file (required) and possibly PDF file  

<img width="453" alt="bildschirmfoto 2019-02-18 um 13 41 42" src="https://user-images.githubusercontent.com/1062981/52951801-08083a00-3383-11e9-9b75-d11205f72c97.png">

same document but with accents.sty loaded instead

<img width="454" alt="bildschirmfoto 2019-02-18 um 13 43 22" src="https://user-images.githubusercontent.com/1062981/52951875-40a81380-3383-11e9-83f2-4db40456daef.png">

or with amsmath,mathdots (which uses more separation between dots):

<img width="429" alt="bildschirmfoto 2019-02-18 um 13 46 12" src="https://user-images.githubusercontent.com/1062981/52952044-b2805d00-3383-11e9-9d03-e6b8dad810be.png">

**Comment by wspr** [comment]
This is an interesting one in unicode-math because it's really up to the font designer to make this work. Here's LM Math:

![image](https://user-images.githubusercontent.com/8169/53052774-871a8100-34ef-11e9-8018-d2096bc7370b.png)

And XITSMath-Regular:

![image](https://user-images.githubusercontent.com/8169/53052804-94d00680-34ef-11e9-9689-c6273af807f4.png)

And XITSMath-Bold: (ouch)

![image](https://user-images.githubusercontent.com/8169/53052840-aaddc700-34ef-11e9-8025-375967c919b9.png)

@khaledhosny may be interested in the above...

**Comment by FrankMittelbach** [comment]
@wspr you don't really say how your images got produced. As they don't show the bug (with the lowered "R" I presume that you haven't loaded `amsmath` have you?

**Comment by wspr** [comment]
@FrankMittelbach Indeed, that's partly the point — in unicode-math the dots are just accents applied like every other accent. (And you better hope the font designer remembered to include them...)

**Comment by FrankMittelbach** [comment]
@wspr does that mean you haven't loaded amsmath or that unicode-math overwrites the amsmath definitions for those accents?

**Comment by wspr** [comment]
@FrankMittelbach Either would yield the same results — unicode-math overwrites most of what amsmath (and family) do with fonts and symbols. The main exception I can think of off the top of my head is `\colon` as the amsmath definition is kind of more structural. (Still not sure if that's a good idea or not, but was too much of a change to overwrite it.)

**Comment by FrankMittelbach** [comment]
well, I doubt that this is true also if you load accents or mathdots or ... that looks like a kind of worms for unicode-math eventually ... but on the whole it doesn#t belong into this pr (other than by reference)

**Comment by wspr** [comment]
@FrankMittelbach Sure. Currently unicode-math does most of its setup `\AtBeginDocument` and this avoids some/most trouble (although is a bit annoying at times), and if it seems necessary I could also add code to disable/emulate legacy packages to avoid more conflicts. But we can pick this discussion up elsewhere if need be :)

**Comment by stone-zeng** [comment]
@wspr It seems that the above figures show a bug in XITS Math Bold. An accent glyph and an alphabet glyph (that can be composed with an accent) need a Top Accent Position value (`topAccentAttachment` in Microsoft's specification), but the `uni20DB`, `uni20DC` etc don't contain such information.

**Comment by khaledhosny** [comment]
XITS Math Bold is know to be incomplete, it was never supposed to be a fully functional math font since its uses are limited for the occasional all-bold math formula (e.g. inside some other bold text, which I’m told is a bad practice anyway).

**Comment by wspr** [comment]
@khaledhosny Okay, thanks for looking into it.

I probably agree there are limited uses for a bold maths font but in certain contexts I think it's good to have.

One area where I suspect they could be very useful is to obtain a bold version of a character that otherwise doesn't have a bold alternative. I know this isn't the Unicode way, but it's a common complaint that unicode-math doesn't have a "bold symbol" command.
