### ISSUE TITLE
Avoid option conflicts between classs and packages

### ISSUE THREAD

**Issue by lvjr** [latex3/latex2e#1279]
## Brief outline of the enhancement

From [https://github.com/latex3/fontspec/issues/501](https://github.com/latex3/fontspec/issues/501), I think it would be great if LaTeX could provide some interfaces to reduce option conflicts between classes and packages using `\DeclareKeys` command.

Sometimes a class defines some key and hopes it to be used only by itself. So I think some key property `.scope = local` would be very useful:

```latex
\DeclareKeys {
   key .scope = local,
   key .code = {foo},
 }
```

And it is also good to provide a public command `\RemoveKeyFromOptionsList`.

**Comment by josephwright** [comment]
We had a bit of discussion in this direction in the team: I can't fine the issue it was in! Your suggestion is an interesting take: lets see what the rest of the team think, @davidcarlisle, @car222222  and @FrankMittelbach  in particular.

**Comment by Skillmon** [comment]
This is roughly what `beamer` does (but overzealous by removing all key=value options from the global options list), which led to unexpected behaviour in the past. I'd say that a class shouldn't decide which options might be read by a package and which aren't. If a user then has an incompatibility because a class should get an option while a package shouldn't the user can still use `\PassOptionsToClass`.

**Comment by davidcarlisle** [comment]
@josephwright  I don't like the idea of automatically removing any option used with a value, I'm not sure that leads to a useful behaviour if `foo=true` gets removed but the otherwise equivalent option `foo` does not,  however I think it would be good if classes could flag that some options are not global, either with a command such as `\RemoveKeyFrom(Global?)OptionsList.` in their code or probably nicer, as suggested here,  a `.something` declaration within the key setup, as then this more easily applies to boolean and other options with no explicit code.

**Comment by car222222** [comment]
David's idea seems sensible.  (Not that I really know very much about global keys, etc.)
