### ISSUE TITLE
longtable: caption font depends on outer value

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#133]
## Brief outline of the bug

Font used in the caption command is not initialized, so picks up any outer state. This needs `\reset@font` in the caption definition (not needed in latex.ltx as done in float setup there)

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\usepackage{longtable}

\begin{document}

\begin{longtable}{c}
  \caption{foo}  \endhead
  X
\end{longtable}

\sffamily

\begin{longtable}{c}
  \caption{foo}  \endhead
  X
\end{longtable}

\end{document}
```

## Log file (required) and possibly PDF file  

[lt-issue.log](https://github.com/latex3/latex2e/files/2978018/lt-issue.log)
[lt-issue.pdf](https://github.com/latex3/latex2e/files/2978019/lt-issue.pdf)

**Comment by davidcarlisle** [comment]
yes I guess so, although with `table` + `tabular` + `\caption` the table and caption font automatically match as the `\reset@font`  applies to both, but if I just reset the font in LT@caption then they won't unless we add the `\reset@font`  to longtable, but that might be too big a change?

**Comment by FrankMittelbach** [comment]
you mean that if you change a font inside table it also affects the caption? I would consider that a bug too. In my opinion the caption should always start out from a defined point and not depend on outer settings.

**Comment by davidcarlisle** [comment]
No, I mean a case as in your test file.

If the current font is sans serif (or whatever) and you use

`\begin{table}\caption{xyz}\begin{tabular}{ccc}abc....\end{tabular}\end{table}`


then the abc will be in the roman as `table` resets the font to the document default, so the table and caption font match each other,

Conversely, if  the table gets long and you switch to longtable


`\begin{longtable}{ccc}\caption{xyz}\\ abc....\end{longtable}`

Then currently abc and xyz would pick up the current sans font. Your suggestion is that `\caption` should reset so that xyz uses the document default,  but my question was whether `longtable` should reset so that abc also uses the document default as in the `table` case.

**Comment by car222222** [comment]
“table” and “longtable” are somewhat different structures.  Therefore it is not necessarily the case that the “caption” substructures in the two should behave similarly in all ways.  I am not really too sure what kind of logical structure a caption of a longtable is.  The confusion is partly because there is no “lomgtabular” structure to sit inside a longtable.

But it seems sensible to me that in both cases, “caption” should inherit most settings from the outer structure.  But with a hook like \captionsetup to override this default.  

It is not at all clear to me whether “lomgtable” should have a default of inheriting settings such as the font.  It is sufficiently different from “table” that it need not have the same behaviour.

**Comment by car222222** [comment]
“ I would consider that a bug too. In my opinion the caption should always start out from a defined point and not depend on outer settings. “

But the setting for the table environment is not an “outer setting”.  The caption in a table is a substructure of the table so it most naturally inherits settings from the table structure, but not from further out.

But it is sensible to provide a hook for local caption settings relative to the those table settings.

**Comment by car222222** [comment]
“but my question was whether longtable should reset so that abc also uses the document default as in the table case.”

Not so clear whether longtable should reset to some “document defaults”.  As implemented it is simply the next thing in the document so there is no compelling reason to reset.  

To help decide, Need some reasonable and structured use-cases in which the settings would be changed from the the dicument defaults.  This seems to me to imply that the longtable us embeded into some other document structure where the font or whatever is changed, a priori this seems unlikely to me.

**Comment by davidcarlisle** [comment]
On Sat, 23 Mar 2019 at 14:29, Chris Rowley <notifications@github.com> wrote:

> “but my question was whether longtable should reset so that abc also uses
> the document default as in the table case.”
>
> Not so clear whether longtable should reset to some “document defaults”.
>


> As implemented it is simply the next thing in the document so there is no
> compelling reason to reset.
>

That is of course a very reasonable viewpoint (as it was the view I took
when implementing it:-)

To help decide, Need some reasonable and structured use-cases in which the
> settings would be changed from the the dicument defaults. This seems to me
> to imply that the longtable us embeded into some other document structure
> where the font or whatever is changed, a priori this seems unlikely to me.
>
>
>
But..  the very common case is that a document starts out using
`\begin{table}\begin{tabular}`   so, being a float, the tabular uses the
document default font not the current font, but then during editing the
table gets too big so the markup is changed to `\begin{longtable}`  at
which point the (unexpected?) result is that the font switches to the font
current at that point.

I can see arguments either way for which font longtable should use but I'm
less convinced by the premise in the original comment that \caption should
use the document default even if the table doesn't.

**Comment by u-fischer** [comment]
I'm rather certain that there are quite a number of documents around who do

~~~~
{
  some font changes for the table
 \begin{longtable}...\end{longtable} 
}
~~~~

In most cases the "font changes" affect only the size, but I have also seen changes to e.g. sans serif.

So I don't think it would be a good idea if longtable would suddenly undo such font changes, but I also think it would be rather useful if there were e.g. a \LTfont command that the user could define to set the fonts for all longtables in a document and so avoid the grouping above.

**Comment by FrankMittelbach** [comment]
But arguably if the font size is changed that is done for the table data not to get a smaller caption, so even if one argues that such thing should not happen because of backward compatibility decupling the data font from the caption font to not automatically get the caption font changed just because your data font changes is conceptually correct. But of course by the end of the day it is David's call.

**Comment by car222222** [comment]
>> result is that the font switches to the font current at that point.

Yes.  And i see that the (possible) change when adding “long” can be surprising.

As I said before (i think) longtabular would have been a less misleading name!

But I am still looking for a case where the table, or longtable, would naturally be within some other structure and hence a real use-case in which the font would be changed from the default in a srluctured way: of course anyone can make a font change just for fun!

**Comment by car222222** [comment]
“But arguably if the font size is changed that is done for the table data not to get a smaller caption, “

And arguably not, because the caption in a long table is not much like a caption in a float.  It seems to be more of a heading for the tabular structure, so it could well be wanted in the same size as the data.

So need an \LTCfont too!

**Comment by u-fischer** [comment]
@FrankMittelbach  yes, normally I would want the caption font and its size to be the same as in tables (and I normally use the caption package to configure this) and beside a \LTfont a \LTcaptionfont would be nice. 

But I'm not sure if it makes it for the users easier, if longtable starts to resets some font aspects and other not.

**Comment by FrankMittelbach** [comment]
the case I came across it was building a font display package that lists available slots in otf  and other fonts  and was a bit surprised to get

<img width="765" alt="Screenshot 2019-03-23 at 16 47 46" src="https://user-images.githubusercontent.com/1062981/54868342-cefd2400-4d8b-11e9-90bb-29b4a9914724.png">

Ok, so I added \normalfont into the caption but that means "Table 123:" is still in the outer font, so no good. But putting \normalfont before the \caption in the heading doesn't work either because then you gat the famous "Misplaced \noalign" error.

The caption package is actually a good example for how things should be (imo) as it decouples the fonts and sets up its own defaults (so just by loading it you get what I think should happen anyway). So for my purpose thats enough. Maybe anouther case for, historical omissions/mistakes need to be kept for backward compatibility and you need to load a package to make it right.
