### ISSUE TITLE
Multicol with Right-to-Left Languages Misaligned on Last Page

### ISSUE THREAD

**Issue by TimothyALee** [latex3/latex2e#1346]
## Brief outline of the bug

The margins of the final page of a long multi column text do not align correctly when using a right-to-left language such as Hebrew or Arabic. In this case page 4 has the same inner margin as page 3, when it should alternate like on previous pages. The code appears to assume page 4 is and even page like page 3.

## Minimal example showing the bug

\RequirePackage{multicol}

\documentclass[11pt]{book}
\usepackage[paperwidth=4in, paperheight=6in, top=0.7in, bottom=0.6in, inner=0.3in, outer=0.8in]{geometry}
\usepackage{lipsum}
\usepackage{polyglossia}
\setotherlanguages{hebrew}
\begin{document}

\RLE{\setmainlanguage{hebrew}
	\begin{multicols}{2}
		\lipsum[1-5]
	\end{multicols}
}
\end{document}

[multicol.pdf](https://github.com/latex3/latex2e/files/15265162/multicol.pdf)
[logfile.log](https://github.com/latex3/latex2e/files/15265157/logfile.log)

**Comment by FrankMittelbach** [comment]
The last page of your example is not an RL page, but a LR page. The nature of the page is determined at the end of the page not at its beginning and when the end of the page is reached `\RLE` is no longer active, because the `}` is closed before `\end{document}`.

In other words, comment out the `multicols` environment in the example  to get single columns you see the same behavior. This is not a core LaTeX issue, but a consequence of the definition of `\RLE` and that is a `polyglossia` question an outside of the scope of this issue tracker.

What you have to do is to ensure that the whole document is RL e.g., by include a `\newpage` just before the closing `}`if polyglossia doesn't offer something else (I'm not a polyglossia person so don't know). E.g.,
```
\RLE{ .... \newpage}
```

**Comment by TimothyALee** [comment]
Thank you!
