### ISSUE TITLE
Extra \endgroup in \AddToHook

### ISSUE THREAD

**Issue by ysalmon** [latex3/latex2e#1430]
## Brief outline of the bug
The command ``\AddToHook`` causes an error in special circumstances.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\ExplSyntaxOn
\NewDocumentCommand{\test}{m}{
    \group_begin:
    \cs_set_eq:cN { ~ } \space
    \group_end:
}

\AddToHook{cmd/test/before}{\relax}
\ExplSyntaxOff

\begin{document}
nothing
\end{document}
```
Note the error goes away if the ``{m}`` spec is replaced with ``{}``. Also note I have no idea about ``\cs_set_eq:cN { ~ } \space``, this is minimised from a function in a package I did not write (Piton, function ``\__piton_piton_standard``).

## Log file (required) and possibly PDF file  

[texstudio_VuFlvC.log](https://github.com/user-attachments/files/16549438/texstudio_VuFlvC.log)
No PDF file is produced.

**Comment by muzimuzhi** [comment]
Similar: #1099.

**Comment by u-fischer** [comment]
unrelated but you should not patch internal commands of other packages.

**Comment by FrankMittelbach** [comment]
I think this ends up being an unfortunate restriction. It is documented that it is not possible to use generic command hooks with every command. Normally the code that inserts the hook tries to identify  whether or not it is possible and provide the developer with a sensible error message, but in edge cases like this you can end up with a low-level error.

Trying to avoid this at the cost of making each and every patching noticeably slower is not really viable approach as it doesn't  change the situation (other than producing a better error message (it will still not be possible to patch in a generic hook into such commands).

So I think the only thing that **should** be done here is to strengthen the documentation and stating that in a few cases one might get low-level errors instead of a decent error message when using a generic hook is not possible.

**Comment by ysalmon** [comment]
I see this is tricky.

Is there a way to do the same thing as ``\cs_set_eq:cN { ~ } \space`` without using this syntax ?
My naïve idea would be ``\cs_set_eq:NN \  \space`` but I guess that would have been used if possible.

The definition is using the L3 catcode table, and assumes that the standard tex/L2 catcode table is in force when its execution starts.
