### ISSUE TITLE
Is it actually true that every command `\⟨name⟩` offers now two associated hooks to which code can be added using `\AddToHookWithArguments` and `\AddToHookNextWithArguments`?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#1501]
The `ltcmdhooks-doc` reads:

> This file implements generic hooks for (arbitrary) commands. In theory every command `\⟨name⟩` offers now two associated hooks to which code can be added using `\AddToHook`,¹ `\AddToHookNext`, `\AddToHookWithArguments`, and `\AddToHookNextWithArguments`.²

So I naïvely thought e.g. `\AddToHookWithArguments{cmd/⟨name⟩/before}{...}` might [apply to `⟨name⟩`=`section`](https://tex.stackexchange.com/q/729066/18401).

But, IIUC, not every command `\⟨name⟩` offers these two associated hooks to which code can be added using `\AddToHookWithArguments` and `\AddToHookNextWithArguments`: in particular, not all (or any of the?) commands documented in e.g. [_LaTeX2e: An unofficial reference manual_](https://latex2e.org/) are concerned and only the ones documented in `source2e.pdf` are. If so, it is worth IMO to add this precision in the documentation.

**Comment by muzimuzhi** [comment]
It's one of the limitations of command hooks, see `texdoc ltcmdhooks-doc`, sec. 2.2 "Commands that look ahead":

> Some commands are defined in different “steps” and they look ahead in the input stream
to find more arguments. If you try to add some code to the `cmd/⟨name⟩/after` hook of
such command, it will not work, and it is not possible to detect that programmatically,
so the user has to know (or find out) which commands can or cannot have hooks attached
to them.
> One good example is the `\section` command. You can add something to the
cmd/section/before hook, but if you try to add something to the `cmd/section/after`
hook, `\section` will no longer work. That happens because the `\section` macro takes
no argument, but instead calls a few internal LaTeX macros to look for the optional and
mandatory arguments. By adding code to the `cmd/section/after` hook, you get in the
way of that scanning.

**Comment by dbitouze** [comment]
> It's one of the limitations of command hooks, see `texdoc ltcmdhooks-doc`, sec. 2.2 "Commands that look ahead":

Okay but, in [my question on TeX.SE](https://tex.stackexchange.com/q/729066/18401), I added something only to the `cmd/section/before` hook.

**Comment by muzimuzhi** [comment]
As Ulrike Fischer [commented](https://tex.stackexchange.com/questions/729066/can-addtohookwitharguments-let-us-access-to-the-arguments-of-a-command-that-has#comment1815401_729066) in your TeX.SE question, that's because "\section has no arguments at all."

Looks like the words in sec. 2.2 "Commands that look ahead" can be refined.

**Comment by dbitouze** [comment]
> As Ulrike Fischer [commented](https://tex.stackexchange.com/questions/729066/can-addtohookwitharguments-let-us-access-to-the-arguments-of-a-command-that-has#comment1815401_729066) in your TeX.SE question, that's because "\section has no arguments at all."

Okay but, once again, [_LaTeX2e: An unofficial reference manual_](https://latex2e.org/) contains plenty of commands that, at a first glance, do have arguments (and `\section` is one of them). Hence how a user could proceed to know which of them do actually have arguments, if he wants to play with `\AddToHookWithArguments{cmd/⟨name⟩/before}{...}`?

**Comment by dbitouze** [comment]
@u-fischer In fact, my initial concern was with `biblatex`'s `\addbibresource`, not with `\section`: I gave an MCE with the latter in order to make my question less specific.

Anyway, the `ltcmdhooks-doc` deserves improvements IMO.
