### ISSUE TITLE
inclusion of graphics broken in lualatex in the develop branch

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#155]
## Brief outline of the bug

Inclusion of every graphic fails in the luatex engine when using a format build with the develop branch. The primitive `\saveimageresources` doesn't work with the additional quotes:

~~~~
! error:  (file "example-image".pdf) (pdf backend): cannot find image file '"example-image".pdf'
!  ==> Fatal error occurred, no output PDF file produced!
~~~~

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{graphicx}
\begin{document}
\includegraphics{example-image}
\end{document}
```

And example using only the primitives is

~~~~
\documentclass{article}
\begin{document}
\saveimageresource {"example-image".pdf} 
\end{document}
~~~~

## Log file (required) and possibly PDF file  

[test-utf8.log](https://github.com/latex3/latex2e/files/3389040/test-utf8.log)

(my fontloader is newer and I'm using a local ini for the format).

**Comment by davidcarlisle** [comment]
I'll check, this was working in some off-git initial tests, as for \special in dvi backends, the code needs to remove all double quotes from the filename and then quote the whole name as required (which is just a brace group here)

**Comment by davidcarlisle** [comment]
I put a start of a fix in a develop branch `luatex.def` 

https://github.com/latex3/graphics-def/commit/6530ef5fe2b12685d980464164d8e2ed2a078789

It works for me with this test case, but all the graphics-def files (and the rest of `luatex.def`) probably need a review,

**Comment by davidcarlisle** [comment]
In the above fix I have added  the format's new `\unquote@name` command to remove `"`  but this needs to be dome in several  places, and probably will need doing on some of the other back end files as well, as even specials that allow `"` quoting may require `"example-image.png"` not `"example-image".png`  It may be better to refactor the core graphics code so that filenames passed on to driver files  never have `"` than the driver files can quote with `"` or `{}` as required.

**Comment by u-fischer** [comment]
works okay in LaTeX2e <2019-10-01> pre-release-2.
