### ISSUE TITLE
EC fonts silently remap italic to slanted

### ISSUE THREAD

**Issue by hmenke** [latex3/latex2e#172]
## Brief outline of the bug

Typesetting the minial example below produces a missing font warning in the log as expected:
```
LaTeX Font Warning: Font shape `OT1/cmss/m/it' in size <10> not available
(Font)              Font shape `OT1/cmss/m/sl' tried instead on input line 4.
```
However commenting in the `\usepackage[T1]{fontenc}` line makes this warning disappear, even though the EC fonts do not provide an italic version of Computer Modern.  Instead, the italic alphabet is simply remapped to slanted:
https://github.com/latex3/latex2e/blob/06814a346ab13447ba52c5f51414e9705202b648/base/cmfonts.fdd#L494-L495
While this has no functional impact, I believe that this is “false advertising”.  Remapping to slanted should still take place but also a warning should be printed to emphasize that there is actually no italic variant of `cmss` in T1 encoding.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
%\usepackage[T1]{fontenc}
\begin{document}
\sffamily\textit{Hi!}
\end{document}
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/3537984/test.log)

**Comment by eg9** [comment]
I'm not sure this can be classified as a bug. In general, there is no italic shape for sans serif fonts, but slanted. In `t1cmss.fd` we find
```latex
\EC@family{T1}{cmss}{m}{sl}{ecsi}
\EC@family{T1}{cmss}{m}{it}{ecsi}
```
so both `it` and `sl` are mapped to the same font. In `ot1cmss.fd` a different choice was made, namely
```latex
\DeclareFontShape{OT1}{cmss}{m}{it}
      {<->sub*cmss/m/sl}{}
```
which I consider suboptimal.

The creators of European Modern decided for `ecsi` because they wanted to stick to four letters. It's just a question of naming.

**Comment by FrankMittelbach** [comment]
Not quite sure why you consider the `ot1css.fd` choice sub-optimal  @eg9,  it does correctly reflect the situation, does it not? Suboptimal because it produces warnings when you can't do anything about them?

Some warning about substitution can be helpful and  while it is true that sans fonts usually only offer an oblique shape this is not universally true, there are a few that have real italics.

However, if you consider that `\emph` always switches to italics making that change only means that you get more substitution warnings for cases you can't really change (which I think was the main reason for the EC decision (we didn't actually alter the EC support files when we integrated them in LaTeX).

Probably for the same reason most newer sans fonts (e.g., all that have been provided via autoinst) use `it -> sl` and not `sl -> it` for probably exactly the same reason even though technically speaking that is even "wronger" but at least it avoids the warning when you can't to anything about and only warns if you use `\slshape` which means you probably tried to use both sl and it.

So all in all I think a change would not really be helpful or perhaps if changed than following the approach that autoinst is using even if that is technically wrong.

**Comment by FrankMittelbach** [comment]
CMSS fonts in OT1 will now silently (log info only) substitute `it` shape to `sl`. But the log info will remain.

**Comment by hmenke** [comment]
There is zero advantage from just logging, because most editors parse the log file, so users will still be bothered by this warning.

**Comment by FrankMittelbach** [comment]
... and all fonts other than CMSS in T1 show the substituation in the log but not on the terminal usually. so that *is* the normal behavior T1cmss is the odd one here, but making that produce a warning after 20 years without isn't going to happen. Sorry, if this is not getting your approval, but we aren't going to fully drop the substitution info.

By the way, there is a difference: it doesn't say Warning it say Info if  it only goes in the log.

**Comment by hmenke** [comment]
Ah, I see.  If the level is Info, it won't be shown in the quick-fix log of most editors.
