### ISSUE TITLE
Legacy comment in ltxref.dtx seems wrong (possibly obsoleted at some point)

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#180]
Here we see a description of `\@currentlabel` definition.

https://github.com/latex3/latex2e/blob/a7963325cd2fabc0c88ee018450e839409b56881/base/ltxref.dtx#L101-L103

But what does `{CNT}` stand for? This could have been standing for `\the\value{c@countername}` but I don't feel like `\@currentlabel` is defined this way. My understanding is that it is only `{eval(\p@cnt\theCNT)}`.

**Comment by FrankMittelbach** [comment]
true, all the "oldcomments" date back to LaTeX 2.09 and are often not fully accurate any longer. But life is short, which is why we surrounded them with `\begin{oldcomments}` instead of always writing new documentation.

I have changed the formatting so that they now clearly show as "Historical 2.09 comments (not necessarily accurate any more)" which is not perfect, but the best I'm currently willing to do.
