### ISSUE TITLE
Underbrace is a bit discontinuous

### ISSUE THREAD

**Issue by wazdra** [latex3/latex2e#194]
## Brief outline of the bug
Small discontinuity on the edges of underbrace (at the junction between the edges and the flat line). Observed on different viewers

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

  % Any preamble code goes here
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amssymb}

\begin{document}

  % Demonstration of issue here
  \[f'= f\cup\underbrace{\{((\lambda,\beta),(\alpha\cdot\beta + \lambda)),\lambda\in\alpha\}}_{g}\]

\end{document}
```

## Log file (required) and possibly PDF file  
[bugunderbrace.log](https://github.com/latex3/latex2e/files/3706619/bugunderbrace.log)
[bugunderbrace.pdf](https://github.com/latex3/latex2e/files/3706621/bugunderbrace.pdf)

**Comment by davidcarlisle** [comment]
like all extensible characters in tex the large brace is made by typesetting multiple characters with the parts of the symbol. Exactly how well they merge together depends to an extent on your pdf viewer and zoom level.

If I run your test file I see the following, which looks Ok to me, although at some other zoom levels small discontinuities can be seen at the start of the curved sections.

![brace](https://user-images.githubusercontent.com/1268738/66478252-d9fe7400-ea91-11e9-96f2-cc33f1073c7c.png)

**Comment by stone-zeng** [comment]
If you are talking about something like

![image](https://user-images.githubusercontent.com/18233088/66476242-acccb880-eac7-11e9-9d78-2b32f37c477d.png)

then it's due to the rendering of your PDF reader, since the underbrace is combined with two "terminals" and an extensible middle part.

However, if you zoom in further enough, you will find something like

![image](https://user-images.githubusercontent.com/18233088/66476531-69267e80-eac8-11e9-9234-d204308db7a8.png)

I guess it's because of the design of Computer Modern font (here is `cmex10`).

To show that, first let's check the dvi file (use `latex` to compile then `dviasm` to read it). We can find:

```yaml
push:
  right: 2.222168pt
  fnt: cmex10 at 10pt
  set: '|'
  setrule: 1.199966pt 51.534531pt
  set: '{z'
  setrule: 1.199966pt 51.534515pt
  set: '}'
pop:
```

It means TeX selects glyphs `7C`, `7B`, `7A`, `7D` in font `cmex10` at 10pt, and inserts two rules with height=1.199966pt and width=51.534531pt between them.

We only consider glyph `7C` here (others are similar). The glyph is the following:

![image](https://user-images.githubusercontent.com/18233088/66477548-f7036900-eaca-11e9-926e-752781efedeb.png)

The height is 0.12 em and as the font size is 10pt currently, it should only gives an error at 1.2-1.199966=0.000034pt, which can be ignored.

But wait a minute here. Zoom in the glyph and we will notice that there is a tiny gap at the right boundary:

![image](https://user-images.githubusercontent.com/18233088/66477877-af311180-eacb-11e9-8ae1-44b9ca37fca8.png)

The rule will start at the left boundary (the vertical line in the above figure), so a tiny triangle will be left. Its height is 0.406977/1000*10pt=0.004070pt, and I think it is observable.

**Comment by FrankMittelbach** [comment]
Impressive analyis by @stone-zeng but unfortunately nothing the LaTeX Team can do about. We don't own the fonts, they are designed by Donald Knuth and  not likely to get changed, though one could try to raise a bug report with him (though I'm not sure these days how to do that electronically).

Since we can't change this, I'm closing the issue.

**Comment by stone-zeng** [comment]
Need to mention that in Latin Modern Math, the glyphs are redesigned so they can connect perfectly:

![image](https://user-images.githubusercontent.com/18233088/66480320-fe2d7580-ead0-11e9-88b5-979e7cf36cc0.png)

@FrankMittelbach Is it possible to add a negative kern between the left/right terminal and the rule?

**Comment by FrankMittelbach** [comment]
@stone-zeng one could experiment with that in the definition of \upbracefill I guess (though shouldn't that be a positive kern?) --- anyway, if you do that then the definition would be wrong with other fonts that work correctly (like Latin Modern as you say) and that may also end up showing other artifacts (like gaps) depending on how the viewers display things. So I don't really think it should be done on the macro level.
