### ISSUE TITLE
! Package inputenc Error: Invalid UTF-8 byte 191.

### ISSUE THREAD

**Issue by ZhaokunQiu** [latex3/latex2e#228]
## Brief outline of the bug
This is the first time I use LaTex, but when I try to run a template application, it gives the error as mentioned. Is there anyone could do me a favor ? THX !!!

## Log file (required) and possibly PDF file  
There is an empty log file.

**Comment by PhelypeOleinik** [comment]
Hello,

This issue tracker is for bugs in LaTeX, but your problem seems like some weird character or missing input encoding setting in your document, so it's an user error.

You are welcome to ask this at the [TeX--LaTeX Stackexchange](https://tex.stackexchange.com/questions/ask). Make sure to provide a minimal compilable example that demonstrates the issue. Thank you!

I will close this issue as user error.
