### ISSUE TITLE
Bug in the redefinition of \dotfill in doc.sty

### ISSUE THREAD

**Issue by FOCCOF** [latex3/latex2e#23]
## Brief outline of the bug

I found (after getting really irritated, to be honest) that
the package doc.sty redefines the \dotfill macro of the LaTeX2e kernel.

The definition of  doc.sty  leads to unwanted behaviour when \dotfill is
followed by \unskip  (and such an \unskip may be deeply hidden !).

    doc.sty definition:  \dotfill = \leaders ... \hfill
    latex.ltx definition: \dotfill = \leaders ...\hfill \kern \z@ => \kern\z@ protects against \unskip

I wonder why a LaTeX package redefines commands from the kernel. 

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\let\dotfillLaTeXORI =\dotfill     % < Save original LaTeX2e definition >

\documentclass [a4paper]{ltxdoc}% < ltxdoc loads doc.sty that redefines \dotfill >

\usepackage [T1]{fontenc}
\usepackage [utf8]{inputenc}
\usepackage {array}

\begin{document}

\begin{tabular}{ l  l  }% < tabular executes \unskip after the cell contents >
BAD               & GOOD                      \\
One\dotfill    & Two\dotfillLaTeXORI \\
Column One & Column Two              \\
\end{tabular}

 
\end{document}
```

## Log file (required) and possibly PDF file  

!! Use drag-and-drop !!

**Comment by FrankMittelbach** [comment]
> I wonder why a LaTeX package redefines commands from the kernel.

Interesting question. Quite often because it has to as the 2e kernel doesn't have the right hooks (eg the `array` package you use above does that even more often than `doc`). But anyway  in this case put it down to the `doc` code being written 30 years ago (at a time `\kern \z@` wasn't in side `\dotfill`. And back then token space was of real importance so it wouldn't do to add arbitrary new commands unnecessarily. 

Anyway, even though that has served for about three decades without anybody coming across that problem, I agree that it makes sense to fix it and as I'm currently anyway revising doc in other places I will make sure that the next release will have the correction.

**Comment by FOCCOF** [comment]
@FrankMittelbach   
Thank you for your reply.
I think the definition of LaTeX2e kernel is related to its proper definition of the tabular/array environments.
At the time of e-TeX, I think the \unskip put after the # in the template should be filtered, since \unskip here means "remove the last space " we should say nowadays with e-TeX :

\ifcase\gluestretchorder\lastskip
  \ifcase\glueshrinkorder\lastskip   \unskip \fi \fi

In order not to cancel a infinitely stretchable or shrinkable glue, what a <Space> never is.

Finally, to be clear, in my opinion the culprit is \@mkpream and not the \dotfill definition of doc.sty....

**Comment by davidcarlisle** [comment]
@FOCCOF  Hi, I hope this account github ping is still working, may we contact you re tabu?
You could mail me at d.p.carlisle [at] gmail.com

thanks,

David
