### ISSUE TITLE
Testing core third-party packages

### ISSUE THREAD

**Issue by josephwright** [latex3/latex2e#235]
[This is a meta/tracking issue: not the normal structure.]

To allow some opportunity to catch interactions between third-party packages and kernel changes, it would be useful to have a set of `contrib` tests, modelled on the LaTeX3 repo ones.

- [X] Add a stub `contrib` directory
- [ ] Set up one or more basic tests
- [ ] Check these have the right package support on the VM
- [ ] Run the `contrib` tests automatically rather than manually-only

**Comment by josephwright** [comment]
We still need some idea of which packages to include here!

**Comment by FrankMittelbach** [comment]
- babel + main languages
 - biblatex 
 - some expl3 based packages (acro ... ?)
 - tikz
 - fancyhdr
 - floats, caption
 - geometry
 - KOMA classes
 - memoir
 - mathtools
 - enumitem
 - titlesec
 - titletoc

just throwing out random ideas

**Comment by blefloch** [comment]
* cite, natbib, biblatex and other bibliography-related packages because they
may be relying on some details of the implemntation
* standalone, preview, and other packages that reorganize pages
* amscls, revtex, and other journal classes

**Comment by jcrippen** [comment]
Maybe reledmac / reledpar?

Hyperref and its friends?

**Comment by hmenke** [comment]
Regarding PGF/TikZ, at some (hopefully not too distant) point in the future I want to set up regression testing for PGF/TikZ.  I could just run these tests against `latex-dev` by default.

**Comment by FrankMittelbach** [comment]
> Regarding PGF/TikZ, at some (hopefully not too distant) point in the future I want to set up regression testing for PGF/TikZ. I could just run these tests against `latex-dev` by default.

that would certainly be helpful but you should make your setup configurable to be able to explicitly test against current not only future releases. 

Anyway, this issue here is for us finding possible issues even before we make a public dev release.

**Comment by josephwright** [comment]
I think experience with the L3 attempts at this suggests it's not likely to pick up breakage by us, rather changes in third party code we'll be forever tracking. As such, I don't think it's a good plan.

**Comment by blefloch** [comment]
I slightly disagree: our LaTeX3 experience applies to fast-moving packages such as `ctex`, but this issue here would be about packages that are much more stable and that we would ideally not needlessly break.  On the other hand, this may better live in a separate repository, with separate Travis runs, so as to not slow down our work.

**Comment by FrankMittelbach** [comment]
@blefloch an interesting idea. Maybe one step further would be to make it a repository in which we invite others to add test files for their software that we would autmatically test --- provided they are will to help in debugging if something goes wrong (or something needs updating because they change. Not sure if it will have a great traction initially, but perhaps over time ...

**Comment by blefloch** [comment]
On 5/5/21 9:59 PM, Frank Mittelbach wrote:
> @blefloch <https://github.com/blefloch> an interesting idea. Maybe one step
> further would be to make it a repository in which we invite others to add test
> files for their software that we would autmatically test --- provided they are
> will to help in debugging if something goes wrong (or something needs updating
> because they change. Not sure if it will have a great traction initially, but
> perhaps over time ...

Thinking some more (or maybe it's just because it's late at night here), I don't
think we have the resources.

Basically, it would be nice if someone was maintaining this, because we could
use it as a complementary tool to grepping texlive before making some of the
more dangerous changes, but I think no-one will have the time to maintain it.
