### ISSUE TITLE
Document rationale for pre-loading parts of expl3 also for pdftex engine

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#240]
This surely got discussed internally but as it is a somewhat significative change promised at horizon 2020-02-02 I feel the current phrasing in ltnew31 is lacking in details. It convincingly argues that lualatex and xelatex LaTeX users anyhow for the most part are expected to use fontspec which requires expl3 and that Unicode data loading time significantly slows down document build. Regarding pdflatex I see no such convincing argument. Why not build the LaTeX2e format the legacy way, as long as LaTeX2e itself is not written in expl3? That is my question.

edit: I meant as long as bits and pieces of LaTeX2e are not written using expl3.

**Comment by FrankMittelbach** [comment]
The argument also holds for pdftex as well, as a large number of documents load packages that implicitly load expl3 (for example because they load `xparse` if nothing else) or load expl3 because the package itself is written in it. 

We also have don't have the resources the maintain different code bases unnecessarily and  to advance LaTeX we need to standardize and bring back more and more into a common code base  instead of diverting further.

Furthermore in the future we intend to do the necessary rewrites and extensions using the expl3 code base from which point on expl3 would be loaded virtually in all pdftex documents as well (and not only in many, as it is now the case). So moving it now to the kernel is a logical prestep and at this point intented to be transparent other than benefitting all documents that anyhow already use expl3 at some point in the preamble.

_As a side note: the issue tracker for 2e is intended to be for issues and bugs only and not for philosophy questions and discussions around future directions and I would appreciated if we keep it this way.  That is better done on the LATEX-L mailing ist or if you want to by mailing the team directly. thanks_

**Comment by jfbu** [comment]
I wish to take this into account and for this reason do not comment on the items of your message except to point out that it would be interesting if ltnews31 actually included  

> ... in the future we intend to do the necessary rewrites and extensions using the expl3 code base

**Comment by FrankMittelbach** [comment]
yeah understood, but as ltnews31 says, it is under construction and incomplete ... should have mentioend that above too, Anyway, merry Xmas - Frank
