### ISSUE TITLE
Docstrip can't put \endinput at end of file

### ISSUE THREAD

**Issue by Skillmon** [latex3/latex2e#244]
The following saved as `endinputbugmwe.dtx` will not put `\endinput` and the following `\BUGREPORT` into the generated file but only the first `\BUGREPORT`:

```latex
% \iffalse meta-comment
%
% this is an MWE to show the endinput bug
%
%<*driver>
\def\nameofplainTeX{plain}
\ifx\fmtname\nameofplainTeX\else
  \expandafter\begingroup
\fi
\input docstrip.tex
\askforoverwritefalse
\preamble

Just a quick example of endinput failing to show up in the final file.

\endpreamble
\postamble
\endpostamble
\generate{\file{endinputbugmwe.tex}{\from{endinputbugmwe.dtx}{tex}}}
\ifx\fmtname\nameofplainTeX
  \expandafter\endbatchfile
\else
  \expandafter\endgroup
\fi
%
\documentclass{l3doc}
\begin{document}
  This is a bug report.
  \DocInput{endinputbugmwe.dtx}
\end{document}
%</driver>
% \fi
%
% \begin{implementation}
%
% \clearpage
%
% \section{Implementation}
% This should show the bug
%    \begin{macrocode}
%<*tex>
\BUGREPORT
\endinput
\BUGREPORT
%</tex>
%    \end{macrocode}
%
% \end{implementation}
%
\endinput
```

**Comment by Skillmon** [comment]
An `\endinput` inside an `\if...` statement like `\expandafter\ifx\csname inputguard\endcsname\relax\else\expandafter\endinput\fi` works (luckily).

**Comment by u-fischer** [comment]
You need to indent the \endinput:

```
\BUGREPORT
 \endinput
\BUGREPORT
```

> To allow also real \endinput commands in the source \endinput is only recognized
when it occurs directly at the beginning of a line

**Comment by FrankMittelbach** [comment]
As @u-fischer said, `\endinput` has a dual purpose: if used at the start of the line is interpret as "please end the file here" in any  other position it is considered parte of code and will be handled like any other code that is docstripped. So of you need `\endinput? as part of your code make sure it is not at the beginning of a line.

**Comment by Skillmon** [comment]
A bit counter-intuitive, IMHO it would make sense to generally ignore it in between of `\begin{macrocode}` and `\end{macrocode}`, but ok. Thanks for pointing this out!

**Comment by FrankMittelbach** [comment]
@Skillmon yes agreed, but after 30 years and literally thousands of sources files using it any change is likely to break something here and that doesn't seem to be worth it imho. But I agree with you that could have been designed differently.

**Comment by Skillmon** [comment]
@FrankMittelbach of course, changing it now is no good idea if that's the documented behaviour. What about `l3docstrip` is it possible to change it there (there shouldn't be too many documents relying on this behaviour using `l3docstrip`, I hope...)?

**Comment by FrankMittelbach** [comment]
well, l3docstrip is really just docstrip with a very thin wrapper, having different interfaces is in theory possible but it would mean copying and then altering a lot of code from docstrip to l3docstrip and I'm not sure that is time well spent. for me docstrip is something I have written more than 30 years ago and that was since then altered by others and it is code that has wel served even though it is something that I would do totally different if doing it fron scratch, but it is not something that I think is very sensible to "improve" (even though I agree that in the l3 area it would be likelyupward compatible).  But I leave this to @josephwright if he really want to reopen that for future consideration.
