### ISSUE TITLE
`\raggedright` may add a line in tough situations

### ISSUE THREAD

**Issue by eg9** [latex3/latex2e#247]
## Brief outline of the bug
Under `\raggedright`, if a line contains a very long word with discretionary hyphens, TeX might choose to make an additional line.

Source: https://tex.stackexchange.com/q/523828/4427

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\RequirePackage{latexbug}
\documentclass{article}

\begin{document}

\raggedright

methyl\-methyl\-methyl\-methyl\-methyl\-methyl\-methyl\-methyl\-methyl\-methyl\-%
methyl\-methyl\-methyl\-methyl\-methyl\-methyl\-methyl some more words

\end{document}
```

## Log file (required) and possibly PDF file  
```latex
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex 2020.1.6)  11 JAN 2020 14:18
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**methyl.tex
(./methyl.tex
LaTeX2e <2019-10-01> patch level 3
(/usr/local/texlive/2019/texmf-dist/tex/latex/latexbug/latexbug.sty
Package: latexbug 2019/10/15 v1.0g Bug-classification
)
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/10/25 v1.4k Standard LaTeX document class
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2019/10/25 v1.4k Standard LaTeX file (size option)
)
\c@part=\count80
\c@section=\count81
\c@subsection=\count82
\c@subsubsection=\count83
\c@paragraph=\count84
\c@subparagraph=\count85
\c@figure=\count86
\c@table=\count87
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
) (./methyl.aux)
\openout1 = `methyl.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.

[1

{/usr/local/texlive/2019/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
(./methyl.aux) ) 
Here is how much of TeX's memory you used:
 723 strings out of 492163
 12613 string characters out of 6125307
 68100 words of memory out of 5000000
 5171 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 25i,4n,19p,147b,495s stack positions out of 5000i,500n,10000p,200000b,80000s
</usr/local/texlive/2019/texmf-dist/fonts/type1/public/amsfonts
/cm/cmr10.pfb>
Output written on methyl.pdf (1 page, 13199 bytes).
PDF statistics:
 12 PDF objects out of 1000 (max. 8388607)
 7 compressed objects within 1 object stream
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)
```

## Output

<img width="677" alt="image" src="https://user-images.githubusercontent.com/302839/72204949-b296b900-347d-11ea-94d3-972e4d06d5e0.png">

## Proposal

Add `\finalhyphendemerits=\z@` to the code for `\raggedright`.

## Output with proposed fix

<img width="681" alt="image" src="https://user-images.githubusercontent.com/302839/72204972-f7225480-347d-11ea-87c9-06ace23da1f6.png">

**Comment by FrankMittelbach** [comment]
I see your argument though normally I would say something like that shouldn't be  done in `\raggedright` because it robs you of possibilities. E.g., if you set `\hyphenpenalty=0` to allow hyphenation in raggedright you still might want to penalize a hyphen in the second last line

But I agree that if one considers `\raggedright` the way it is now (i.e., never hyphenate unless the word itself is longer than a line) then this setting makes sense.

**Comment by FrankMittelbach** [comment]
Couple of comments ...

 - the same applies to `\centering` and `\raggedleft` so it should probably be fixed in all 3 places
 -  setting `\finalhyphendemerits` means that its value is wrong if inside a `\parbox` or a `minipage` is started. Especially with `\centering`this is not an unlikely scenario, so the fix should include an automated way to restore the value in such situations (e.g., via `\@parboxrestore`)

Not sure at the moment how to best make that happen without introducing a lot of (unnecessary) code. Suggestions welcome.

**Comment by car222222** [comment]
Probably not relevant at this stage, but another improvement that never got into 2e is to not misuse \par for forced linebreaks.  
But maybe there were good reasons why it was done this way in 2.09?

**Comment by FrankMittelbach** [comment]
> But maybe there were good reasons why it was done this way in 2.09?

I'm not sure there was a *good* reason but in contrast to the topic of the issue (which is a bug basically) preventing \par from being misued for a linebreak (not sure sure how you would do that) would be a change in behavior wouldn't it, so it would trip a lot of old documents because people are bound to have used that.

**Comment by FrankMittelbach** [comment]
>   * setting |\finalhyphendemerits| means that its value is wrong if
>     inside a |\parbox| or a |minipage| is started. Especially with
>     |\centering|this is not an unlikely scenario, so the fix should
>     include an automated way to restore the value in such situations
>     (e.g., via |\@parboxrestore|)
> 
> Not sure at the moment how to best make that happen without introducing 
> a lot of (unnecessary) code. Suggestions welcome.
> 

given that \@arrayparboxrestore uses \sloppy it is probably overkill to 
reset \finalhyphendemerits, so I think I leave it alone.
