### ISSUE TITLE
After amsmath.sty is loaded \DeclareMathAccent for existing accent fails

### ISSUE THREAD

**Issue by DiegoPuga** [latex3/latex2e#254]
## Brief outline of the bug

After the amsmath.sty package is loaded, the command \DeclareMathAccent cannot be used to declare existing math accents, like \acute. So, for instance, my mathpazo.sty package (currently part of PSNFSS) can no longer be loaded after amsmath. Other packages changing math fonts likely run into trouble too. The minimal code below just loads amsmath.sty and then includes two lines from mathpazo.sty

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{amsmath}
\DeclareSymbolFont{upright}       {OT1}{zplm}{m}{n}
\DeclareMathAccent{\acute}{\mathalpha}{upright}{"13}

\begin{document}
\end{document}
```

## Log file (required) and possibly PDF file  

This fails with the error:
./amsmatthbug.tex:5: LaTeX Error: Command `\acute' already defined.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
l.5 ...athAccent{\acute}{\mathalpha}{upright}{"13}
? 
./amsmatthbug.tex:5: Emergency stop.
[amsmatthbug.log](https://github.com/latex3/latex2e/files/4099346/amsmatthbug.log)

**Comment by davidcarlisle** [comment]
I get no error with a current release, I note you are using ` LaTeX2e <2018-12-01>` there have been several releases since then, the current public release is `LaTeX2e <2019-10-01> patch level 3` (with another release planned fro the start of February.

`\DeclareMathAccent` has been changed since your release `% \changes{v3.0s}{2019/08/27}{Make math accents robust}`

**Comment by FrankMittelbach** [comment]
As David said, you seems to run an old LaTeX kernel/format

`LaTeX2e <2018-12-01>`

into whic you load a (manually?) added amsmath package
`
/usr/local/texlive/2019/texmf-dist/tex/latex/amsmath/amsmath.sty`

This can't work because amsamth is a core part of LaTeX and its release just need to fit the release of LaTeX.

Maybe you your system failed to regenerate the formats after getting updated files (normally that should happen automatically. Or maybe you generated a format locally and it is still picked up. So try and figure out why on your system you see LaTeX 2018 while your setup indicates you have TeXLive from 2019 otherwise --- we can't help you with that, sorry.

**Comment by blefloch** [comment]
Should amsmath say \NeedsTeXFormat{...} with the right date?  (I don't
know the syntax.)

**Comment by FrankMittelbach** [comment]
@blefloch could do I guess

**Comment by DiegoPuga** [comment]
You're right, of course, it was an outdated format file. Sorry for the trouble.

The latex distribution was up to date but the formats were not. The formats had not been regenerated because a left-behind language.dat file referred to date-specific files with German hyphenation patterns from the dehyph-exptl package and this made the regeneration of the formats fail.

I don't quite understand why the dehyph-exptl package changes the file names to incorporate a new date in the name itself with every release (e.g. dehyphn-x-2019-04-04.tex), but in any case this is resolved, thank you.

**Comment by FrankMittelbach** [comment]
> I don't quite understand why the dehyph-exptl package changes the file names to incorporate a new date in the name itself with every release (e.g. dehyphn-x-2019-04-04.tex), but in any case this is resolved, thank you.

probably to enable you to set up some explicit hyphenations. After all changing the patterns might mean that your document changes, this way you can set up something is deliberately using patterns from a specific date and they can live side by side ... but I'm just guessing.
