### ISSUE TITLE
correct inputenc docu about greek

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#278]
inputenc.pdf writes in the utf8 section

>... but currently already falls short on languages like
>Greek (which has some semi-offcial font support, but for which corresponding
>UTF-8 mappings still need to be defined).

This should be changed. Greek is now well supported with the packages greek-fontenc and greek-inputenc based on LGR.

**Comment by FrankMittelbach** [comment]
@u-fischer would you mind doing the docu update as you think it should be these days?

**Comment by u-fischer** [comment]
@FrankMittelbach  I'm not sure what to do here. The only language with missing dfu I remember from the last years is thai (and I think I even made a dfu and sent it to the maintainer at some time). So the only idea I have is to stay vage and not mention a concrete language. Does this sounds okay:

> % This works well enough for the main Western languages for which \LaTeX{}
> % has proper font encoding support, but can fall short on other
> % languages.
> %
> % For some of these languages all that remains doing is
> % to provide the necessary mappings and stick them into |utf8ienc.dtx|, so
> % volunteers are welcome. For other languages that do not fit well into
> % \LaTeX{} font selection scheme, e.g., Asian languages the outlined inputenc
> % approach will not work. If that is the case one can try using Dominique
> % Unruh's option |utf8x| for inputenc which has a somewhat different approach
> % and encodes many more UTF-8 characters than the standard |utf8| option.
> % However, we recommend to do so only if you really need such alphabets and can not
> % switch to one of the unicode engines xelatex or lualatex as
> % there are problems with this extended approach which were precisely the
> % reason that we decided to limit the support to what is properly supported
> % within the boundaries of \LaTeX's font selection.
>

**Comment by FrankMittelbach** [comment]
looks fine to me (I just updated the text)

**Comment by car222222** [comment]
Since we are rewording this, please can we change Asian languages.  What do we, or the original author really mean here?    Asia is big, and even the number of script-families used within its boundaries is quite large.  Thus I am sure it can not possibly refer to all, or even most, Asian languages.

When that is sorted we can perhaps move onto the meaning of the remainder of that sentence as I cannot follow it.

**Comment by car222222** [comment]
I shall not here get into correct use of the word alphabet.  Maybe better to just say characters here.

**Comment by FrankMittelbach** [comment]
@car222222 feel free to reword as you see fit in the development branch. alphabet = scripts or characters as you see. Personally I dont see a need to change Asian languages. The nagative applies to nearly every script-family  there and it is given as an example. But as I said, please just update if you think you have a better wording or want to say something different.

**Comment by car222222** [comment]
Maybe what is not covered could be better summarised as:  non-European scripts ? 
rather than referring to languages at all.   

I thought that dfu files are attached to (8-bit) font encodings, thus I see no obvious  relationship to languages; but I can see that it is possible that an occasional double may work only for a particular language or even a single dialect.  Nevertheless it is not clear that any of these files should be named for a language.

**Comment by car222222** [comment]
@FrankMittelbach You are too kind.  But it may be better to wait for clarification of why ‘language’ is currently used, etc. before doing changing things and doing the copy editing.
