### ISSUE TITLE
w column in array  why we need $$ for every cell !?  

### ISSUE THREAD

**Issue by seloumi** [latex3/latex2e#297]
## Brief outline of the bug

Using `w` (or `W`)  column type provided by the `array`  package in an array environment requires to add $  $ for every column, I think best and more natural  if in `array`  environment  `w` works like `c` column without need to add $ $  for every cell (It might be better if this can be done implicitly in the definition of `w`  column )  

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}      
\documentclass{article}
\usepackage{array}

\begin{document}

% for c column

$$
\begin{array}{c}
f(x)= x^2+x+1
\end{array}
$$

% for w column note the need of $ $ 

$$
\begin{array}{wc{3cm}}
$f(x)= x^2+x+1$
\end{array}
$$

\end{document}
```

## Log file (required) and possibly PDF file  
[test.pdf](https://github.com/latex3/latex2e/files/4272479/test.pdf)
[test.log](https://github.com/latex3/latex2e/files/4272478/test.log)

**Comment by eg9** [comment]
A `w` column is a form of `\makebox`, so its argument is typeset in text mode; just like `p` columns are in an `array`.

**Comment by FrankMittelbach** [comment]
@eg9 Technically that is true and p columns are also typeset as text in an `array`. However I do see the interface logic suggested by @seloumi  that it is more like a `c` or `l` column only set to a specific width and obviously it could have been implemented like that. The problem is that this is a breaking change and the introduction of `w`and `W`is probably too long ago to make any change here.   

Maybe via an option enabling it or perhaps via some extended syntax such as `w${3cm}` or `w$r{3cm}` or something, have to think about that.

**Comment by davidcarlisle** [comment]
Related to this I just noticed the `nicematrix` package which documents in a footnote:

> However, for the columns of type w and W, the cells are composed in math mode (in the environments of nicematrix) whereas in {array} of array, they are composed in text mode.

**Comment by car222222** [comment]
That sounds sensible: environments called *matrix* or similar mathematical terms always use math-mode for all cells.  (Hence I guess no p specifier.)
