### ISSUE TITLE
Inconsistent cramped style for sin, cos, tan

### ISSUE THREAD

**Issue by Eldrad-Ulthran** [latex3/latex2e#348]
## Brief outline of the bug

Superscripts on \sin, \cos and \tan inside \sqrt are placed on different heights, and if there is more content with superscripts inside the same sqrt, the superscripts are not placed at the same height. In the example, the square on F is placed a bit lower than on tan or sin, which doesn't look too good. Also the total size of the sqrt is affected.
It looks as if \tan and \sin do not have a cramped style, but \cos has.
Compiled with pdflatex.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\begin{document}

\begin{equation}
 \sqrt{F^2 + \tan^2\phi} ~~ \sqrt{F^2 + \cos^2\phi} ~~ \sqrt{F^2 + \sin^2\phi}
\end{equation}

\end{document}
```

## Log file (required) and possibly PDF file

[cramped_superscript_sqrt.log](https://github.com/latex3/latex2e/files/4850387/cramped_superscript_sqrt.log)
  
[cramped_superscript_sqrt.pdf](https://github.com/latex3/latex2e/files/4850386/cramped_superscript_sqrt.pdf)

**Comment by u-fischer** [comment]
The problem is not cramped style, but that the operators have different height, as tan contains a `t` and sin an `i`.

You can smash these heights, e.g.

~~~~
\documentclass{article}

\makeatletter
\DeclareRobustCommand\sin{\mathop{\vphantom{\operator@font c}\smash{\operator@font sin}}\nolimits}
\DeclareRobustCommand\tan{\mathop{\vphantom{\operator@font c}\smash{\operator@font tan}}\nolimits}
\makeatother
\begin{document}

\begin{equation}
 \sqrt{F^2 + \tan^2\phi} ~~ \sqrt{F^2 + \cos^2\phi} ~~ \sqrt{F^2 + \sin^2\phi}
\end{equation}

\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/86104034-ced6f280-babd-11ea-852c-bee2073b5766.png)

A similar problem with the amsmath definitions has been discussed at https://tex.stackexchange.com/a/547660/2388.

**Comment by Eldrad-Ulthran** [comment]
Thanks for linking the thread, I missed that while searching. That means, having the squares at different heights inside one sqrt is "working as intended"? I didn't expect that, I assumed that pushing all superscripts on one common level (minimum or maximum available height, whatever pleases) would give nicer results.

**Comment by davidcarlisle** [comment]
It does look better to have them the same, but you know sin cos and tan are related , tex can't take such value judgements, and it can't make all superscripts the same height, you would expect \frac{1}{2}^2  to have a higher 2 than x^2 . The height is determined by the font so not really in latex's control.  Or for specific operators you can force them to be the same, as in the comment above where sin, cos, tan are all given the height of c.

**Comment by FrankMittelbach** [comment]
Arguably it does (in many cases) but your milage varies and it is as designed by Don Knuth. So bottom line, it works as intended.

**Comment by u-fischer** [comment]
> Arguably it does (in many cases) but your milage varies and it is as designed by Don Knuth

I wouldn't say that is is designed by Don Knuth: it is LaTeX and amsmath which define the operator names and these definitions could make them all the same height. But it would naturally quite probably change the output of documents.

**Comment by FrankMittelbach** [comment]
> I wouldn't say that is is designed by Don Knuth: it is LaTeX and amsmath which define the operator names and these definitions could make them all the same height

well I would :-). From plain.tex (the mother of amsmath etc ...):
```
\def\sin{\mathop{\rm sin}\nolimits}
\def\tan{\mathop{\rm tan}\nolimits}
```
That is not exactly the same definition used in LaTeX but it is its origin and so since 1986.

**Comment by car222222** [comment]
More likely it is designed to a specification from from the AMS editorial staff rather than any individual.  But maybe that it ‘just what their phototypesetters had been doing for 20-30 years’ without anyone worrying what it looked like.  

“Design” is a somewhat 21st Century luxury concept when it comes to churning out the pages!
