### ISSUE TITLE
Documentation suggestion for lthooks/ltshipout - for the 2020/10/01 format

### ISSUE THREAD

**Issue by daleif** [latex3/latex2e#365]
(not sure if this is the right place to place this request)

While playing with shipout/background hooks in memoir, I noticed that something similar to 

```
\AddToHook{shipout/background}[trimmarks]{\put(0,0){\trimmarks}}
\AddToHook{shipout/background}[bg]{\put(0,0){\color{orange}\raisebox{-\stockheight}{\rule{\stockwidth}{\stockheight}}}}
\DeclareHookRule{shipout/background}{bg}{before}{trimmarks}
\ShowHook{shipout/background}
```

lists

```
The hook 'shipout/background':
 Code chunks:
    trimmarks -> \put (0,0){\trimmarks }
    bg -> \put (0,0){\color {orange}\raisebox {-\stockheight }{\rule {\stockwidth }{\stockheight }}}
 Extra code next invocation:
    ---
 Rules:
    bg|trimmarks with relation <
 Execution order (after applying rules):
    not set yet
```

Whereas the execution order is listed if I move the `\ShowHook` after `\begin{document}`

Ulrike mentioned in chat that the sorted order are not updated immediately.

It might be an idea to mention this fact in the documentation for `\ShowHook` as it might else confuse readers.

---

BTW in ltshipout in the documentation for shipout/background, and example would be nice. Initially I completely missed that I need to use something similar to

```
\AddToHook{shipout/background}{\put(....){xyz}}
```

I just used

```
\AddToHook{shipout/background}{xyz}
```

which worked, but then the reordering (above) did not work).

---

Besides this, I think these hooks are going to be very very useful. When we also get `\pagecolor` fixed then a long standing memoir bug will be resolved (currently memoir trimmarks appear behind the page color), my example at the top was a test to see if we could color the bg without `\pagecolor` and in the right order.

**Comment by PhelypeOleinik** [comment]
The sorting is delayed to `\begin{document}` because every change in a hook (adding/removing code and setting a relation) would require sorting, and since most of these operations are done before `\begin{document}`, delaying the sorting saves some time.

That said, this is solely for performance, so I think it would be useful to have `\ShowHook` initialise the hook before showing it: most usages of `\ShowHook` will probably be confined to the preamble.

**Comment by FrankMittelbach** [comment]
> That said, this is solely for performance, so I think it would be useful to have `\ShowHook` initialise the hook before showing it: most usages of `\ShowHook` will probably be confined to the preamble.

Agreed, that is a sensible improvement as well as a simplification. But it makes the hook act differently, because if the hook becomes expandable (if its code is expandable) after \ShowHook  while without \ShowHook it  is definitely unexpandable because the initialization does assignments when \UseHook is called in the preamble.

It is a minor point because expandable hook code is seldom needed  but perhaps that suggests that we also provide \InitializeHook so that it possible to force hook initialization at a different point than \HookUse

**Comment by FrankMittelbach** [comment]
> BTW in ltshipout in the documentation for shipout/background, and example would be nice. Initially I completely missed that I need to use something similar to
> 
> ```
> \AddToHook{shipout/background}{\put(....){xyz}}
> ```

agreed. The documentation in parts is at the moment too technical and needs further work. Examples for such hooks is one area.

**Comment by PhelypeOleinik** [comment]
> Agreed, that is a sensible improvement as well as a simplification. But it makes the hook act differently, because if the hook becomes expandable (if its code is expandable) after \ShowHook while without \ShowHook it is definitely unexpandable because the initialization does assignments when \UseHook is called in the preamble.

No, the initialisation is done by `\UseHook`, so `\ShowHook` would cause it to be initialised twice (redundant yes, but we're debugging anyway, so performance won't be a problem).

> It is a minor point because expandable hook code is seldom needed but perhaps that suggests that we also provide \InitializeHook so that it possible to force hook initialization at a different point than \HookUse

But this could be added anyway, in case expandability is required before `\begin{document}`.

**Comment by FrankMittelbach** [comment]
Some updates have happened but a real article on the topic  with examples will have to wait for TUG2021 I guess. I'll close this here and track the progress in #410.
