### ISSUE TITLE
\multicolumn reinserts suppressed \tabcolsep 

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#37]
## Brief outline of the bug

`\multicolumn` seems to always insert at the start a `\tabcolsep`. This means that if the space has been suppressed by a previous `@{}` declaration it must be suppressed by a *following* `\multicolumn` too. I'm not sure if this count as a bug but it contradicts the general rule that (apart from the first) a `\multicolumn` needs only to take care about the following intercolumn stuff. A similar report is latex/3140.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug} 
\documentclass{book}
%\usepackage{array}
\begin{document}

%additional tabcolsep:
\begin{tabular}{l@{!}l}
abc &XXX\\
    &\multicolumn{1}{l}{XXX}\\
\end{tabular}

%expected output    
\begin{tabular}{l@{!}l}
abc &XXX\\
    &\multicolumn{1}{@{}l}{XXX}
\end{tabular}

\end{document}
```
![multicbug](https://user-images.githubusercontent.com/4047173/38978145-c8a30744-43b6-11e8-81a9-cf8e89b26718.PNG)

## Log file (required) and possibly PDF file  
[test-utf8.log](https://github.com/latex3/latex2e/files/1927107/test-utf8.log)

**Comment by FrankMittelbach** [comment]
As I read page 206 of the LaTeX manual this is clearly a bug as there Leslie states that "except for the first column the column spec is divided in parts where each part starts at l, r, c, or p and that \multicolumn replaces the parts according to the number of its first argument, so it should not add anything according to that description.

However, whether or not that "bug" can be changed after that time is a different matter.

**Comment by sony976837769** [comment]
[[反璞歸真為真如 砱崆御枵麮驉無 陰陽日月為乾坤 天地遨遊趣楈錓]]
反璞歸真 黃 保欽親筆瀛題

**Comment by FrankMittelbach** [comment]
@sony976837769 google translate is of little help here

**Comment by FrankMittelbach** [comment]
After some discussions our conclusion is that this should be considered a documentation bug or documentation inaccuracy (in Leslie's manual). This is clearly the case that this is the situation since day one and even though ther are probably only a few documents that would be affected if changed, the change would be rather elabroate (and not easy to make fault-proof). As a result, it would likely give as real bugs, because changing the array code in many places just for this may mean that several packages hooking into it might fall over.

So the correction will be an errata entry in manual.err

**Comment by FrankMittelbach** [comment]
errata updated by Leslie
