### ISSUE TITLE
source2edoc.cls in runtime?

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#384]
New latex2e-dev has texmf-dist/tex/latex-dev/base/source2edoc.cls which starts with
```
\ProvidesClass{source2edoc}
              [2020/08/16 v0.1 Quick hack to typeset source2.tex
               (not usable for anything else and buggy -- will vanish again)!]
```

Even though it's promised to "vanish again", I wanted to mention it. Doesn't seem like it should be installed in the runtime, in principle.

I imported the new release anyway, without change ...

**Comment by FrankMittelbach** [comment]
Not installing it in runtime means that somebody trying to typeset source2e.tex will not easily be able to, so I think it is better to have it in runtime while it may be needed. The danger that somebody is going to use it as his or her class file are slim and if so  it should be easily replacable by l3doc later, because everything special is really tied to the way the 2e sources look.

**Comment by kberry** [comment]
fine, closing.
