### ISSUE TITLE
strange behaviour of \declare@file@substitution and \PassOptionsToPackage

### ISSUE THREAD

**Issue by komascript** [latex3/latex2e#386]
I've tried to reimplement `\ReplacePackage` of `scrlfile` using `\declare@file@substitution`. With `scrlfile` you can use something like:

```latex
\documentclass{article}
\usepackage{scrlfile}
\ReplacePackage{german}{babel}
\PassOptionsToPackage{main=ngerman}{babel}
\usepackage{german}
\begin{document}
Language is \languagename
\end{document}
```

resulting in loading `babel` with language set to `ngerman`.

I've tried the same with `\declare@file@substitution` instead of `\ReplacePackage`:

```latex
\documentclass{article}
\makeatletter
\declare@file@substitution{german.sty}{babel.sty}
\makeatletter
\PassOptionsToPackage{main=ngerman}{babel}
\usepackage{german}
\begin{document}
Language is \languagename
\end{document}
```

Here the language is `nil`. So I've tried to pass the option to package `german` instead of `babel`:

```latex
\documentclass{article}
\makeatletter
\declare@file@substitution{german.sty}{babel.sty}
\makeatletter
%\ReplacePackage{german}{babel}
%\PassOptionsToPackage{main=ngerman}{babel}
\PassOptionsToPackage{main=ngerman}{german}
\usepackage{german}
\begin{document}
Language is \languagename
\end{document}
```

but this results in error message:

```
(/usr/local/texlive/2020/texmf-dist/tex/generic/babel/babel.def
! Argument of \bbl@tempa has an extra }.
<inserted text> 
                \par 
l.1375 ...packagewith{babel}{KeepShorthandsActive}
                                                  %
? 
```

The same error occurs, if I use a global option:

```latex
\documentclass[main=ngerman]{article}
\makeatletter
\declare@file@substitution{german.sty}{babel.sty}
\makeatletter
%\ReplacePackage{german}{babel}
%\PassOptionsToPackage{main=ngerman}{babel}
%\PassOptionsToPackage{main=ngerman}{german}
\usepackage{german}
\begin{document}
Language is \languagename
\end{document}
```

So it seems, that I cannot use `\declare@file@substitution` to implement `\ReplacePackage`. However following works:

```latex
\documentclass{article}
\makeatletter
\disable@package@load{german}{\RequirePackage{babel}}
\makeatother
\PassOptionsToPackage{main=ngerman}{babel}

\usepackage{german}
\begin{document}
Language is \languagename
\end{document}
```

So if the behaviour of `\declare@file@substitution` is intended, I will try to reimplement `\ReplacePackage` this way. Unfortunatly I cannot use this for `\ReplaceClass`.  So currently I do not know how to bring back that command using `ltfilehook`.

**Comment by PhelypeOleinik** [comment]
Since `babel` is loaded (even if from a substitution), options _should_ be passed on, so this was probably an oversight from me. I'll investigate.

I wonder what should be the behaviour, if you pass the option to `german.sty` rather than to `babel.sty`.  Seems like the option should _not_ be passed, since `german.sty` is not actually loaded (unless the loaded package, `babel` here`, loads it internally).

**Comment by komascript** [comment]
@PhelypeOleinik It is only an example. Sometimes to replace one package by another (newer) one, passing an option is needed, e.g., to be more compatible to the replaced package. So there should be a documented solution to pass options to the replacement. `\ReplacePackage` of `scrlfile` does provide such a documented solution, that does not need any changes of the replacement package. So as the first example shows, it does work with `babel`. But re-implementation using only `ltfilehook` instead of patching the kernel is not as easy as it seems.

The intended behaviour in all examples is the one of the first example: `babel` should be loaded with option `main=ngerman` to replace package `german`.

**Comment by u-fischer** [comment]
babel doesn't load german, but if it did you would probably get a circular loop and a capacity exceeded error:

~~~~
\begin{filecontents}{testA.tex}
blub
\end{filecontents}
\begin{filecontents}{testB.tex}
\input{testA}
\end{filecontents}

\documentclass{article}
\makeatletter
\declare@file@substitution{testA.tex}{testB.tex}
\makeatother

\begin{document}
\input{testA}
\end{document}
~~~~

**Comment by komascript** [comment]
@u-fischer I know that `babel` should not load `german`. In the example(s) it should be loaded using option `main=ngerman` to replace `german`. Yes, I know, that option `main=ngerman` originally is intended to be an replacement for package `german` not only `ngerman` (because the used class still uses `\usepackage{german}` and cannot be changed).

**Comment by u-fischer** [comment]
@komascript personally I think that using a file substituation feels wrong here. 

      \disable@package@load{german}{\RequirePackage{babel}}

looks saner. 




> I know that `babel` should not load `german`.

I know that you know ;-). I didn't commented on this, but on @PhelypeOleinik's remark what should happen *if* babel would load german which lead me to check if we get loops here.

**Comment by komascript** [comment]
@u-fischer Once again: This is an example only. I can give you another one:

```latex
\documentclass{article}
\makeatletter
\declare@file@substitution{scrpage2.sty}{scrlayer-scrpage.sty}
\makeatletter

\usepackage{scrpage2}

\begin{document}
Test
\end{document}
```

results in an error. Once again original replacement with `scrlfile`:

```
\documentclass{article}
\usepackage{scrlfile}
\ReplacePackage{scrpage2}{scrlayer-scrpage}

\usepackage{scrpage2}

\begin{document}
Test
\end{document}
```

works as a transparent substitution.

The documentation of `\declare@file@substitution` in `ltfilehook-doc.pdf` explains:

> The main use case for this declaration is to provide a corrected version of a package
that can’t be changed (due to its license) but no longer functions because of L A TEX kernel
changes, for example, or to provide a version that makes use of new kernel functionality
while the original package remains available for use with older releases.

But if it seams not to be usable for transparent package (or class) substitutions, is it really suitable for that main use case?

**Comment by u-fischer** [comment]
@komascript  sorry that I'm a bit short, I'm just making lunch. I do understand the problem and there is something wrong, either in the code or the documentation or the concept. My comments are meant to find out what ;-).

**Comment by FrankMittelbach** [comment]
The idea of `\declare@file@substitution` is to be transparent for technical updates, that is

 - the user interface is and should remain `\usepackage{foo}` but internally `foo-fixed.sty`is loaded
 - foo-fixed would still announce itself as foo.
 - the fact that the babel example (with `\PassOptionToPackage{main=ngerman}{german}`) is a bit surprising and seems wrong (it worked for me with other examples, eg varioref).

But this is already getting outside the intended use case. For a drastical replacement of one package with a totally different one, I think Ulrike's suggestion of using `\disable@package@load` together with `\RequirePackage` in the second argument is not a bad choice.

In any case this may need looking/thinking about a bit more. Sorry on the run packing for a cycling trip and not online during the next days.

**Comment by komascript** [comment]
@u-fischer I think, for transparent package/class substitutions the substitution should not be done at input level. Changing the file name argument of `\@loadwithoptions` or `\@onefilewithoptions` like I've done in `scrlfile` could do it. But I was told not to patch internal kernel commands any longer, so I'm searching for another solution.

**Comment by PhelypeOleinik** [comment]
@komascript With my comment

> I wonder what should be the behaviour, if you pass the option to `german.sty` rather than to `babel.sty`. Seems like the option should _not_ be passed, since `german.sty` is not actually loaded (unless the loaded package, `babel` here`, loads it internally).

I meant as a general "what should happen" scenario that options are passed to a package that is load-prevented (and maybe loaded inside the actually-loaded package), rather than the specific `german`--`babel` issue you mention.

Regardless of that, I would expect your example to work, because the options are passed to `babel.sty`, so they should be there when the package is loaded.  Later today I'll investigate

**Comment by u-fischer** [comment]
> Regardless of that, I would expect your example to work, because the options are passed to `babel.sty`, so they should be there when the package is loaded. Later today I'll investigate

Well I'm not sure if we want to pass the options to babel sty. As Frank wrote: the main idea of file substituation is to allow transparent fixes for packages. And this means that they should process the options of the original package. 

I mean what should happen here:

~~~~
\PassOptionsToPackage{optionA}{packageA}
\PassOptionsToPackage{optionB}{packageB-better}
\makeatletter
\declare@file@substitution{packageA.sty}{packageA-fixed.sty}
\declare@file@substitution{packageB.sty}{packageB-better.sty}
\makeatletter
~~~~

In the example with german, the real goal is to suppress the loading of german, as it harms. Replacing it with babel is actually neither needed nor necessarly the best idea - perhaps polyglossia is wanted, or a message would be better.

**Comment by FrankMittelbach** [comment]
Am 02.09.20 um 14:29 schrieb Ulrike Fischer:
>     Regardless of that, I would expect your example to work, because the
>     options are passed to |babel.sty|, so they should be there when the
>     package is loaded. Later today I'll investigate
> 
> Well I'm not sure if we want to pass the options to babel sty. As Frank 
> wrote: the main idea of file substituation is to allow transparent fixes 
> for packages. And this means that they should process the options of the 
> original package.
> 


yes but this is what happens (or should happen) right now, only that in 
case of babel it doesn't seem to work for some reason (wonder if that 
simply isn't a bug with babel).

\documentclass{article}
\makeatletter
\declare@file@substitution{foo.sty}{varioref.sty}
\makeatletter
\PassOptionsToPackage{german}{foo}
\usepackage{foo}
\begin{document}
\show\reftextbefore
\end{document}

foo gets "german" and that is passed onto varioref and the same happens 
if you put it into the optional argument of \usepackage. So somethign is 
wrong with the babel example.

**Comment by FrankMittelbach** [comment]
Am 02.09.20 um 14:29 schrieb Ulrike Fischer:
> I mean what should happen here:
> 
> |\PassOptionsToPackage{optionA}{packageA} 
> \PassOptionsToPackage{optionB}{packageB-better} \makeatletter 
> \declare@file@substitution{packageA.sty}{packageA-fixed.sty} 
> \declare@file@substitution{packageB.sty}{packageB-better.sty} \makeatletter |

in that case I would say optionA should get executed but optionB not as 
from our use case perspective packageB-better is not a document level 
package it is internal and still "represents" packageB  -- and that is 
what is currently implemented (or should be)

**Comment by u-fischer** [comment]
> yes but this is what happens (or should happen) right now, only that in case of babel it doesn't seem to work for some reason (wonder if that simply isn't a bug with babel).

No the example above is the other way round: it tries to add an option for the target package (babel) in your example) not for the source package (german). And `\PassOptionsToPackage{main=ngerman}{german}` doesn't work as both have a different option setup.

**Comment by FrankMittelbach** [comment]
Am 02.09.20 um 14:48 schrieb Ulrike Fischer:
> No the example above is the other way round: it tries to add an option 
> for the target package (babel) in your example) not for the source 
> package (german). And |\PassOptionsToPackage{main=ngerman}{german}| 
> doesn't work as both have a different option setup.

the first attempt but not the second -- and that is where the babel 
error appears (which is the strange thing)

**Comment by u-fischer** [comment]
@FrankMittelbach  right, it breaks at the `\@ifpackagewith{babel}{...}` in babel.def%

**Comment by u-fischer** [comment]
@FrankMittelbach  the problem is that `\opt@babel.sty` doesn't exist. As soon as it is provided, things behaves. But I'm not sure where to do this automatically (if at all). The file substitution code doesn't look like the right place, why should it care about package management details?

~~~~
\documentclass{article}
\makeatletter
\declare@file@substitution{german.sty}{babel.sty}
\ExplSyntaxOn
\tl_if_exist:cF{opt@babel.sty}{\tl_new:c{opt@babel.sty}}
% or 
%\PassOptionsToPackage{}{babel}
% or
%\AddToHook{package/before/german}{\tl_set_eq:cc {opt@babel.sty}{opt@german.sty}}%or something more complicated
\ExplSyntaxOff
\makeatother

\PassOptionsToPackage{french,main=ngerman}{german}
\usepackage{german}
\begin{document}
Language is \languagename
\end{document}
~~~~

**Comment by PhelypeOleinik** [comment]
@komascript Markus, I analysed the code and it was indeed wrong: see the test file and its log in 52a35a98. It shows that options passed to a package were sometimes passed to the replaced package, and sometimes to the target package, when queried by `\@ifpackagewith` (what `babel` uses), and options passed with `\PassOptionsToPackage` weren't picked up by `\ProcessOptions` (see the difference after fixing here: 214ab85f), so thanks a lot for finding that!

Other than some bookkeeping, the main changes are: 1) to update `\@currname` and `\@currext` in case a file substitution happened; and 2) to resolve the file substitution in `\@pass@ptions` (thus `\PassOptionsToPackage` has to be used after the substitution is declared). `babel` failed, as Ulrike diagnosed, because it expected `\opt@babel.sty` to contain the option, but since `\@currname` had the old value, options were incorrectly passed to `german.sty` (`babel` is parsing the options in an unusual manner, but it's not wrong).

The implementation in the `gh386` branch contains the fixes, so if you could test that it would be great. If you use `git` you can do `git develop gh386` to see the changes, otherwise adding this patch at the top of the document will replicate the new (hopefully correct) behaviour (using `etoolbox` to keep it shorter):
```latex
\RequirePackage{etoolbox}
\tracingpatches
\makeatletter
\ExplSyntaxOn
\cs_gset_eq:NN \@expl@str@map@function@@NN \str_map_function:NN
\cs_gset_eq:NN \@expl@char@generate@@nn \char_generate:nn
\ExplSyntaxOff
\def\@pass@ptions#1#2#3{%
  \edef\reserved@a{\@expl@@@filehook@resolve@file@subst@@w #3.#1\@nil}%
  \expandafter\xdef\csname opt@\reserved@a\endcsname{%
    \@ifundefined{opt@\reserved@a}\@empty
      {\csname opt@\reserved@a\endcsname,}%
    \zap@space#2 \@empty}}
\patchcmd\load@onefilewithoptions
  {\@filehook@set@CurrentFile}
  {\@filehook@set@CurrentFile
   \edef\@currpkg@reqd{\@currname.\@currext}%
   \ifx\CurrentFile\CurrentFileUsed
   \else
     \filename@parse\@curr@file
     \edef\@currname{\string@makeletter\filename@base}%
     \edef\@currext{\string@makeletter\filename@ext}%
   \fi}%
  {}{\FAILEDA}
\patchcmd\load@onefile@withoptions
  {\InputIfFileExists{\@currname.\@currext}}
  {\InputIfFileExists{\@currpkg@reqd}}
  {}{\FAILEDB}
\patchcmd\load@onefile@withoptions
  {\def\reserved@a}
  {\def\reserved@a{\@ifl@aded\@currext\@currname{}{\reserved@b}}%
   \def\reserved@b}
  {}{\FAILEDC}
\def\string@makeletter#1{%
  \@expl@str@map@function@@NN#1\@string@makeletter}
\def\@string@makeletter#1{%
  \char@if@alph{#1}%
    {\@expl@char@generate@@nn{`#1}{11}}%
    {#1}}
\def\char@if@alph#1{%
  \ifnum0\ifnum`#1<`A 1\fi\ifnum`#1>`z 1\fi
      \if\ifnum`#1>`Z @\fi\ifnum`#1<`a @\fi01\fi>0
    \expandafter\@secondoftwo
  \else
    \expandafter\@firstoftwo
  \fi}
\makeatother
```

Running the patch above with your test documents gives the expected `Language is ngerman` and no error, except for the one with `\documentclass[main=ngerman]{article}`, which gives `Language is nil` (but so it does with previous releases: `babel` doesn't pick a global `main=<lang>` option).

Thanks again for testing!
