### ISSUE TITLE
luatexja-fontspec and filehook Error: Detected unknown definition of \InputIfFileExists

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#391]
## Brief outline of the bug
Running lualatex-dev on attached results in:

```
...texmf-dist/tex/latex/filehook/filehook.sty:368: Package
filehook Error: Detected unknown definition of \InputIfFileExists.
```

Followed up by:
```
.../graphics.sty:106: LaTeX Error: Missing \begin{document}.
```

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{luatexja-fontspec}
\usepackage{unicode-math}
\usepackage{graphicx}
\begin{document}\end{document}
```

## Log file (required) and possibly PDF file  
Interface is so advanced it refuses to attach files. Or possibly does so multiple times. I can't tell. If you need the log, I can email it to you. If email still works.

**Comment by kberry** [comment]
Oops, the output I reported is without the \RequirePackage{latexbug}. That causes slightly different results. The basic problem is still there, though.

**Comment by FrankMittelbach** [comment]
Well, yes, filehook is broken, it expects a different definition of \InputIfFileExists -> so filehook needs changing which is why this report should really go to https://sourceforge.net/projects/filehook/

As a temporary fix you can load

    \usepackage{filehook-ltx}

first, but this is only a rough sketch of what is needed and doesn't implement all interfaces provided by filehook (only the most important ones).
Martin is aware of the issue for some time, but there has been no new version yet. If there will be none, then we may have to temporarily disable filehook and load filehook-ltx instead (until a new version appears) but I hope it will not come to that.

Anyway, as "latexbug" should have told you (but didn't because the error happened too early) is that this needs to be reported elswhere, i.e., at the above link.

**Comment by kberry** [comment]
filehook-ltx worked for me (my real document as well as the test one), thanks.

No way you can keep filehook working? I mean, it's your changes that broke it.

Lacking any fix from Martin, can you take it over? Have you written him yourself?

I hope the new latex is not made official while this is pending. Clearly it would break an awful lot of documents for filehook to be doa. ALthough maybe the pseudo-replacement of filehook-ltx would suffice. Thanks.

**Comment by kberry** [comment]
FWIW, Martin just replied to me, saying he's currently working on it, and: "I am planning to release something in the next days to avoid big issues on Oct 1st, but I guess further updates might be required." Fingers crossed ...

**Comment by FrankMittelbach** [comment]
If it comes in time, great. If not it will be taken care of from our end by temporarily (and automatically) loading fonthook-ltx when fonthook.sty is requested.
