### ISSUE TITLE
Package array: Using \def, \let, \newcommand etc... in \newcolumntype produces an error

### ISSUE THREAD

**Issue by Red-Quill** [latex3/latex2e#392]
In custom tabular cell types created with \newcolumntype, definitions (\def, \let, \newcommand etc.) seem to take effect only from second token onwards in the cell. Now redefining a command only for specific cell type in tabular fails.

Tested with XeLaTeX and pdfLaTeX on TeX Live 2020/Arch Linux.

```latex
\RequirePackage{latexbug}
\documentclass{article}

\usepackage{array}
\newcolumntype{A}{>{\def\TEST{BC}}l}

\begin{document}
% This produces an undefined control sequence error
\begin{tabular}{A}
\TEST
\end{tabular}

% This works correctly
\begin{tabular}{A}
A\TEST
\end{tabular}
\end{document}
```

[mwe.log](https://github.com/latex3/latex2e/files/5281635/mwe.log)

**Comment by zauguin** [comment]
This is by design. The first fully expanded token can still change the column type (e.g. using `\multicolumn{1}{c}{???}`) and therefore must be expanded before the column type settings are applied. You can avoid this using robust commands or by prepending `\protect` when they appear at the beginning of a cell. (If a command is undefined outside of the table, you can `\let` it to `\relax` outside to avoid the undefined control sequence.)

E.g.
```
\RequirePackage{latexbug}
\documentclass{article}

\DeclareRobustCommand \TEST {outside}
\usepackage{array}
\newcolumntype{A}{>{\DeclareRobustCommand\TEST{BC}}l}

\begin{document}
\begin{tabular}{A}
\TEST
\end{tabular}

% This works correctly
\begin{tabular}{A}
A\TEST
\end{tabular}
\end{document}
```
