### ISSUE TITLE
\IfFileExists with empty argument returns true

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#403]
```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass[]{article}
\begin{document}
\IfFileExists{}{\show\true}{\show\false}
\end{document}
```
gives 

```
> \true=undefined.
\reserved@a ->\show \true 
                          
```

in a current latex on windows, but false in texlive 2019.

## Log file (required) and possibly PDF file  

[test-utf8.log](https://github.com/latex3/latex2e/files/5334120/test-utf8.log)

**Comment by PhelypeOleinik** [comment]
In TeXLive 2019 it returned `\false` by accident.  It would check against `csnameendcsname.tex` (see #356), and if that file happened to exist, it would return true:
```latex
\begin{filecontents}{csnameendcsname.tex}
\end{filecontents}
\documentclass{article}
\begin{document}
\IfFileExists{}{\show\true}{\show\false}
\end{document}
```
which is much less likely, of course, but arguably more wrong: since `\input{}` reads `.tex` it makes _some_ sense for `\IfFileExists{}` to test against `.tex` as well.

An explicit emptiness test for `\IfFileExists` isn't good because it's virtually impossible to accept all variations of `\IfFileExists{}` and `\IfFileExists{\@empty}` and `\IfFileExists{\@gobble x}` and... without expanding the whole thing.

So I think the right solution would include a flag of some sort for `\set@curr@file` that allows or inhibits automatically adding `.tex`, and then setting it to false in cases like `\IfFileExists`.

**Comment by FrankMittelbach** [comment]
Yes, I think the behavior is correct as it is now
```
\@input{}
\InputIfFileExists{}{}{}
```
both find and input `.tex`and so I think it is correct if `\IfFileExists` returns true on an empty argument and it was a bug if it didn't in the past.

**Comment by wspr** [comment]
@u-fischer — thanks for passing this on, I've just sent an update in that hopefully fixes this

**Comment by FrankMittelbach** [comment]
> it suddenly executed `del ""` and I got a security question if I really want to delete all files

ouch, but I still maintain that the current behavior is correct and executing `del ""` is the wrong behavior
