### ISSUE TITLE
Please, add \cyrdash alias for  \textemdash in TU encoding

### ISSUE THREAD

**Issue by kia999** [latex3/latex2e#417]
## Brief outline of the enhancement

See https://tex.stackexchange.com/questions/566895/can-a-definition-of-cyrdash-command-be-added-to-tu-encoding

**LaTeX2e generally cannot add new features without an extreme amount of care to accommodate backwards compatibility. Please do not be offended if your request is closed for being infeasible.**

**Comment by FrankMittelbach** [comment]
thanks for the suggestion Igor. 

We discussed it among the team and our conclusion was that we think it should not be added to TU which should represent, as far as possible, only the support for standard Unicode characters and their official core LaTeX names. Language specific settings or specific support for typesetting traditions are better handled on the level of language support instead of cluttering the TU encoding file with various language specific aliases.
