### ISSUE TITLE
Warning on provided package should ignore `./` and raise no error about the load sequence `before \documentclass`

### ISSUE THREAD

**Issue by SieDa** [latex3/latex2e#426]
It should be the same if you load a class or style of a  package with  
`\documentclass{./pkgDir/Class} ` or `\documentclass{pkgDir/Class} `
`\usepackage{./pkgDir/Style}` or `\usepackage{./pkgDir/Style}`, 
which you need in the preambel to load `Class.cls` and `Style.sty` from` pkgDir/`.

In the class or style file you have to determin for one or the other in \ProvidesClass{...}.
 
`./` should be ignored to raise no warning if you specify the short form in the class or style without `./` . 
1. LaTeX Warning: You have requested package `./pkgDir/Style',
               but the package provides `pkgDir/Style'.

This is confusing, as it is loaded and means the same. I recognized this whily analyzing the issue related to it, which is not yet fixed: 

2. `! Package xkeyval Error: xkeyval loaded before \documentclass.`

I store my custom package file in a subdirectory `/pkgDir/` by handling that as a git submodule in different projects in different versions. 
By that I don't care if the project needs an update, due to package changes, till I update my project ressources to fit to the latest package changes or just run a different branch for special purposes. 
The second error message raises because of the `/pkgDir/` usage. 

It looks like the commit 
[commit/978bf8f68](https://github.com/latex3/latex2e/commit/978bf8f6823a6119e84f7dc0c0831f24eb45b8b3) does not fix that. 

I run that in a new installation of TexLive in Win10 and there is no minimum example, as all the rest is ignored after the first lines of code to load my packages - it looks like it just happend during the last weeks, as I work that way since several years.

**Comment by PhelypeOleinik** [comment]
Thanks for the report.  This is partly a duplicate of #422, to which I am working on a fix as we speak.  We expect to make a patch release to fix that issue some time next week, so watch out for that.

Now addressing the different points in your report:

> It should be the same if you load a class or style of a package with
> `\documentclass{./pkgDir/Class} ` or `\documentclass{pkgDir/Class} `

Yes, and so should `\documentclass{./pkgDir/../pkgDir///.././pkgDir/Class}`, but that would lead to a rabbit hole of parsing, far beyond what's considered fun :-)

> `./` should be ignored to raise no warning if you specify the short form in the class or style without `./` .
> 
>     1. LaTeX Warning: You have requested package `./pkgDir/Style', but the package provides `pkgDir/Style'.

So far, LaTeX has treated the entire argument to `\usepackage` as the internal identification for the file, so `./pkgDir/Style` and `pkgDir/Style` are be, as far as LaTeX knows, two different packages (even though they point to the same file).  In fact, it even loads the package one second time if you do
```
\usepackage{./pkgDir/Style}
\usepackage{pkgDir/Style}
```

With the [commit](https://github.com/latex3/latex2e/commit/978bf8f) you mentioned (which fixed #414) I fixed `\input@path` but added the path to the file where it shouldn't have, so now I'm working on something that fixes both #414 and #422, and also a bunch of the problems you mentioned as a consequence. That is already fixed in a local branch for #422 in my machine, to be uploaded shortly. 

> I recognized this whily analyzing the issue related to it, which is not yet fixed:
> 
>     1. `! Package xkeyval Error: xkeyval loaded before \documentclass.`

This is a duplicate of issue #421 which will in part be fixed in the update I mentioned above, but in part will need an update from `xkeyval`.  As a temporary workaround, you can add the fix proposed [here](https://github.com/ho-tex/kvoptions/issues/8#issuecomment-726785624) to your class file.

**Comment by SieDa** [comment]
Many thanks for the feedback. Yes, this works as a workaround. 
```
\makeatletter
\def\input@path{{pkgDir/}}
\makeatother
\documentclass{Class}

%\documentclass{pkgDir/Class}
```

**Comment by PhelypeOleinik** [comment]
@SieDa Hendri fixed the problem with `xkeyval` a few days ago (your document should work fine with that update), and now the issue at the LaTeX end is also sorted, and will be available in a few days with patch release 3.

Regarding

> `./` should be ignored to raise no warning if you specify the short form in the class or style without `./` .
> 
>     1. LaTeX Warning: You have requested package `./pkgDir/Style', but the package provides `pkgDir/Style'.

This behaviour was retained on purpose, because using paths in `\usepackage` and `\documentclass` is, even though supported, not officially the right thing to do, so the “You have requested” warning is there to highlight that you are using a nonstandard path.

The right way to fix this is to move the class to the top-level folder or to your local texmf tree.
