### ISSUE TITLE
LaTeX2e <2020-10-01> breaks dinbrief with wallpaper

### ISSUE THREAD

**Issue by andram** [latex3/latex2e#468]
## Brief outline of the bug

Since I upgraded to LaTeX2e <2020-10-01> I cannot compile documents with document class dinbrief and the wallpaper package. 

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{dinbrief}
\usepackage{wallpaper}

\begin{document}
test
\end{document}
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/5788142/test.log)

!! Use drag-and-drop  (remember: .log file is required) !!

**Comment by u-fischer** [comment]
As the latexbug error in your log file tells you, you are using the third-party files dinbrief.cls, dinbrief.cfg and wallpaper.sty and you should contact their authors. 

dinbrief redefines `\document` and `\enddocument` in a way that is not compatible with a current latex: It removes all code that should be executed at the begin of the document.

**Comment by FrankMittelbach** [comment]
> dinbrief redefines `\document` and `\enddocument` in a way that is not compatible with a current latex: It removes all code that should be executed at the begin of the document.

We have contacted the maintainers of dinbrief months before the LaTeX release and when nothing happened we put in a minimal first aid into LaTeX so that dinbrief doesn't break for all documents, but that class needs to  correct the redef of `\document` and `\enddocument` to  work properly in more complicated situations (e.g. with color). We can't do that for the maintainers of that class so you have to lean on them for an update.
