### ISSUE TITLE
\label inside/outside of \caption{..} produdes addition vertical shift

### ISSUE THREAD

**Issue by hvoss49** [latex3/latex2e#469]
## Brief outline of the bug
I have two lines of two minipages side by side in a figure environment. The first one has an own \label
_inside_ the \caption{} and the second minipage has a caption too, but no \label.  For this case the output is fine (see image)

The next two minipages are nearly the same, except that the \label of the
minipages's \caption is placed _outside_ of it. As can be seen the output shows a small
vertical space for these minipages.

This happens for TL versions since 2015 (my oldest version)

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
  % Any preamble code goes here
\listfiles
\usepackage[demo]{graphicx}
\begin{document}
	
	\begin{figure}
		\centering
		\begin{minipage}[b]{0.3\linewidth}
			\includegraphics[width=\linewidth]{crow_4.png}
			\caption{Corvid and C.\label{fig:subcrow2}}
		\end{minipage}
	    \begin{minipage}[b]{0.3\linewidth}
	    	\includegraphics [width=\linewidth]{crow_5.jpg}
	    	\caption{Corvid and E.}
	    \end{minipage}
		\caption{Corvids being corvids.}\label{fig:subcrow3}
	\end{figure}

	\begin{figure}
		\centering
		\begin{minipage}[b]{0.3\linewidth}
			\includegraphics[width=\linewidth]{crow_4.png}
			\caption{Corvid and C.}\label{fig:subcrow2a}
		\end{minipage}
	    \begin{minipage}[b]{0.3\linewidth}
	    	\includegraphics [width=\linewidth]{crow_5.jpg}
	    	\caption{Corvid and E.}
	    \end{minipage}
		\caption{Corvids being corvids.}\label{fig:subcrow3a}
	\end{figure}

foo\vfill

\end{document}
 ```

## Log file (required) and possibly PDF file  

[Eine_Testdatei.log](https://github.com/latex3/latex2e/files/5791657/Eine_Testdatei.log)
![Bildschirmfoto 2021-01-09 um 20 16 58](https://user-images.githubusercontent.com/12891199/104106743-b854f380-52b7-11eb-8fd1-71ab980fa34e.png)

**Comment by davidcarlisle** [comment]
Yes this is a known feature unfortunately, there are several places where `\label` can affect spacing.

You see essentially the same issue with a `[t]` top aligned minipage if you use `\color` at the start. In that case the top edge of the box would align rather than the first baseline of text.

Here the `[b]` alignment is aligning on the `\write` node from the `\label` rather than aligning on the last baseline in the caption.

This is fundamentally the behaviour provided at the primitive tex level and the workaround of ensuring that invisible nodes are added in horizontal not vertical mode is in many cases the only thing to suggest. In this case that can be achieved by placing the label in the caption, as you note.

**Comment by FrankMittelbach** [comment]
> This is fundamentally the behaviour provided at the primitive tex level and the workaround of ensuring that invisible nodes are added in horizontal not vertical mode is in many cases the only thing to suggest. In this case that can be achieved by placing the label in the caption, as you note.

and which is why Lamport actually states in the manual that `\label` can go into the argument of caption and section and the like (though he doesn't explicitly says when that is necessary or why). 

To fix that generally would either require that `\label` can't be put into arbitrary places by being a command on its own but instead a key or argumement to headings or captions etc or by delaying its action to the next save place (as experimentally done in xgalley). Neither can realistically done in LaTeX2e without changing the syntax and/or breaking  many documents, so bottom line for current LaTeX this is "works as designed".

**Comment by car222222** [comment]
I guess this is what the 'long-term' label refers to??

We are working on providing such better ways to specify the logical-label without using the old, explicit, `\label` commands.  This needs only a mild enhancement to allow (not mandate) the new usage (in future documents only), so it could come fairly soon with no compatibility problems.
