### ISSUE TITLE
alltt doesn't treat some italicized characters properly

### ISSUE THREAD

**Issue by gsrohde** [latex3/latex2e#483]
## Brief outline of the bug

If one uses `\textit` to italicize the dollar-sign symbol ($) within the `alltt` environment, the result displays it as a pound sterling symbol (£).

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\usepackage{alltt}

\begin{document}

\textbf{Inside the alltt environment:}
\begin{alltt}
  The dollar sign in slant font: \textsl{$}
  The dollar sign in italic font: \textit{$}
\end{alltt}

\textbf{Outside of the alltt environment:}

  The dollar sign in slant font: \textsl{\$}

  The dollar sign in italic font: \textit{\$}

\end{document}

```

## Log file (required) and possibly PDF file  

[alltt_bug.log](https://github.com/latex3/latex2e/files/5875787/alltt_bug.log)
[alltt_bug.pdf](https://github.com/latex3/latex2e/files/5875788/alltt_bug.pdf)

**Comment by u-fischer** [comment]
That is one of the problems of the OT1 encoding: it has so few glyph slots that some are used for different chars. 
Use 

    \usepackage[T1]{fontenc}

**Comment by FrankMittelbach** [comment]
As Ulrike said this is a limitation of the original CM fonts: in their 7-bit encoding dollar and pounds share a single slot (pounds being in the it font and dollar in the upright/sl font). So it works as designed by Knuth unfortunately. The old encodings are still the default in LaTeX for a number of reasons but best is to always use T1 instead in new documents.

`\$` and `\pounds` work because they are commands and do some clever extra tests and then change fonts which stops being possible if you use just the character slot by using `$`. So
```
\begin{alltt}
  The dollar sign in slant font: \textsl{\$}
  The dollar sign in italic font: \textit{\$}
\end{alltt}
```
would also work for you, but if that's not an option you need to use a sensible 8-bit encoding i.e. T1.

@JohannesBraams it might be worth adding a note to the package documentation but other than that, it is as it is, sorry.
