### ISSUE TITLE
doc: clarify that \include and \includeonly now strip the .tex extension

### ISSUE THREAD

**Issue by stone-zeng** [latex3/latex2e#486]
In LaTeX 2020-10-01 release, `\include` and `\includeonly` will strip the `.tex` extension, but it was not mentioned in the ltnews. Please consider to clarify it.

Related:

- <https://tex.stackexchange.com/q/319506/>
- CTeX-org/lshort-zh-cn#58

**Comment by PhelypeOleinik** [comment]
The syntax has always been `\include{<filename without extension>}`, so dropping the `.tex` is just an enforcement of that (although I admit that dropping the extension _always_ was an oversight when I wrote that code, that's why it was not documented).  Though I'm not sure if it needs fixing...

But if Google Translate and I understood the linked issue correctly, both `\include{fileb.tex}` and `\include{path/fileb.tex}` work, and without the `.tex` extension they work as well, provided the files are there, so I don't understand what is the problem.

**Comment by stone-zeng** [comment]
> The syntax has *always* been `\include{<filename without extension>}`

So the problem is actually we mistakenly add the `.tex` file extension in `lshort-zh-cn` and someone noticed that... And when I try it I find it can run now, so is this issue.

**Comment by FrankMittelbach** [comment]
Correct. `\include{<file>}` is documented in Lamport as `<file>` being a file without its extension and that the content is then in `<file>.tex` and the extra info in `<file>.aux`and in the past it was really the case that trying the incorrect usage `\include{foo.tex} would result in the attempt to open `foo.tex.tex`.  With the recent change that got normalized  (by lucky chance if you like) and now include behaves like `\input` and strips off a `.tex`if there was one by mistake.
Could/should have been mentioned in ltnews but  we overlooked it as it is nothing people do normally. So we'll mention it in the next one.
