### ISSUE TITLE
\textasteriskcentered and "with microtype

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#525]
With pdflatex-dev (TL21) pretest, following gets the error:

**Comment by kberry** [comment]
Let's try again, stupid github interface. With pdflatex-dev (TL21) pretest, following gets errors as shown:
```
\documentclass{article}
\usepackage{microtype}
\begin{document}
\begin{itemize}
  \item For
\end{itemize}
\end{document}
```

resulting in:
```
Package microtype Warning: Unknown slot number of character
(microtype)                `\textasteriskcentered '
(microtype)                in font encoding `TS1' in protrusion list
(microtype)                `cmr-textcomp'.

! Extra else.
... more errors omitted ...
```

Has to be an \item (or maybe just indented?) or something. It works with TL21 pdflatex (not -dev), hence I surmise it is your issue rather than Robert's. He did just make a release of microtype recently, though. FWIW ...

**Comment by FrankMittelbach** [comment]
Thanks, already addressed with Robert (the Problem was actually there before, the LaTeX adjustment only highlighted it).
Should be gone with his update (or the next).
Until resolved one can add (but that fails with the stix2 fonts as they miss this basic character)
```
\DeclareTextSymbol \textasteriskcentered{TS1}{42}
```

**Comment by FrankMittelbach** [comment]
please close this when it works in pretest - thanks

**Comment by kberry** [comment]
Ok I hope Robert is preparing another version. TL has the current release of microtype, which causes the error.

It seems strange to me that the presence or absence of a character that is not even being used (at least I don't think it is) causes an error. Whatever ...

**Comment by FrankMittelbach** [comment]
The technical reason is that in the past the LaTeX definition was simply to select the character in TS1 (under the assumption that any TS1 implementation has it). As that turned out to be wrong for an important font family we changed it to check with \iffontchar what the situation is and that breaks microtype as it is not careful enough when expanding the command.  As \textasteriskcentered is a very common character (used in footnote symbols) the issue now shows (more often), but it was there before and it would have failed similarly for other characters. Robert already send me a fix so I'll expect an update will happen soon.

**Comment by schlcht** [comment]
The new version is now in TL, so this should be fixed.

**Comment by kberry** [comment]
confirmed, thanks.
