### ISSUE TITLE
Example of  "Using boxes efficiently" fails to compile

### ISSUE THREAD

**Issue by erwannr** [latex3/latex2e#535]
## Brief outline of the bug

In section 33.12 of [the manual](https://ctan.math.illinois.edu/macros/latex/contrib/l3kernel/interface3.pdf), "Using boxes efficiently", the first example fails to compile.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{xparse}

\begin{document}

\ExplSyntaxOn
\hbox_set:Nn \l_tmpa_box { A }
\group_begin:
  \hbox_set:Nn \l_tmpa_box { B }
   \group_begin:
     \box_use_drop:N \l_tmpa_box
   \group_end:
  \box_show:N \l_tmpa_box % ERROR: OK.
\group_end:
%\box_show:N \l_tmpa_box
\ExplSyntaxOff

\end{document}
```

## Log file (required) and possibly PDF file  
[LaTeX-142.log](https://github.com/latex3/latex2e/files/6174031/LaTeX-142.log)

**Comment by FrankMittelbach** [comment]
Sorry not sure what you mean by fails to compile. It compiles for me and your log file seems to indicate it compiled for you (give or take that you put a `%` in front of the second `\box_show:N`)

TeX's `\showbox` or `\box_show:N` stops with an error prompt so that you can inspect the result, that is the standard behavior if that is what you mean by "not compiling" you need to press `<return>` to continue after that.

So unless I'm missing something obvious this is all correct behavior.

**Comment by erwannr** [comment]
OK.
