### ISSUE TITLE
Coloring does no longer work properly

### ISSUE THREAD

**Issue by marmotghost** [latex3/latex2e#559]
I am encountering many issues with the new kernel. Obviously I cannot upload long documents. Here is a document of which I believe that it did work not so long ago.
```
\documentclass{article}
\usepackage{xcolor}
\usepackage{lipsum}
\begin{document}
~\vspace{8em}\par
\lipsum[1-3]
abc\footnote{\textcolor{orange}{\lipsum[4-6]}}
\lipsum[7-8]
\end{document}
```
On page 2 the footnote loses its color.
![ani](https://user-images.githubusercontent.com/68924170/116955153-986e8480-ac46-11eb-8bff-bbed88ffd02a.gif)
I am using a TeXLive 2021 installation which I just updated. I compiled with `pdflatex`, `lualatex` and `xelatex` and always got the same issue. 

P.S. I do have an extensive collection of lecture notes and other documents. Many of them have major issues after the recent updates. Sometimes the issues result in error messages, or like here just in an inconsistent output that differs from what it used to be. In the second case it is sometimes not me who spots the issue but a reader, which is particularly frustrating because I did check the notes carefully some years back, and all I did was to compile again in good faith. However, cooking these document down to simple examples like the one above would require more time than I have. In particular, the above example is not an explicit example of a document for which I have an old pdf file to compare, it is a truncated version, but I believe that it is at least plausible that the output was different before.

**Comment by PhelypeOleinik** [comment]
Thank you for opening an issue!

I've transferred from latex3/latex3 to latex3/latex2e because this is related to the LaTeX2e kernel, and not to `l3kernel`.  This is however the exact same as issue #1, and it exists for as long as colour exists in LaTeX (I've just tested with TL 2014, which is the oldest version I have available).

What happens is (very roughly) that at the code level the `\textcolor` command introduces a `color push` and `color pop` operation, which are written as specials interpreted directly by the PDF backend (pdfTeX itself, or `dvipdfmx` for XeTeX, or LuaTeX's pdf backend).   The problem when the page break happens is that another `pop` instruction is inserted at the page break, but the `color push` instruction is not reinserted when the footnote resumes, because LaTeX has never had a mechanism to keep track of that.

This is mostly an issue because it is hard to keep track of a colour stack without engine support, but we are working on providing that generically with `l3color`, so this issue may be fixed in a not-so-distant future.  Curently, you can work around the issue by loading `bigfoot`:

```latex
\documentclass{article}
\usepackage{xcolor}
\usepackage{bigfoot}
\usepackage{lipsum}
\begin{document}
~\vspace{8em}\par
\lipsum[1-3]
abc\footnote{\textcolor{orange}{\lipsum[4-6]}}
\lipsum[7-8]
\end{document}
```

**Comment by u-fischer** [comment]
This is an old problem. You can use (with pdflatex and lualatex) the package pdfcolfoot (https://ctan.org/pkg/pdfcolfoot) from Heiko Oberdiek, which was written in 2007 to resolve this. xelatex has now color stacks too, so it will probably be possible to extend the code to support this engine too in the near future. 

The package patches some LaTeX commands, to resolve this directly in latex we will have to do similar changes in the kernel (which we need too to enable tagging of splitted footnotes).

**Comment by josephwright** [comment]
@u-fischer  To fix here for XeTeX we of course need to activate the new colour stacks: I guess a question of if/when we want to do that.
