### ISSUE TITLE
`\DiscardShipoutBox` doesn't discard shipout code set with `\AddToHookNext` 

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#565]
## Brief outline of the bug

No quite sure if it is a bug, but in following example all the shipout code set with `\AddToHookNext` stays and is then added at the last page.

In the real world example this affects the pagesel package which used `\DiscardShipoutBox` together with pdfpages which includes graphics with the shipout hooks. All images pills then up in one page. 

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\begin{document}
Page 1
\AddToHookNext {shipout/before} {\DiscardShipoutBox}

\newpage 
Page 2
\AddToHookNext{shipout/before} {\DiscardShipoutBox}
\AddToHookNext{shipout/background}{\put(3cm,-4cm){\Large Page 2 ???????}}
\AddToHookNext{shipout/foreground}{\put(3cm,-6cm){\Large Foreground Page 2 ???????}}

\newpage 
\AddToHookNext {shipout/background}{\put(3cm,-5cm){\Large Page 3 ??????}}
\AddToHookNext {shipout/before} {\DiscardShipoutBox}

Page 3

\newpage 

Page 4
\end{document}
```

![image](https://user-images.githubusercontent.com/4047173/118673649-773a9600-b7f9-11eb-8b41-4f655134ba25.png)

## Log file (required) and possibly PDF file  

[test-nomgt.log](https://github.com/latex3/latex2e/files/6502210/test-nomgt.log)

**Comment by FrankMittelbach** [comment]
I would say this is by design.  `\AddToHookNext` adds code to the *next* use of the hook and neither foreground nor background have been used before in your example.

Also the user may add something to the foreground for the next page (as what he thinks is the next page) and that internally some code peaks at the the shupout box then does something with it and discards the shipout is not at all visible on the document level.

On the other hand we may want to offer the possibility to cancel code added to next invocation of a hook. But there is only all or nothing as the *next* code is mainly for shortterm/document usage and so is not structured --- I think that was the reason why we decided initially not to offer that. But it would be trivial:
```
\ExplSyntaxOn
\cs_new_eq:NN\ClearHookNext\__hook_clear_next:n
\ExplSyntaxOff
```
Then your example could go with
```
\AddToHookNext {shipout/before} {\DiscardShipoutBox
  \ClearHookNext{shipout/background}%
  \ClearHookNext{shipout/foreground}%
}
```

**Comment by FrankMittelbach** [comment]
My point is that should probably not make an exception from the general rule that the code stays until used, i.e., not cancel it ourselves inside `\DiscardShipoutBox`. But we could as I said offer the mechanism for cancelation. Needs a decision for the command name though.

**Comment by u-fischer** [comment]
Yes, I  agree, someone using `\DiscardShipoutBox` should take care of this details too. Imho `\ClearHookNext`  sound good, or perhaps `\DiscardHookNext`.  `\RemoveFromHookNext` wouldn't fit so well as there is no label.

**Comment by FrankMittelbach** [comment]
Looking over the documentation I think `\ClearHookNext` is fine, fitting with `\ClearHookRule`.  As you say `RemoveFromHookNext` doesn't quite work as there is not partial structure you could remove, so "clear" is clearer :-)
On the `expl3` side that would then be `hook_gclear_code:n` I would say. At least that is my proposal.

**Comment by FrankMittelbach** [comment]
Having pondered over the possible names I now again leaning towards `\DiscardHookNext` as the only real use cases  can think of are cases going with `\DiscardShipoutBox`.

**Comment by FrankMittelbach** [comment]
decided in the end to stay with \ClearHookNext
