### ISSUE TITLE
Regression between longtable 4.13 and 4.16 when combined with ltxtable

### ISSUE THREAD

**Issue by pkl97** [latex3/latex2e#585]
## Brief outline of the bug

The document below shows different column widths with longtable 4.13 and 4.16 as the attached PDFs demonstrate.
The issue occurred after updating the tools package in TeXLive 2021 from version 56514 to 59424. Simply reverting longtable.sty makes the problem go away, so I assume this package is the trigger.

When using longtable 4.16 this warning message is generated:
> Overfull \hbox (369.0pt too wide) in alignment at lines 1--3

No such warning happens with longtable 4.13.

Sorry, the sample file still uses ltxtable. This package however was not changed in the TeXLive upgrade, so I see no connection to the problem (at least no obvious one).

## Minimal example showing the bug

```latex
\documentclass{article}
\usepackage{ltxtable}
\usepackage{environ}

\newwrite\filehandle
\NewDocumentEnvironment{mytable}{ m }%
{%
  \immediate\openout\filehandle=\jobname-ltxtable.tmp
  \immediate\write\filehandle{\unexpanded{\begin{longtable}{#1}}}%
  \Environlongtablex%
}%
{\endEnvironlongtablex}
\NewEnviron{Environlongtablex}
{%
  \immediate\write\filehandle{\unexpanded\expandafter{\BODY}}%
  \immediate\write\filehandle{\unexpanded{\end{longtable}}}%
  \immediate\closeout\filehandle%
}%
\AfterEndEnvironment{mytable}{\LTXtable{\textwidth}{\jobname-ltxtable.tmp}}

\begin{document}
\begin{mytable}{XX}
  Column1        & Column2
\end{mytable}
\end{document}
```

## Log file (required) and possibly PDF file  
[document-longtable4.13.pdf](https://github.com/latex3/latex2e/files/6642759/document-longtable4.13.pdf)
[document-longtable4.16.pdf](https://github.com/latex3/latex2e/files/6642760/document-longtable4.16.pdf)
[document-longtable4.13.log](https://github.com/latex3/latex2e/files/6642762/document-longtable4.13.log)
[document-longtable4.16.log](https://github.com/latex3/latex2e/files/6642763/document-longtable4.16.log)

**Comment by davidcarlisle** [comment]
Thanks I can reproduce so I'll have a look.

**Comment by davidcarlisle** [comment]
To avoid clashing with other code longtable (finally) allocated its own global box register rather than using the scratch register `\box1` and hoping no other package also globally use that same register.

But this breaks extension packages expecting to find `longtable `data in box 1.  (`tabu`'s `longtable` got  bitten by this as well)
I'll update `ltxtable `to use `\LT@gbox` instead of `\box1` (the code has had no update since 1995 so it's probably about due for a release:-)  

The easiest quick fix is to make `\LT@gbox` be the same as `\box1`  which then risks the clashes the change was trying to avoid but since it was that way for 25 years previously it is probably safe enough as a temporary patch until a `ltxtabl` update.

Alternatively you could test the updat eI would make, in a local copy of `ltxtable.sty` change the three `\@ne` on lines 55 and 56 to `\LT@gbox`  so it looks like

```
\global\setbox\LT@gbox\hbox{\unhbox\LT@gbox}%
  \kern\wd\LT@gbox
```

 But I'll get an updated ltctabl to CTAN this weekend, thanks for the report,

```

\makeatletter
\chardef\LT@gbox 1
\makeatother
```

In your preamble after loading ` ltxtable` would work.

**Comment by pkl97** [comment]
Thanks a lot @davidcarlisle!

Both suggestions work fine. I'll go with the changed ltxtable.sty file and then replace it with the updated package once it is available in TeXLive.

**Comment by davidcarlisle** [comment]
@FrankMittelbach  formally I think this PR can be closed the fix does not  need to be in tools but in my dpctex github

**Comment by davidcarlisle** [comment]
@pkl97  it's been uploaded to ctan, should arrive in the distributions in a few days.
