### ISSUE TITLE
\AddToHookNext* to add code executed before normal code instead of after

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex2e#599]
## Brief outline of the enhancement

According to the documentation of `\AddToHookNext`,

"
The code is executed after the normal hook code has finished
"

the requested enhancement is a starred version for which the code is executed before the normal hook code.

## Minimal example showing the desired new behaviour

The purpose is to run initialization code only on the first invocation.
It is actually possible in very simple situations, but a bit verbose and limited.
```latex
\documentclass{article}
\NewHook{A}
\AddToHook{A}[setup]{setup }
\AddToHook{A}{A}
\AddToHookNext{A}{\RemoveFromHook{A}[setup]}
\begin{document}
\UseHook{A}
\UseHook{A}
\end{document}
```
It should be replaced by
```latex
\documentclass{article}
\NewHook{A}
\AddToHookNext*{A}{setup }
\AddToHook{A}{A}
\begin{document}
\UseHook{A}
\UseHook{A}
\end{document}
```
The problem with the first approach is that the setup code must absolutely come first.
This is only possible if a priori you have a known limited choice of `<label>`'s.

**Comment by FrankMittelbach** [comment]
Thanks for the suggestion. We have decided not to offer this for a number of reasons. First, there is no "must come first", because even with your suggestion what happens if 2 packages want to come _absoletely first_? Second ,the number of _real_ use cases for this is rather limited if even if some may exist, so our current position is that the available possiblility are sufficient. If the practical use of hooks in the future  indicates otherwise, we can still revisit this.
