### ISSUE TITLE
! File ended while scanning use of <.

### ISSUE THREAD

**Issue by aminophen** [latex3/latex2e#603]
## Brief outline of the bug

With LaTeX2e 2020/10/01 or later, making `<` active before `\begin{document}` causes an error

```
Runaway argument?
\__int_eval:w 20201111\__int_eval_end: \__prg_TF_true:w \fi: \use_ii:nn \ETC.
! File ended while scanning use of <.
<inserted text> 
                \par 
l.11 \begin{document}
                     ^^M
?
```

When rolling back to 2020/09/30 or earlier, the error goes but `latexbug.sty` reports

```
! Package latexbug Error: Third-party file(s)
(latexbug)                This test file uses third-party file(s)
(latexbug)                ==============
(latexbug)                expl3.ltx
(latexbug)                ==============
```

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}

% current: NG: Runaway argument
%\RequirePackage[2020/10/01]{latexrelease}% NG: Runaway argument
%\RequirePackage[2020/09/30]{latexrelease}% OK, but expl3.ltx is said external
\documentclass[dvipdfmx]{article}

\catcode`\<=13
\def<#1>{===#1===}

\begin{document}
a
\end{document}
```

## Log file (required) and possibly PDF file  

* [l3active.log](https://github.com/latex3/latex2e/files/6721529/l3active.log)

----

We used to make `<` active for [ptex-manual.tex](https://github.com/texjporg/ptex-manual) to easily formatting the syntax, which was OK before but does not work any more.  Of course we can change the syntax in ours, but...

**Comment by FrankMittelbach** [comment]
How about
```
\begingroup
\catcode`\<=13
\gdef<#1>{===#1===}
\endgroup
\AtBeginDocument{\catcode`\<=13 }
```
for now?

**Comment by aminophen** [comment]
I did that already ;-)  Just wanted to note that there might be other breakage

**Comment by FrankMittelbach** [comment]
> I did that already ;-) Just wanted to note that there might be other breakage

because? 

I mean activating core symbols that are used by TeX in its syntax is always a rather dangerous  business and other than .fd files LaTex never guarded agains catcode changes, so if you load code after the catcode got changed you are likely breaking it (which is what happens here). In some sense (even though done by a number of babel packages and others) changing catcodes it not really a supported  method. I see the beauty of doing so :-) but ...

Long term there needs to be a better solution then it is now but it isn't simply solved by forcing the catcode back to 12 during code loading. After all, that might upset scanners that then scan for catcode12 symbols but find catcode 13 in the document, etc. So it is a difficult problem to solve generally and at the moment I think the answer is changing catcode means you have to deal with the consequences and they may change over time.

**Comment by aminophen** [comment]
> other than .fd files LaTex never guarded agains catcode changes,

I thought babel did lots of catcode changes, but the policy is clear now.

> at the moment I think the answer is changing catcode means you have to deal with the consequences and they may change over time.

I see. Thanks for the help.

**Comment by aminophen** [comment]
> other than .fd files LaTex never guarded agains catcode changes,

I thought babel did lots of catcode changes, but the policy is clear now.

> at the moment I think the answer is changing catcode means you have to deal with the consequences and they may change over time.

I see. Thanks for the help.

**Comment by u-fischer** [comment]
> I thought babel did lots of catcode changes, but the policy is clear now

babel delays all catcode changes until begindocument, exactly for this reason. This doesn't avoid all problems, but at least the type of problem you had here.

**Comment by FrankMittelbach** [comment]
> > other than .fd files LaTex never guarded agains catcode changes,
> 
> I thought babel did lots of catcode changes, but the policy is clear now.

yes it does/did, but that have been all mainly local/national styles that evolved and it was and is always a dangerous approach with no clear guidance how to handle that best. Babel has some code that tries to render such catcode changes harmless but it isn't extremely successful in that space. So bottom line it is all rather fragile, hence my advice/comment.
