### ISSUE TITLE
\UseOneTimeHook should properly clean up after itself so it becomes a noop on further calls

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex2e#606]
## Brief outline of the enhancement

Correct me if I am wrong. Whereas normal hooks are used to execute some code *on request*, one time hooks are used to execute code *after some point*. This is why `\UseOneTimeHook` is intended to be used "only once".

Then if `\UseOneTimeHook` should be used only once, any further call should either be a simple no op or raise an error to help package and class connectors in writing better code (\UseHook should be limited also). At least the documentation could mark this usage as *undefined* or *unsupported*.

If this is considered as a feature, this should be explicitly documented.

## Minimal example showing the current behaviour

```latex
\documentclass{article}
\NewHook{A}
\AddToHook{A}{1}
\begin{document}
\UseOneTimeHook{A}
\UseOneTimeHook{A}
\AddToHook{A}{2}
\UseOneTimeHook{A}
\UseHook{A}
\end{document}
```
Output is  1 1 2 1 1

**Comment by FrankMittelbach** [comment]
> ## Brief outline of the enhancement
> 
> Correct me if I am wrong. Whereas normal hooks are used to execute some code _on request_, one time hooks are used to execute code _after some point_. This is why `\UseOneTimeHook` is intended to be used "only once".

I think you misunderstand the original intention. The reason for a one-time hook was not that its code is executed _after some point_ but rather that it is a hook that is only being called once. The main use case for allowing further code pushes to be executed immediately was to support something like `begindocument` where it often happens that it receives code which in turn contains `\AtBeginDocument` because it is code that could have been called earlier.

As a side effect, you get the behavior that code added to it will execute at or after so your description is accurate.

Also accurate is that because of this, the current behavior of `\UseOneTimeHook` is not optimal. It is okay for the originally envisioned use case (ie that it _is_ only executed once, because the calling command, eg `\document` is only called once) but the fact that it doesn't clean up after it means that some interesting other use cases are not possible.

I.e.,  use `\UseOneTimeHook` in a command that can be called several times in the document. That would allow the hook to work as an initialization hook which is used the first time it is called and then afterwards does nothing on repeated calls.

So we classify this as an enhancement that improves the usability and will update the code to clean up after first usage and update the documentation to better describe the use cases.

Mixing `\UseHook`and use `\OneTimeHook` for the same hook name is mainly unsupported behavior I would say, even though with the cleanup you could even argue that could have some very specialized use cases.

**Comment by FrankMittelbach** [comment]
@PhelypeOleinik clearing the onetime hook after first use is going to be addressed as part of your other changes, right? The documentation updates have already happened in #638.

**Comment by PhelypeOleinik** [comment]
@FrankMittelbach Yes, I'll tackle this in a bit

**Comment by car222222** [comment]
I shall hold off reviewing/correcting these documentation updates until this work is nearer completion.

**Comment by FrankMittelbach** [comment]
@car222222 makes sense I guess. wait until the various branches are merged together into develop.
