### ISSUE TITLE
\AddToHookNext should run the code immediately once the hook is consumed

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex2e#607]
## Brief outline of the bug

Given a declared one time hook, the `<code>` provided to `\AddToHook` is always executed.
The `<code>` provided to `\AddToHookNext` may be executed or silently gobbled, depending on the moment the hook is consumed. But this moment is unknown in advance for sure.

`\AddToHookNext` should behave exactly like `\AddToHook` on that respect.

## Minimal example showing the bug

```latex
\documentclass{article}
\begin{document}
\NewHook{A}
\AddToHook{A}{1}
\AddToHookNext{A}{2}
\UseOneTimeHook{A}
\AddToHook{A}{3}
\AddToHookNext{A}{4}
\end{document}
```
The output is 123, it should be 1234

## Log file (required) and possibly PDF file  
[sansnom-17-copie.log](https://github.com/latex3/latex2e/files/6727181/sansnom-17-copie.log)

**Comment by FrankMittelbach** [comment]
This works as designed, but I agree it could be better explained.  By making "Next" always mean next invocation it will not be used on one-time hooks if it is placed after they have executed as you observed. 

But  a) you should know if you are before or after such a hook and b) this allows you a choice that you otherwise would not have. If you need your code to run *only* at the point where the one-time hook  executes you can use `\AddToHookNext`, if your code should execute even it it comes too late you use `\AddToHook`.

**Comment by FrankMittelbach** [comment]
Documentation updated in #638 explaining why this is the intended behavior
