### ISSUE TITLE
Make \AddToHookNext compatible with reversed ordering

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex2e#608]
## Brief outline of the bug

For normal hooks, the order of execution is: labeled code < top-level code < Next code
For reversed hooks, the order of execution is: top-level code < labeled code < Next code
It should be: Next code < top-level code < labeled code

If this is "by design" then this big limitation should really be documented (it means we cannot play with TeX grouping)
## Minimal example showing the bug

```latex
\documentclass{article}
\NewMirroredHookPair{A}{B}
\AddToHook{A}[labeled]{labeled/}
\AddToHook{A}[top-level]{top-level/}
\AddToHookNext{A}{next/}
\AddToHook{B}[labeled]{labeled/}
\AddToHook{B}[top-level]{top-level/}
\AddToHookNext{B}{next/}
\begin{document}
\UseHook{A}
\UseHook{B}
\end{document}
```
The output reads A:labeled/top-level/next/ B:top-level/labeled/next/

## Use case example

Actually nesting environments only in next invocation is not possible

```latex
\documentclass{article}
\AddToHook{env/quote/begin}{\begin{bfseries}}
\AddToHook{env/quote/end}{\end{bfseries}}
\begin{document}
\begin{quote}ABC\end{quote}
\AddToHookNext{env/quote/begin}{\begin{itshape}}
\AddToHookNext{env/quote/end}{\end{itshape}}
\begin{quote}DEF\end{quote}
\end{document}
```
DEF is not typeset because LateX environment are not properly nested.

## Log file (required) and possibly PDF file  

[sansnom-17 copie.log](https://github.com/latex3/latex2e/files/6732359/sansnom-17.copie.log)

**Comment by FrankMittelbach** [comment]
It is by design and after some discussion we decided that this is the design we want. You are right that this prohibits using "Next" to add code involving environments or other grouping into paired hooks (if they already contain code with grouping), but on the other hand it allows to adjust whatever is in the hook for a single invocation. 

The latter functionality would be gone if the "Next" coded would be placed first. As "Next" is meant to be for single overwrites and generally on the document-level when you know what is in the hooks, we consider this more important than the ability to use environments in all cases. If that is something you deparately need you can still get it by a somewhat convoluted way of using
```
\AddToHook{foo}[X]{ <code> \RemoveFromHook{foo}[X]}
```

We extend the documentation though to make this clear.
