### ISSUE TITLE
\mathsurround incorrectly reset in array package

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/latex2e#614]
## Brief outline of the bug

`tabular` calls `\m@th` t,o reset `\mathsurround` but it is inside a group so does not affect the outer `$` used for vertical centering.

## Minimal example showing the bug

https://tex.stackexchange.com/q/604536/1090

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\mathsurround=50pt % Exaggerated value to visualize the effect
\usepackage{array}

\begin{document}

Bla bla $x=0$ bla bla.

X\begin{tabular}{|c|}A$x$A\end{tabular}X

\makeatletter
\def\endtabular{\endarray\m@th$\egroup}
\makeatother


X\begin{tabular}{|c|}A$x$A\end{tabular}X


\end{document}
```

**Comment by aminophen** [comment]
Just curious: why not `\def\@tabarray{\m@th\@ifnextchar[{\@@array}{\@@array[c]}}` ?  I think this is more natural because source2e.pdf says "RmS 91/11/04 added `\m@th`."

**Comment by FrankMittelbach** [comment]
@aminophen In practice it probably makes no difference. I had briefly thought about whether I should move the `\m@th` to the start but decided that it is better placed at the end because then I know for sure that the outer `$...$` has definitely no `\mathsurround` even if by some strange code inside the array it has be turned on again. And to be honest I hadn't checked what is in LaTeX for this but only looked at the arrray code. Interesting that Rainer only updated the 2.09 source but not array back then.

**Comment by aminophen** [comment]
I guess `\endtabular` is slightly more often redefined by others (e.g. arydshln.sty, plarray.sty in platex-tools) so updates are needed for those but `\@tabarray` redefinition requires less.
