### ISSUE TITLE
\include in preamble writes \@input{filename.aux} to terminal

### ISSUE THREAD

**Issue by dahosek** [latex3/latex2e#645]
## Brief outline of the bug

Of course a user should not use `\include` in the preamble, but LaTeX does not currently prohibit it. Because the main aux file has not yet been opened for writing, the lines 
```
  \if@filesw
    \immediate\write\@mainaux{\string\@input{#1.aux}}%
  \fi
```
in the definition of `\@include` write their output to the terminal.

Not a serious issue, but perhaps there should  be a guard to check to see if we're in the preamble:
```
\ifx\@nodocument\relax
  \@latex@warning{\protect\include\space should not be used in preamble}%
\else
  \if@filesw
    \immediate\write\@mainaux{\string\@input{#1.aux}}%
  \fi
\fi
```

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\include{foobar}
\begin{document}


\end{document}

```

## Log file (required) and possibly PDF file  
[x.log](https://github.com/latex3/latex2e/files/6970791/x.log)

**Comment by FrankMittelbach** [comment]
Don, users shouldn't use `\chapter` inside a footnote either and there is no check for this either. These kind of "misues" have not been an issue for anybody in the last 40 years  (or if somebody did it, they figured out fast enough I think) and yes there could be guards for all kind of strance inputs but if they are in practice not needed but run reach time, they just add to the overall processing time and that seems pointless.

So do me a favor and make a bit of a sanity check first: if there is not a single query about the behavior in any forum or elsewhere, then we are very very unlikely to add to the processing time of LaTeX (or alter macros unnecessarily because that quite often results in introducing real errors or incomptibilities) and I don't think it helps anybody if you write up issues of a nature that all we will do with them is closing them again. This just clutters this issue tracker and I would appreciate if we can keep it mainly with bugs worth fixing. There is really enough "real" stuff worth fixing so please  let's try to focus on that.

**Comment by car222222** [comment]
@FrankMittelbach wrote (before 'going off message'):

"Don, users shouldn't use \chapter inside a footnote either and there is no check for this either."

Agreed!  
Although we may need sometime soon to introduce some checks similar to these in order to produce valid (WTPDF) output.

But equally: 

“Frank, team members ﻿should not use overbearing and boorish language — nor descend into over-personal or aggressive modes of expression, nor lash out petulantly at individuals or groups concerning either specific  postings or the general nature of their postings.”

Do we agree on both of these?

**Comment by dahosek** [comment]
I've thought about this a bit and I'm thinking that if a command attempts to write to `\@mainaux` before it's opened, it should generate an error. It's not merely the case of `\include` in the preamble, but also classes like elsarticle and revtex which break LaTeX conventions by requiring the author to put titling commands *after* `\begin{document}`. I understand the reluctance to make these sorts of changes, but in this case, it would mean the difference between something silently not working and the user getting feedback about having done something wrong.

And the lack of a check for a chapter in a footnote is perhaps something that should matter. Most likely, it's not intentional, and discovering the error sooner rather than later can help with usability. LaTeX's error messages are often unhelpful, if not misleading and while TeX is happy to promise help if you press `h`, and for the low-level errors it's often helpful, for every single error issued by `\@latex@error`, it says look at Lamport or the LaTeX companion. I would argue that giving good error messages is vital for usability (I've been coding in Rust lately and the compiler error messages there are nothing short of delightful. In most cases, not only is the error correctly identified, but a specific fix is offered). I'm well aware of the limitations of TeX in this regard, but errors are a part of the user experience and anything that helps the user experience of LaTeX is a net plus in my opinion.

**Comment by dahosek** [comment]
A proposed implementation of the above solution:

Move `\newwrite\@mainaux` to the definition of `\document`. In the format, define `\@mainaux` with something like

```
\def\@mainaux{0{}\@latex@error{You've attempted to use a command that must come after \string\begin{document} in the preamble}}
```

**Comment by u-fischer** [comment]
Quite a lot people use `\include` instead of `\input` in the preamble to input some template files. While it is it isn't meant for this it normally doesn't harm and it doesn't matter (or is even good) that the command can't write to aux.  

If we make this an error we would break such documents for no real benefit.

**Comment by dahosek** [comment]
>If we make this an error we would break such documents for no real benefit.

Except of course the mysterious errors that may arise when they use `\includeonly`. As I mentioned above, `\include` is not the only command that writes to `\@mainaux` which, when used in the preamble silently fails and produces unexpected behavior rather than surfacing an error immediately. The benefit of alerting a user who, following good LaTeX process writes:

```
\documentclass{elsarticle}
\title{foo}
\author{bar}
\ead{foo@bar}
\begin{document}
\maketitle
```

and wonders why their email address never prints gains.

**Comment by Skillmon** [comment]
@dahosek actually it is good LaTeX practice to specify `\title`, `\author`, etc. after `\begin{document}` for things like `babel` short hands to correctly work.

**Comment by car222222** [comment]
The questions (that Don picked up from Frank’s examples) around badly structured input need to be discussed elsewhere, and are best situated in the more general context of the many aspects (that we are soon to be tackling) of dealing with structure when processing LaTeX documents.

**Comment by car222222** [comment]
Using \include instead of \input in the preamble seems very strange — I wonder how/where that usage ﻿ever got started.

Its existence means that, if possible at this late stage, it might be good to just define \include to be \input until the end of the preamble.
