### ISSUE TITLE
Arguments to environment hooks in `lthooks` documentation

### ISSUE THREAD

**Issue by gusbrs** [latex3/latex2e#646]
I just noticed a small thing in the documentation of `lthooks`: the environment hooks are missing the `env` argument in current section 2.8 "LaTeX2e commands and environments augmented by hooks".

As far as I can tell, the involved lines are:
https://github.com/latex3/latex2e/blob/1ad34d510d8cde30ae32ad4cc1db04824f72c7f0/base/lthooks.dtx#L1500
https://github.com/latex3/latex2e/blob/1ad34d510d8cde30ae32ad4cc1db04824f72c7f0/base/lthooks.dtx#L1509
https://github.com/latex3/latex2e/blob/1ad34d510d8cde30ae32ad4cc1db04824f72c7f0/base/lthooks.dtx#L1516
https://github.com/latex3/latex2e/blob/1ad34d510d8cde30ae32ad4cc1db04824f72c7f0/base/lthooks.dtx#L1523

**Comment by FrankMittelbach** [comment]
This is because I think they should not be used (or say aren't really needed), so I messed up the documentation :-) -- thanks

**Comment by gusbrs** [comment]
:-)

> This is because I think they should not be used (or say aren't really needed)

Could you elaborate? You got me curious, and I was about to use them for an important task...

(Feel free not to answer, I admit to it being off-topic here).

**Comment by FrankMittelbach** [comment]
well basically, the hook management system is nicely standard, so long term I think it is better to always use

    \AddToHook{env/foo/before}....
    \AddToHook{cmd/...}...
    \AddToHook{begindocument}...

instead of using for a few hooks a special command. They are largely there because they have been in some package that we this way got rid off or in case of "begindocument" because that was more or less the only hook LaTeX had as \AtBeginDocument`. I mean the moment you need to order some chunks coming from different packages in the same hook you need to use `\DeclareHookRule{env/foo/before}...`

But they will stay so no worry there ... only LaTeX will get further hooks over time and none will get special `\At...` declarations. So you can safely use them but I would go for always using `\AddToHook` that's all.

**Comment by gusbrs** [comment]
Ah, I see, you mean these traditional commands are redundant with the standard forms of the new hook management system. Understood!

I'll use `\AddToHook` then out of this concern. I do share your taste for symmetry there.  :-)

And thank you!
