### ISSUE TITLE
Starred versions of \counterwithin & \counterwithout

### ISSUE THREAD

**Issue by dr-scsi** [latex3/latex2e#709]
The macros `\counterwithin`/`\counterwithout` are described in ltnews28 and ltnews34.

https://github.com/latex3/latex2e/blob/d18d208b30fb47cdf8ed697d6b0cee27fd5b6e69/base/doc/ltnews28.tex#L282-L287
https://github.com/latex3/latex2e/blob/d18d208b30fb47cdf8ed697d6b0cee27fd5b6e69/base/doc/ltnews34.tex#L487-L495

Looking at the source, these macros also have starred versions.  It seems they are not mentioned.  Am I missing something or should they be added to ltnews34?

**Comment by FrankMittelbach** [comment]
thanks, fixed in dev

**Comment by dr-scsi** [comment]
Thanks for the quick fix, closing this issue.

**Comment by FrankMittelbach** [comment]
as an FYI: we normally prefer to keep issues open until we have actually pushed (the main release, or at least the -dev release) to CTAN  -- in this particular case it doesn't really matter, but for others usually does.

**Comment by dr-scsi** [comment]
Thanks for the FYI.  Does it mean then mean that bugs are usually closed by the team?  I'm easy with it, just asking 🙂

**Comment by FrankMittelbach** [comment]
yes, it is normally done by us (unless of course, a bug report is taken back as incorrect) but there are not many people who could install LaTeX from the repo, so for them a bug isn't fixed until it hits ctan which is why (beside other reasons) we prefer to keep it open in the 2e repo at least. In other repos we often close earlier.
