### ISSUE TITLE
[tl2021 COSMETIC] `\dospecials` doubly defined

### ISSUE THREAD

**Issue by ilyaza** [latex3/latex2e#725]
## Brief outline of the bug
In `latex.ltx` the definition of `\dospecials` appears twice: on l.119, and l.306.

## Minimal example showing the bug

```
texmf-dist\tex\latex\base>   grep -n "def.*dospecials" latex.ltx
119:\def\dospecials{\do\ \do\\\do\{\do\}\do\$\do\&%
306:\def\dospecials{\do\ \do\\\do\{\do\}\do\$\do\&%
```

or
```
texmf-dist\tex\latex\base>   grep -nC2 "def.*dospecials" latex.ltx
117-\newlinechar`\^^J
118-\def\typeout{\immediate\write17}
119:\def\dospecials{\do\ \do\\\do\{\do\}\do\$\do\&%
120-  \do\#\do\^\do\_\do\%\do\~}
121-\def\@makeother#1{\catcode`#1=12\relax}
--
304-\catcode`\^^L=\active \def^^L{\par}% ascii form-feed is \par
305-\message{catcodes,}
306:\def\dospecials{\do\ \do\\\do\{\do\}\do\$\do\&%
307-  \do\#\do\^\do\_\do\%\do\~}
308-\catcode`@=11
```

**Comment by davidcarlisle** [comment]
Yes this is by design, the first one is part of a set of basic definitions for `ltdirchk` which is loaded very early when building the format, in initex mode when essentially nothing is set up. The line above there is also a duplicated (simplified) definiion of `\typeout` as well. It may be that by now the two definitions are the same and the second one in the main part of the formak from `ltplain` could be omitted but the original design was that all theltdirchk definitions would be overwritten later so they could just be simple definitions enough to work at that stage. As is still the case with `\typeout`.

In fact most of the `ltdirchk` testing is no longer used as all current systems use a unix style  directory path with / separator, no longer have to test for exotic file formats with no directories or no extensions etc.

**Comment by FrankMittelbach** [comment]
It looks a bit odd in latex.ltx though. So perhaps it is worth adding  `%%` line in ltdircheck that all definitions from here to there are going to replaced later

**Comment by ilyaza** [comment]
Actually, when reporting this, I double-checked with `source2e.pdf` — but did not find anything relevant close enough to these definitions…

Moreover, “intended to be overwritten” is fine — but even so: one is not ***forced*** to overwrite it by an identical definition, right?

**Comment by FrankMittelbach** [comment]
Am 11.12.21 um 12:46 schrieb ilyaza:
> Moreover, “intended to be overwritten” is fine — but even so: one is not 
> /*forced*/ to overwrite it by an identical definition, right?

no, but it is helpful to have the definition  listed in the right place 
and that is the later one. But, of course, it could be done there as a 
verbatim as long as it is identical.

**Comment by ilyaza** [comment]
I do not know what to do: I would close it, but then Frank’s suggestion in the third message may be lost…

**Comment by FrankMittelbach** [comment]
just leave, I'll guess I'll add 2 such lines so that things are a bit clearer in latex.ltx but I'll keep the definitions later because those are the real places (that should be changed if changes are needed). And it is not just this one but many others that are handled in the same way.
