### ISSUE TITLE
lthooks-doc: List syntaxes of every command 

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#738]
## Brief outline of the enhancement

**LaTeX2e generally cannot add new features without an extreme amount of care to accommodate backwards compatibility. Please do not be offended if your request is closed for being infeasible.**

Currently the syntaxes of some commands in `lthooks-doc` is not listed explicitly, probably due to similarities to the syntaxes of listed ones in the same group. For example, `\ShowHook` and `\LogHook` are introduced in a whole, but only `\ShowHook{<hook>}` is listed.
https://github.com/latex3/latex2e/blob/42a8fa1872e68a53b9551031292c6f633a524d4f/base/lthooks.dtx#L783-L786

This might cause misunderstanding and already caused one in TeXstudio's completion file, see https://github.com/texstudio-org/texstudio/pull/2041.

Therefore I suggest to complete the command syntaxes. Actually I've prepared a commit https://github.com/muzimuzhi/latex2e/commit/bb6ab531dd2071f6dd08d191d36a4a73f12006c6.

**Comment by FrankMittelbach** [comment]
I always consider that syntax section as only given an example, we nearly never show all possible variants or all commands, e.g., if there is `\ShowHook` and `\LogHook` marked in the margin and one example for the syntax is given then it seems to me that it is obvious both have the same. Thus if you are serious on this one then I fear there are many other places that only list one command in the syntax but several in the margin. But I have no strong feelings either way and since you prepared a change, I'm happy to accept a pull request.

One organizational point though: by convention we do change version numbers of files only when code changes --- if there are only documentation changes we only change the doc date.

**Comment by muzimuzhi** [comment]
> Thus if you are serious on this one then I fear there are many other places that only list one command in the syntax but several in the margin.

true. After a second look, I decide to only add entries for `\LogHook` (the only one I want to have) and `\hook_log:n` (just for consistency).
