### ISSUE TITLE
`\label` taken into account only at the end of `figure` and `table` environments?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#770]
I am grading exams following a LaTeX course I just gave to second and third year university students. Although I have insisted on placing `label` after `caption` in the `figure` and `table` environments, I find that this warning is often forgotten and that it therefore leads to incorrect cross-references.

Hence my query: would it be possible that, within a `figure` or `table` environment, the `\label` command is taken into account only at the end of that environment? I am aware that this can cause problems in case of e.g. `subfigure` environments inside a `figure` environment, but just in case, I start the discussion :smile:

**Comment by FrankMittelbach** [comment]
@dbitouze Denis, while this is tempting and an understandable wish, it is not possible and violates offical documentation (I think even in Lamports book) and rather typical usage.

 - it is possible and allowed to have more than one caption in a figure  or table environment. Thus moving the label to the very end would then be invalid
 - label is scoped, so if somebody puts any grouping around the caption (for whatever reason) and the label would end up outside of that it would be also getting the wrong value
 - it would not even be possible to delay a label until after one has seen the very first caption, because again you could have one label deliberately before the caption (to be able to mark the current section unit where the figure ends up) and a second after the caption to refer to its number.

There are packages that formalize the interface and have the label as part of the float, which is a better design, but the 2e way of doing it can't be altered without breaking *a lot* of documents.

**Comment by blefloch** [comment]
Maybe it makes sense to warn by default if the label is used before the caption?

**Comment by FrankMittelbach** [comment]
It would give a good number of bogus warnings eg. for a figure env with two minipages inside and in there 2 captions, which doesn't make things better. Handling that properly is next to impossible to do correct for all case given the flexibility of the interface as designed. Besides we know that people ignore even relevant warnings typically and you can't stop with an error.

**Comment by u-fischer** [comment]
And you can actually have valid use cases for labels before the caption, e.g.  if you want to do `\phantomsection\label{figpageref:myfig}`  for a good pageref which jumps to a specific place in the figure.
