### ISSUE TITLE
babel: Font feature not working inside hbox if using "bidi=basic-r"

### ISSUE THREAD

**Issue by seloumi** [latex3/latex2e#8]
## Brief outline of the bug

Writing arabic document with babel I'm facing issue in inserting arabic text inside hbox, letters "كـ"  and "م" appear not connected

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage[nil, bidi=basic-r]{babel}
\babelprovide[import=ar, main]{arabic}
\babelfont{rm}{Amiri} %   arabic font
\begin{document}

 
\Huge  

% outside hbox
عليكم  منكم  إليكم 

% within hbox
\hbox {عليكم \quad منكم \quad إليكم}

\end{document}
```

## Log file (required) and possibly PDF file  

[test4.log](https://github.com/latex3/latex2e/files/1629094/test4.log)

**Comment by jbezos** [comment]
I'm not sure, but I think it's the same bug in the lua font loader I reported a few weeks ago to the ConTeXt maintainers (some internal kerns added by luaotfload are misplaced). It's not directly related to babel, and I've reproduced the error with fontspec without babel. I think it has been fixed in ConTeXt and a fix for luaotfload in on the way. See footnote 17, p. 29.

**Comment by josephwright** [comment]
On that basis, I assume 'report elsewhere' (and so close here).
