### ISSUE TITLE
lualatex exclusive callbacks stacks

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex2e#808]
## Brief outline of the enhancement

We must take care of exclusive callbacks because LaTeX is naturally a collaborative environment. 
In order to register her own exclusive callback, one has to remove and save the previous one, do whatever is required, remove her callback and finally restore the previous one.
This is a such a common design pattern that a builtin implementation would be very welcome.

## Example showing the expected behaviour

Two callback are registered for the `open_read_file` key. They just emulate a void file named `\jobname`and print a message to the console.
`exclusive_callback_push` is called to add a callback, its return value is a pop function that we call with no argument to revert to the previous state.
The relevant part of the console reads 
```
 (./sansnom-3.tex**** TEST1	./sansnom-3.tex
**** TEST1	./sansnom-3.tex
) (./sansnom-3.tex**** TEST2	./sansnom-3.tex
**** TEST2	./sansnom-3.tex
) (./sansnom-3.tex**** TEST1	./sansnom-3.tex
**** TEST1	./sansnom-3.tex
)
```
where 'sansnom-3' is the jobname.

```latex
\directlua{
callback_descriptions = luatexbase.callback_descriptions;
add_to_callback = luatexbase.add_to_callback;
remove_from_callback = luatexbase.remove_from_callback;
function exclusive_callback_push(callback_name, callback, description)
  local saved = {};
  for _,d in pairs(
    callback_descriptions(callback_name)
  ) do
    local v = remove_from_callback(callback_name, d )
    saved[d] = v
    break
  end;
  add_to_callback(callback_name, callback, description);
  return function ()
    local f, d = remove_from_callback(callback_name, description)
    for k, v in pairs(saved) do
      add_to_callback(callback_name, v, k)
    end
    return f, d
  end
end
}
\RequirePackage{latexbug}
\documentclass{article}
\begin{document}
POC
\directlua{
  pop1 = exclusive_callback_push(
    'open_read_file',
    function (file_name)
      return {
        reader = function ()
          print('**** TEST1', file_name)
          return nil
        end
      }
    end,
    'DESCRIPTION1'
  )
}
\input{\jobname}
\directlua{
  pop2 = exclusive_callback_push(
    'open_read_file',
    function (file_name)
      return {
        reader = function ()
          print('**** TEST2', file_name)
          return nil
        end
      }
    end,
    'DESCRIPTION2'
  )
}
\input{\jobname}
\directlua{
  pop2()
}
\input{\jobname}
\directlua{
  pop1()
}
\end{document}
```

**Comment by zauguin** [comment]
> In order to register her own exclusive callback, one has to remove and save the previous one, do whatever is required, remove her callback and finally restore the previous one.

I don't think that that's a pattern we should support. Registering an exclusive callback (pretty much by definition) gives exclusive control over a callback. Temporarily taking over control breaks this and might lead to unexpected behavior.

IMO the perceived need for functionality like this rather indicates that the callbacks in question maybe either shouldn't really be exclusive in the first place or that it should be implemented by some kind of dispatcher (which might live outside of the kernel at the beginning).

**Comment by jlaurens** [comment]
The open_read_file callbacks can be nested such that preemptive exclusiveness may break things.
Instead cooperative exclusiveness as requested allows to safely separate code.
Moreover, it helps in reentrant management.

In that case "exclusive" is restricted to one definite task, and a different task may need a different "exclusive" callback.
If the task are separate in time, there is no problem. If the task overlap, then things may break.

Another similar example: the line_break_filter need not be the same for the whole document.
It can be different in some LaTeX environments, say for example in multicols, in can also be different for one specific imported file…
Here again, nested exclusive callbacks is the right collaborative pattern.

If one package is allowed to silently unregister the callback registered by a different package, things may seriously go wrong and difficult to debug. 

luatexbase.sty may be a good candidate to hold such a feature, or at least to hold some ‘best practice’ notes about that.

JL

**Comment by jlaurens** [comment]
In fact this stack design requirement may not be restricted to exclusive callbacks. The `process_input_line` may be used to translate from one formatting language to LaTeX. For example a markdown to LaTeX processor will push its callback before the translation process and will pop it once everything is done. If the markdown contains a different embedded format, then stacking helps.

Some people asked for a mean to have SyncTeX work with a different input format. This is actually available with R. More generally, callbacks are promising for that purpose, provided they don't break each other.

The `process_input_line` callback is one of the examples where actors and observers should be separate.
Actors may changed the input whereas observers just... observe. Actors cold be stacked, observers need not.

**Comment by zauguin** [comment]
> In that case "exclusive" is restricted to one definite task, and a different task may need a different "exclusive" callback.

Without knowing which task the exclusive callback is trying to solve you can't know that it no longer applies for your separate part. Therefore just disabling whatever is there might very well break things if the existing callback is doing something else then you expect.



> Another similar example: the line_break_filter need not be the same for the whole document. It can be different in some LaTeX environments, say for example in multicols, in can also be different for one specific imported file… Here again, nested exclusive callbacks is the right collaborative pattern.

Again it depends on why `line_break_filter` is provided in the first place. In your example, take a `multicols` environment which provides a new `line_break_filter` which is better optimized for short columns. Then assume that the document uses a language which has special line breaking rules and therefore requires a special `line_break_filter`. Now if the language is set globally and some part is set in multiple columns, your stacking would effectively break the language specific linebreaking in the multi column part. And this is happening quietly and without warning for the user.

> If one package is allowed to silently unregister the callback registered by a different package, things may seriously go wrong and difficult to debug.

At least that's true if the packages don't know about another. If package A provides a callback and package B is aware of package A and knows that it's own callback can replace package B's callback, then unregistering it might be fine. That's why `remove_from_callback` requires a description instead of just removing any existing callback.

But that's exactly what your stacking is doing: It silently unregisters callbacks from arbitrary different packages.

> luatexbase.sty may be a good candidate to hold such a feature, or at least to hold some ‘best practice’ notes about that.

Given that `luatexbase.sty` is designed as a compatibility layer for legacy interfaces it would be a rather odd place for something like this.

> In fact this stack design requirement may not be restricted to exclusive callbacks. The `process_input_line` may be used to translate from one formatting language to LaTeX. For example a markdown to LaTeX processor will push its callback before the translation process and will pop it once everything is done. If the markdown contains a different embedded format, then stacking helps.

Why would stacking help here? If the markdown contains a differen embedded format, the markdown processor at some point has to enable this different processor at which point it can disable itself (safely, since it knows what it's own code is doing) instead of having to rely on arbitrary disabling of existing callbacks. Afterwards it can reenable itself.

> The `process_input_line` callback is one of the examples where actors and observers should be separate.
> Actors may changed the input whereas observers just... observe. Actors cold be stacked, observers need not.

But for most "actors" that would be the wrong thing to do. Most uses of `process_input_line` I have seen don't interfere with each other at all and can perfectly combine with other code in the callback. Some "stacking" which would temporarily unregister them in some parts of the document would needlessly break their functionality.

**Comment by jlaurens** [comment]
That analysis is very interesting but it relies on many assumptions that are not always fulfilled. Moreover it does not really concern the current topic. Due to the apparent lack of interest, I close this and will go my own way.
