### ISSUE TITLE
hook rule in hook leads to spurious output

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#818]
## Brief outline of the bug

Due to the way hyperref loads some packages in begin document a rule for `begindocument` ended in the `begindocument` hook and led to spurious output if there is another hook rule:

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\AddToHook{begindocument}[A]{}
\DeclareHookRule {begindocument}{A} {after} {B}
\AddToHook{begindocument}[B]{\DeclareHookRule{begindocument}{x}{before}{y}}

\begin{document}
Foo
\end{document}
```

## Log file (required) and possibly PDF file  

![image](https://user-images.githubusercontent.com/4047173/168567400-e5116f72-383f-4194-b0fd-51d1389d7848.png)

[test-utf8.log](https://github.com/latex3/latex2e/files/8699025/test-utf8.log)

**Comment by FrankMittelbach** [comment]
The result is certainly wrong, but it isn't clear to me what the correct behavior should be. Obviously loading a package inside begindocument that itself tries to install a rule for ordering begindocument can't work, because the hook is already sorted by that time and given that it is a one-time hook it doesn't even make sense for a later invocation (as there is none).

In order to have any effect hyperref would need to load such packages earlier, e.g., inside begindocument/before. But, of course, the general problem remains and needs solving, i.e., that hook resorting initiated by \DeclareHookRule goes wrong in that position.

(by the way, why is \DeclareHookRule defined to be expandable?)

**Comment by josephwright** [comment]
I'd imagine we need to disable `\DeclareHookRule` for the hook when we are actually inside the hook, at least for the one-time ones - perhaps that could be done by having `\DeclareHookRule` 'save up' tasks to the end of each hook, which for a one-time hook would then be ano-op?

**Comment by u-fischer** [comment]
hyperref will load nameref earlier in the next version, package loading in begindocument isn't good  and I wanted to change that anyway and so here is the opportunity.

**Comment by PhelypeOleinik** [comment]
> I'd imagine we need to disable `\DeclareHookRule` for the hook when we are actually inside the hook

Not quite. The problem is really with one-time hooks due to an implementation detail.  I override the `reversed` property of the hook to tell it's one-time, and when that arrives in the insides of the sorting routine, it breaks.  I fixed that by just making the code not sort one-time hooks.  Other hooks can still be sorted even while running their own code.

> (by the way, why is \DeclareHookRule defined to be expandable?)

It's not though...

https://github.com/latex3/latex2e/blob/538c0f443fceb5a3ffe5c4343d55a57c7a44c214/base/lthooks.dtx#L5363

and

https://github.com/latex3/latex2e/blob/538c0f443fceb5a3ffe5c4343d55a57c7a44c214/base/lthooks.dtx#L3622

are both protected...
