### ISSUE TITLE
Package "doc" assumes a fixed set of mathcodes

### ISSUE THREAD

**Issue by josephwright** [latex3/latex2e#820]
## Brief outline of the bug

As title: `\mod@math@codes` has a fixed set of codes, and this is not the case with Unicode engines/`unicode-math`.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug} 
\documentclass{article}
\usepackage{doc}
\usepackage{unicode-math} %  To produce a \mathcode change
\begin{document}
    \begin{macrocode}
%<filea|fileb> test
%    \end{macrocode}
\end{document}
```

## Log file (required) and possibly PDF file  

Log attached: PDF shows
![test](https://user-images.githubusercontent.com/654518/168871991-de939ab9-142c-47f1-9a9d-e5be47bba859.png)

Details of the issue were first reported in https://tex.stackexchange.com/questions/644510/vertical-bar-in-docstrip-file-changes-to-j-with-unicode-math

**Comment by FrankMittelbach** [comment]
Well, as the log clearly shows, this should be reported to unicode-math not to us :-), how far are we with moving unicode-math also under latex3 repository?

leaving that aside, the solution to the problem is to adjust the doc hook for it (which is from 1992), so an old fashioned hook (and it is really a configuration point anyway): but basically
```
\AddToHook{package/unicode-math/after}{%
  \AddToHook{cmd/mod@math@codes/after}{\mathcode`\|=28796 }}
```
The inner hook setting could go into unicode-math directly. Technically it might be better for unicode-math to fully (re)define `\mod@math@codes` instead of the above as that is a little bit more efficient, but the above works without needing to know if doc gets loaded

**Comment by josephwright** [comment]
> Well, as the log clearly shows, this should be reported to unicode-math not to us :-), how far are we with moving unicode-math also under latex3 repository?

I did think of that, but the assumption is in `doc` not in `unicode-math` - it's reasonable in a 7-bit world, of course.

> leaving that aside, the solution to the problem is to adjust the doc hook for it (which is from 1992), so an old fashioned hook (and it is really a configuration point anyway): but basically
> 
> ```
> \AddToHook{package/unicode-math/after}{%
>   \AddToHook{cmd/mod@math@codes/after}{\mathcode`\|=28796 }}
> ```

Is `\mod@math@codes` a documented interface? Feels odd

**Comment by FrankMittelbach** [comment]
> Is `\mod@math@codes` a documented interface? Feels odd

what defines an interface here? This is from 1992 :-) but anyway beasically nobody needs "an interface" except for the one package (or two packages) so far that load math fonts that do not conform to mathfont slot positions defined by the CM + amsfonts and such packages then need to redefine all math-related stuff all of which hide in some `\...@..@` inside the format or amsmath or ... just look at fontmath.ltx 

No user or even package developer needs an interface (even though it is there in rudimentary form) because no person dreams up new math font encodings, well hardly anybody (except the Unicode folks and Will who implemented their design).
