### ISSUE TITLE
fontenc.sty does not have \listfiles info

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#825]
Probably there is some good reason for it, and clearly nothing crucial, but fontenc.sty does not report anything with \listfiles.

```latex
\listfiles
\documentclass{article}
\usepackage[T1]{fontenc}
\begin{document}
\end{document}
```

Log excerpt:
```
 *File List*
 article.cls    2021/10/04 v1.4n Standard LaTeX document class
  size10.clo    2021/10/04 v1.4n Standard LaTeX file (size option)
 fontenc.sty
l3backend-pdftex.def    2022-04-20 L3 backend support: PDF output (pdfTeX)
 ***********
```

**Comment by davidcarlisle** [comment]
This is sort of by design and  documened:

```
% Finally we pretend that the fontenc package wasn't read in. This
% allows for using it several times, e.g., in a class file and in the
% preamble (at the cost of not getting any version info).
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
% That kind of hackery shows that using a general purpose
% package just for loading an encoding is not the right kind
% of interface for setting up encodings --- it will get replaced at
% some point in the future.
% \changes{v1.9r}{1999/01/07}{Hackery to allow using fontenc several
%    times}
````

To allow `\usepackage[...]{fontenc}` the package essentially clears the `\ver@fontenc.sty` tha records that it has been loaded
This has the effect that you show on listfiles.

As ever if we were doing it now we might spend a few tokens to special case this in a different way but 

```
\global\expandafter\let\csname ver@fontenc.sty\endcsname\relax
```

was cheap and effective

as fontenc is extracted from ltoutenc.dtx in the format source, the version information is essentially the same as the format version banner so you don't lose a lot of information here really,

**Comment by FrankMittelbach** [comment]
maybe we should say so explicitly:
```
       \typeout{%
         \filename@area\reserved@a
         \@spaces
         \ifx\reserved@b\relax --No version info provided--\else\reserved@b\fi}}%
```
but I would not try to make the system smarter otherwise.

**Comment by kberry** [comment]
Thanks for the info. "No change" is fine with me. 
It just struck me as odd.

**Comment by davidcarlisle** [comment]
@kberry actually we decided to change, seems harder to justify not having space for a dozen tokens now than it was back then.

See 

https://github.com/latex3/latex2e/commit/1e1d7023461a312aeb205d810c58694472dba849
