### ISSUE TITLE
Error in pre-release-4 with utf8x and hyperref

### ISSUE THREAD

**Issue by scottkosty** [latex3/latex2e#833]
## Brief outline of the bug

On a TeX Live 2022 installation, a document using utf8x and hyperref fails on pre-release-4 but compiles on stable.

I understand that typically issues with non-core packages should not be reported here, but I remember reading somewhere that an exception is when a new failure occurs on a pre-release. However, I could not confirm on CONTRIBUTING.md or on https://www.latex-project.org/bugs/ that this is the official recommendation. Is this exception documented somewhere? In any case, I hope I am following procedure correctly. My apologies if not.

I've searched this repository for issues with "utf8x" and did not find any that seemed to report the current issue (there were only 4 closed old issues).

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage[utf8x]{inputenc}
\usepackage{hyperref}

\begin{document}
Testing
\end{document}
```

## Log file (required) and possibly PDF file  

Here is a log using `pdflatex`: [good.log](https://github.com/latex3/latex2e/files/8793519/good.log)

And here is a log from using `pdflatex-dev`: [bad.log](https://github.com/latex3/latex2e/files/8793521/bad.log)

## Thank you

Thank you, LaTeX team, for your work! I really appreciate all of your time and dedication. I also really like this pre-release `-dev` idea, as it makes it easy to (hopefully) contribute in a small way by testing.

**Comment by u-fischer** [comment]
You can do for now as a work around

~~~~
\usepackage{hyperref}
\makeatletter
\def\HyPsd@expand@utfvii{}
\makeatother
~~~~

But I would recommend to drop `utf8x`/`ucs`. Most improvements in the handling of utf8 which e.g. allow you to use them in `\label`s and filenames are undone by `utf8x`/`ucs`.

**Comment by scottkosty** [comment]
Thanks for the quick reply, Ulrike, and the advice!

**Comment by davidcarlisle** [comment]
Thanks for the report.

At the time ucs/utf8x were written the core inputenc files were very coservative in the characters they support, however by now most accented latin letters are supported by default and utf8 support is preloaded in the format, so in most cases simply not loading uf8x will solve the issue.

If there are documents requiring inputenc for additional Unicode ranges not currently supported by inputenc, please open an issue and we would definitely consider providing mappings that work with the standard UTF-8 processing.

Unfortunately utf8x does not just add additional ranges it re-implements the utf-8 decoder, making characters fragile, so breaking all the support for UTF8 added in recent years, so utf8 in labels, filenames, and uppercasing for example.

The issue is not restricted to hyperref see for example

```
\documentclass{article}
\usepackage[utf8x]{inputenc}

\begin{document}
Testing
\MakeUppercase{êöé}
\end{document}
```

![image](https://user-images.githubusercontent.com/1268738/180600927-c8f963b3-dae0-4a1f-8254-02167e7bbc71.png)


The package could probably be updated but it is not in our control.

As such we have decided to close with no action

**Comment by scottkosty** [comment]
Thanks for the detailed explanation!

**Comment by scottkosty** [comment]
Just an update that after a tlmgr update I think the compilation works fine now, although I'm not sure what caused it. Maybe the new ucs version.

**Comment by u-fischer** [comment]
Yes, the new ucs makes it again compatible. But see the message in the log:

~~~~
Package ucs Info: utf8x disabled, assuming standard utf8 processing
(ucs)             load ucs package to force utf8x processing.
~~~~

This means the `\usepackage[utf8x]{inputenc}` no longer uses ucs and does nothing special unless you explicitly loaded the ucs package before too.

**Comment by scottkosty** [comment]
Ah I understand now. Thank you @u-fischer !

**Comment by FrankMittelbach** [comment]
But ucs package should not be loaded unless you really want to use something of the special stuff it does. It should not be loaded if all you had is `\usepackage[utf8x]{input}`! Perhaps that that info message should be a little more expicit here to avoid that people think they should load ucs now, what do you think @davidcarlisle ?

**Comment by davidcarlisle** [comment]
@FrankMittelbach  I wanted to keep the message reasonably short.

For some extended features or non-european ranges not covered in the default utf8 simply removing `[utf8x]` may not be enough and adding `\usepackage{ucs}` (if it doesn't completely blow up) might be the simplest compatibiity fix.
I think longer term ucs package should itself warn if it is used, but I didn't do that this time, wanted to see how this faired "in the wild".
