### ISSUE TITLE
Notify wrong “keywords” in generic hooks

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#835]
## Brief outline of the enhancement

In case of a wrong “keyword” in a generic hook, the latter is ignored. It would be useful if a warning or an error would notify the mistake.

## Minimal example showing the current behaviour

Here is a minimal example with `end` as a wrong “keyword” (the right one being `after`).
```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\NewDocumentCommand{\foo}{}{foo}

\AddToHook{cmd/foo/end}{bar}

\begin{document}
\foo

\AddToHook{cmd/foo/end}{bar}
\foo

\AddToHook{cmd/foo/after}{bar}
\foo
\end{document}
```

**Comment by FrankMittelbach** [comment]
There are a number of reasons why I think this is not  good.

 - It would mean executing a large number of tests on each run for something that is largely a programmer error (it should therefore better done only in a debugging mode (if at all)).
 - More importantly, it would generate a lot of false positives. For example, each time something is added to a hook that is not yet there (because the package that defines it is not yet loaded (or is never going to be loaded). That would be confusing for users seeing such "warnings" in the the log for their documents even though they are perfectly correct.

I therefore think the current behavior is as it should be (it is at least exactly as designed (because of the second reason)).

**Comment by dbitouze** [comment]
Wouldn't be possible to list at the end of the document the hooks that were intended to be used but weren't used?

**Comment by FrankMittelbach** [comment]
sure, but it would have the same problem. For example, already in the format LaTeX sets a larger number of generic hooks as first aid for packages that are broken and not yet fixed; they would then all show up in each and every document as unknown hooks and each each usage of a hook would need to contribute to that data structure, so quite a footprint. That is why I said that if done it should only be in some special debugging mode (like the one in expl3 that checks if your variables are all declared and that your use global variable with global mutators etc.)

by the way, it is not so much different from misspelling an environment: that would also silently do nothing.

**Comment by dbitouze** [comment]
OK but...

> by the way, it is not so much different from misspelling an environment: that would also silently do nothing.

Really? The following:
```latex
\documentclass{article}
\begin{document}
\begin{foo}
  Foo
\end{foo}
\end{document}
```
fails to compile with:

>! LaTeX Error: Environment foo undefined.

**Comment by dbitouze** [comment]
Sorry to insist: wouldn't be possible to treat differently the hooks defined:

- in the format LaTeX, classes and packages,
- by the user in its document?

**Comment by u-fischer** [comment]
> Wouldn't be possible to list at the end of the document the hooks that were intended to be used but weren't used?

How should one know which hooks were intended to be used?
And do you really want that `\AddToHook{cmd/foo/after}{bar}` creates a warning if `\foo` is not used in the document? 

hooks are like `\csname`. They can fail silently, and you have to check if they do what you expected.  (I normally add \typeout or \show commands during the development).

**Comment by dbitouze** [comment]
> How should one know which hooks were intended to be used?

By this (poorly expressed), I meant hooks defined by the user in his document.

> And do you really want that `\AddToHook{cmd/foo/after}{bar}` creates a warning if `\foo` is not used in the document?

I guess a user wouldn't define so much hooks so would be harmless.

> hooks are like `\csname`. They can fail silently, and you have to check if they do what you expected.

I opened this feature request precisely because of a stupid mistake of mine (`end` instead of `after`) and I first believed patching the command as I wanted wasn't possible, before I realized my mistake. Hence a user could see his hook fails without being aware this failure comes from a wrong keyword.

> (I normally add \typeout or \show commands during the development).

I don't see how I could use `\typeout` or `\show` in the cases of hooks such as in my OP.

**Comment by FrankMittelbach** [comment]
Denis

> How should one know which hooks were intended to be used?
> 
> By this (poorly expressed), I meant hooks defined by the user in his
>  document.

if the user is defining commands with his or her own hook, he should
remember what names he gave those hooks, if he or she is altering
existing hooks then it is actually quite likely that these hooks are either

  - generic (as in cmd/foo/after )
  - or are not from the kernel but from packages and so may happen before
or after the hook is patched in or the file is loaded or ...

> 
> And do you really want that |\AddToHook{cmd/foo/after}{bar}| creates 
> a warning if |\foo| is not used in the document?
> 
> I guess a user wouldn't define so much hooks so would be harmless.

well we think differently

> hooks are like |\csname|. They can fail silently, and you have to 
> check if they do what you expected.
> 
> I opened this feature request precisely because of a stupid mistake
> of mine (|end| instead of |after|)

I guessed as much, but ...

> and I first believed patching the command as I wanted wasn't
> possible, before I realized my mistake. Hence a user could see his
> hook fails without being aware this failure comes from a wrong
> keyword.
> 
> (I normally add \typeout or \show commands during the development).
> 
> I don't see how I could use |\typeout| or |\show| in the cases of
> hooks such as in my OP.

you can use \ShowHook (after begin document to see what state your hook
has), I guess what Ulrike meant is that you can put \typeout into your
cook def, to see when it is executed. Sure if you mistype the name it is
not executed at all, but as I said this is a deliberate design decision
and penalizing users who use that in order to help users that make typos
isn't is not going to happen, sorry.

doing it just for \AddToHook  in the preamble of course is technically
possible (given that TeX is Turing ...), but imo fairly pointless,
because a user could put something into his or her private .sty and in
addition you would need a fair amount of machinery to keep track of what is
used where so it remains a complicated implementation that slows things
down, complicates the overall algorithm and is only covering a few
sub-cases of what you labeled "a stupid typo".
