### ISSUE TITLE
Defining a new environment based on document environment gives error

### ISSUE THREAD

**Issue by kvafa** [latex3/latex2e#843]
## Brief outline of the bug
Defining a new environment based on document environment gives error. However, this used to work few years ago and now is broken. The error is

````
./test.tex:5: LaTeX Error: \begin{vafa} on input line 3 ended by \end{document}
.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.5 \end{vafa}
              
? 
````

The definition
````tex
\newenvironment{vafa}{\document}{\enddocument}
````
also gives the same error.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

  % Any preamble code goes here
\newenvironment{vafa}{\begin{document}}{\end{document}}
\begin{vafa}

  % Demonstration of issue here
  
\end{vafa}
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/8837512/test.log)

**Comment by muzimuzhi** [comment]
The error is thrown by `\@checkend{document}` used in `\enddocument`. But [`git blame`](https://github.com/latex3/latex2e/blame/878a4715df024fc3425d2bfd5d3d138b9395c178/base/ltmiscen.dtx#L223) shows that line has been there for at least 14 years, and tests on Overleaf.com with texlive as old as 2014 always throw the same errors. Hence I doubt a bit whether that ever worked.

**Comment by FrankMittelbach** [comment]
This may have work in some cases in the past, but it was never a supported syntax, which is (since 2e):
```
\documentclass{...}
...
\begin{document}
...
\end{document}
```
The reason is that the document environment is special and requires not to be executed in a group and my guess is that with the additional executions around that environment this is now triggering the issue you see.

As a possible workaround (but without any guarantee that this will not break in the future too) you could try
```
\newenvironment{vafa}{\endgroup  \begin{document}}{\end{document}}
```
Better, however, going forward would be to use use the available Hooks for the document environment and avoid redefining or overwriting/replacing it. See `texdoc lthooks-doc` for details.

**Comment by kvafa** [comment]
Thanks Frank. The minimal example I gave above is simply what `xepersian` does; it does not add anything to document or modify its definition in any way. The main idea is that a user can say `\شروع{نوشتار}‍` instead `\begin{document}` and `\پایان{نوشتار}` instead `\end{document}`. To achieve this, the package previously did something like

````tex
\let\شروع\begin
\let\پایان\end
\newenvironment{نوشتار}{\document}{\enddocument}
````
and things worked in the past but it does not know. I will sort this out anyway. Thanks for looking into this.

**Comment by FrankMittelbach** [comment]
In that case the `\endgroup` suggestion should work for you with the newer code.
