### ISSUE TITLE
Will `\begingroup/\endgroup` be documented and allowed to user at document level by LaTeX users?

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#854]
In usrguide3.pdf one finds the following example:
```
\NewCommandCopy\LaTeXorig\LaTeX
  \RenewDocumentCommand\LaTeX{}{\textcolor{blue}{\LaTeXorig}}
```
but the text before says 
```
However, please note that it is usually better to make use of available hooks (e.g., the generic command or environment hooks), instead of copying the current definition and thereby freezing it;
```
In the case at hand one could envision perhaps
```
\AddToHook{cmd/LaTeX/before}{\begingroup\color{blue}}
\AddToHook{cmd/LaTeX/after}{\endgroup}
```
but are `\begingroup/\endgroup` allowed vocables to the LaTeX user? Will they remain available in future LaTeX?

**Comment by FrankMittelbach** [comment]
I don't see that `\begingroup` and `\endgroup` are going to vanish in traditional style LaTeX2e code at least not in the forseeable future. However, it is not and will not be made a user command (i.e., documented as such) even though given that the names do not contain an @-sign we aren't actively preventing people from using it.

Concering your example above: I wrote "it is *usually* better to ..." based on the fact that in most cases where people used `\let` in the past in packages it was done to add some hooks into commands and *that* is much better done using existing hooks now. In the case at hand I would probably not complicate matters by invoking the hook mechanism, because it is rather unlikely that more  than one such redefinition or additions would be necessary. But if, then your suggested solution would be wrong, because it would execute the group in vertical mode if `\LaTeX`would start a paragraph. So it would need either `\mbox{}`or `\leavevmode` before starting the group and in such a construction I would use `\begin{color}` rather than `\begingroup`, but as I said I think it is the wrong approach for that simple  case and the suggested used of `\NewCommandCopy` is better.
