### ISSUE TITLE
\AddToHook remains silent when trying to add to cmd/<cmdname>/begin but has seemingly no effet

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#856]
## Brief outline of the bug

It could perhaps be nice to be able to do `\AddToHook{cmd/<cmdname>/begin}` and `\AddToHook{cmd/<cmdname>/end}`
with the idea that this would create automatically `\begingroup` and `\endgroup`.

I don't know if this is a good idea (one would have to test if `\endcmdname` exists to distinguish from environments perhaps) but currently it seems one can employ this interface without raising errors but it remains without effect.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\begin{document}

\AddToHook{cmd/TeX/begin}{\gdef\x{x}}
\AddToHook{cmd/TeX/end}{}

\ShowCommand\x
\end{document}
```

one finds in log file

```
> \x=undefined.
<argument> \x 
              
l.9 \ShowCommand\x
                  
```

and no errors.

## Log file (required) and possibly PDF file  

[templatex.log](https://github.com/latex3/latex2e/files/8893525/templatex.log)

**Comment by dbitouze** [comment]
It looks like you (as I did myself) have mixed up ``begin`/before` and ``end`/after`. Besides, I guess you forgot to use `\TeX`:
```latex
\RequirePackage{latexbug}
\documentclass{article}

\begin{document}

\AddToHook{cmd/TeX/before}{\gdef\x{x}}
\AddToHook{cmd/TeX/after}{}

\TeX{}

\ShowCommand\x
\end{document}
```

**Comment by jfbu** [comment]
> It looks like you (as I did myself) have mixed up `begin`/`before` and `end`/`after`. Besides, I guess you forgot to use `\TeX`:

no no quite deliberate. I was expecting an error. And I am suggesting that perhaps it could be a way to employ at user level the `\begingroup/\endgroup` functionality which is TeX not LaTeX.

**Comment by FrankMittelbach** [comment]
I would say the proposal to implicitly have hooks suddenly add groups is a bad one es this badly mixes up concepts.
If you want to make a "color group" you can always do `\begin{color}{blue} ... \end{color}`  (which I think is even discussed in Lamport, though I may be mistaken.

As for not raising an error for an invalid generic hook: that is a bit surprising to me, because we had that kind of check. Maybe it got disabled when we extended the generic hook concept to generic hooks offered by packages. But should probably be tightened ... we'll see.

**Comment by muzimuzhi** [comment]
> Maybe it got disabled when we extended the generic hook concept to generic hooks offered by packages.

Some evidence: Currently in `\__hook_try_declaring_generic_hook:nnn`, when the hook is not any generic hooks, `\__hook_gput_undeclared_hook:nnn` is used which will unconditionally init hook.
https://github.com/latex3/latex2e/blob/d18e71d9e9bab530da44585de92b893ffc835623/base/lthooks.dtx#L3097-L3103
https://github.com/latex3/latex2e/blob/d18e71d9e9bab530da44585de92b893ffc835623/base/lthooks.dtx#L3064-L3072

**Comment by FrankMittelbach** [comment]
The fact that `\AddToHook{<some name>}{...}` does not warn about the hook not being defined is deliberate and by design. After all, a package should be able to specify data for a hook that is defined in  some other package and that other package may or may not get loaded.

Thus, if you misspell the `<some name>` that is not going to give you a warning because the expectation is that the could may get defined later on. And it would not be correct to warn by, say `\begin{document}`because it is perfectly permissible to define data for, say a hook in `hyperref` but hyperref` is not being loaded in the document.

Initially, I designed the generic hooks to be of a limited list of names and have any other name rejected but we decided later to not make that distinction but handle all names in the same way.
