### ISSUE TITLE
docstrip : catcode 128 to 255 set to 12 in new version 2.5g (2018-05-03)

### ISSUE THREAD

**Issue by FOCCOF** [latex3/latex2e#87]
This post is about the docstrip.sty implementation of the DocStrip utility.

Hello,

A change has been made to docstrip in version 2.5g (2018-05-03) :

the macro \readsource implements a loop to set every catcode
between 128 up to 255 to the value 12 (='other')

I used to set some of those catcode to 9 (='ignore') in order
to highlight the .dtx source in my editor, such characters beeing
ignored when \read is performed inside the \readsource macro.

For example, I used the character ¤ (with \catcode 164 = 9 ) to
highlight the .dtx source. But this character will be ignored by \read
and will not be present in the docstrip \output.

The documented source says :
    "  To avoid any UTF-8 handling of characters    "
    "  we set code points 128{255 to other.        "

It could be interesting to filter such assignments like in :

    \ifnum 9=\catcode\@tempcnta
    \else    \catcode\@tempcnta 12\relax \fi

And a discussion could occur about which catcode have to be filtered
(trivially, the "category code 9 = ignore " should be ignored and not
set to 12, but my current opinion is that it should be the only
category 9...  or conversely, that the only category 13 is de-activated
with something like :
  ```
 \ifnum 13=\catcode\@tempcnta 
      \catcode\@tempcnta =12\relax \fi
```
But such a discussion is beyond the scope of my post.

Thanks for any of your help / answer.

**Comment by davidcarlisle** [comment]
> For example, I used the character ¤ (with \catcode 164 = 9 ) to

the problem is that if (as will increasingly be the case) the dtx file is
in UTF-8 then ¤ is the two characters with hex bytes C2 A4 and setting the
catcode of any byte above 128 to "ignore" would break the UTF-8 decoding of
a whole block of characters.

So to do what you ask would need some way of declaring the file encoding of
the file being stripped (and a way of ensuring that encoding wasn't changed
if the file was distributed)

So it's not impossible to do (looking at the source just now reminded me
that the docstrip.dtx file itself does something similar with the catcode
of Z but that has the advantage of still being a single byte in UTF-8) but
I don't think it would be enough to locally check the catcodes of
individual characters it would need a way to specify the file encodings to
be used for reading and writing the file and add quite a lot of
complication.

David

**Comment by FOCCOF** [comment]
thank you for this answer.

In other words, DocStrip only strips the source document, but does not filter or translate it in any way.

The  ¤  character in .dtx source will be actually copied to  .sty/.tex  file. Alternatively, I can set the catcode of  ¤  to 9 temporarily when TeX inputs the  .sty  file. My  .dtx  sources are always in ANSI Code Page (Western European) in order that it is treated the same by  pdfTeX  (Ascii compliant) and LuaTeX (UTF-8 compliant).

For memory : I use the  ¤  character in the source file in order to highlight some special lines in my TeX editor  (Alex Simonic's WinEdt software).

I think this topic is now closed.

Best regards

Florent.

**Comment by u-fischer** [comment]
I don't think that you can set the catcode of a single ansi byte `¤`  to ignore for luatex. If luatex sees this input it will complain about an invalid utf8 char.

**Comment by davidcarlisle** [comment]
> My .dtx sources are always in ANSI Code Page (Western European) in order
that it is treated the same by pdfTeX (Ascii compliant) and LuaTeX (UTF-8
compliant).

Just to strengthen the comment Ulrike made, if the file is in ISO-8859-1
encoding and has characters above 127 then (unless you set up file-reading
callbacks, or equivalent xetex encoding settings) it will not be readable
by luatex or xetex as the incoming bytes are always interpreted as UTF-8,
so this will give a low level file encoding error.
