### ISSUE TITLE
using figure in newenvironment crashes the compiler

### ISSUE THREAD

**Issue by Hu1buerger** [latex3/latex2e#911]
## Brief outline of the bug

I wanted to improve the readability of my document as these tables occur frequently. I already found out that tabularx supports using the "command-style" for usage in newenvironment.

As i want to wrap the table in a figure to pin a caption and lable onto it. 

Using the figure inside the newenvironment fails, while wraping it around work. See below

## Minimal example showing the bug

```latex
\RequirePackage{latexbug} 

\documentclass{report}

\usepackage[utf8]{inputenc} % Charakter-Kodierung
\usepackage[german]{babel} % Sprache

\usepackage[table,xcdraw]{xcolor} % Tabellen Farben
\usepackage{tabularx} % Dynamische Tabellenbreite
\usepackage{tcolorbox} % Graue Boxen
\usepackage{hyperref} % url Umgebung
\usepackage{todonotes} % Notizen
\usepackage{natbib} % Bibliographie
\usepackage{fancyhdr} % Header und Footer
\usepackage{multirow} % Multizeile
\usepackage{geometry} % Page layout
\usepackage{color} % Text Farben
\usepackage{array}

\begin{document}

\newenvironment{mytable}[0]{%
%\begin{figure}[h]% this dosnt seem to work
    \tabularx{\textwidth}{l | X} \hline%
}{%
    \endtabularx% as per tabularx, using the environment of tabularx dosnt work
    \caption{caption}
    \label{label:test}
%\end{figure}%
}

\newpage

%while wraping the figure environment around here, works
\begin{mytable}
        \textbf{Anwendungsfall ID} & UC-U2 \\ \hline
		\textbf{Anwendungsfallname} & Projekte in Umgebung anzeigen lassen \\ \hline
\end{mytable}
\end{document}
```

## Log file (required) and possibly PDF file  

[tex.log](https://github.com/latex3/latex2e/files/9427060/tex.log)

**Comment by u-fischer** [comment]
As your log-file says you are using third party packages:

~~~~

! Package latexbug Error: Third-party file(s)
(latexbug)                
(latexbug)                This test file uses third-party file(s)
(latexbug)                
(latexbug)                ==============
(latexbug)                german.ldf  ->  Juergen Spitzmueller 
(latexbug)                    <juergen [at] spitzmueller [dot] org> 
(latexbug)                tcolorbox.sty
(latexbug)                todonotes.sty
(latexbug)                natbib.sty
(latexbug)                fancyhdr.sty
(latexbug)                multirow.sty
(latexbug)                geometry.sty  ->  Hideo Umeki 
(latexbug)                    <latexgeometry [at] gmail [dot] com> 
(latexbug)                ==============
(latexbug)                
(latexbug)                So you should contact the authors
(latexbug)                of these files, not the LaTeX Team!
(latexbug)                (Or remove the packages that load
(latexbug)                them, if they are not necessary to
(latexbug)                exhibit the problem).
(latexbug)                
(latexbug)                If you think the bug is in core LaTeX
(latexbug)                (as maintained by the LaTeX Team) but
(latexbug)                these files are needed to demonstrate
(latexbug)                the problem, please continue and mention
(latexbug)                this explicitly in your bug report
(latexbug)                (with an explanation why you think so).
~~~~

Please remove them from your example.

**Comment by FrankMittelbach** [comment]
As Ulrike already pointed out, there is a reason for latexbug and it is *not* that we want you to add it but to *add it and then follow its advice*. That helps us to handle more than reports because we don't have to weed through unnecessary data we can't do anything about.

Your problem is that it is *not* enough to use `\tabularx`, you have to use it in a way that `\endtabularx` is looking for the correct document element. Basically `\tabularx` remembers the the current environment to figure out where the table data is.
But according to your definition that is `figure` when `\tabularx` is called. Thus it scans for `\end{figure}` in your source and can't find that (because there is none).

Try
```
\newenvironment{mytable}[0]{%
\figure[h]% this dosnt seem to work
    \tabularx{\textwidth}{l | X} \hline%
}{%
    \endtabularx% as per tabularx, using the environment of tabularx dosnt work
    \caption{caption}
    \label{label:test}
\endfigure%
}
```
instead. Maybe the `tabularx` doc can be improved a but, but it is certainly not a code bug in LaTeX.

**Comment by davidcarlisle** [comment]
a safer alternative to using `\tabularx` and `\figure` would be  to use 

`\NewDocumentEnvironment{mytable}{b}{\begin{figure}\begin{tabularx} #1\end{tabularx}...`

In particular this form still allows the evironment hooks for `figure` to run.

**Comment by FrankMittelbach** [comment]
I keep forgetting that we added that :-) ... but anyhow that is still something to document in tabularx (better in fact than documenting the `\tabularx` approach.

**Comment by Hu1buerger** [comment]
> a safer alternative to using `\tabularx` and `\figure` would be to use
> 
> `\NewDocumentEnvironment{mytable}{b}{\begin{figure}\begin{tabularx} #1\end{tabularx}...`
> 
> In particular this form still allows the environment hooks for `figure` to run.

Thanks for the amazingly fast reply guys*. How would i use that? Same as with \begin{mytable} ?

**Comment by davidcarlisle** [comment]
yes use of the environment is unchanged, this used to be provided by the `xparse` package but has been integrated in the format for  couple of releases now.

**Comment by FrankMittelbach** [comment]
`texdoc usrguide3`

**Comment by josephwright** [comment]
Anything left to do here?

**Comment by FrankMittelbach** [comment]
I guess not.
