### ISSUE TITLE
Contrarily to \smash, the \llap, \rlap, and \clap commands do not quit vertical mode

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#912]
## Brief outline of the bug

Some years ago `\leavevmode@ifvmode` was added to `\finsm@sh` which is involved in implementing the user command `\smash`.

But no such modification was made to `\llap`, `\rlap`, `\clap`.  This may surprise end-users.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\newcommand{\somedecoration}{$\left\updownarrow \rule{0pt}{1.5\baselineskip}\right.$}

\begin{document}
First item

\llap{\smash{\somedecoration} }Second item

Third item

\leavevmode \llap{\smash{\somedecoration} }Fourth item

Fifth item

\end{document}
```

## Log file (required) and possibly PDF file  

[testllap.log](https://github.com/latex3/latex2e/files/9467943/testllap.log)

![Capture d’écran 2022-09-01 à 09 55 36](https://user-images.githubusercontent.com/2589111/187863006-55adcc7c-3ba4-4861-852c-4d8bc43d2d01.png)

**Comment by FrankMittelbach** [comment]
So it may, but this is documented and there is a good reason. `\llap` and `\rlap`are really code level (plain TeX) commands and have been used in million of places in code and in places where the "feature" of stacking boxes if in vertical mode was deliberately used. Changing that would nvalidate a large number of packages and even more documents.

Thus when `\clap` was added it was decided to give it the same semantics as the other two. 

The `\smash` situation is rather different and  a deliberate use of it in vertical mode extremely unelikely which is why we adjusted it to the LaTeX semantics back then.
