### ISSUE TITLE
\DeclareSymbolFont maybe needs \series@maybe@drop@one@m

### ISSUE THREAD

**Issue by giovanni111** [latex3/latex2e#918]
## Brief outline of the bug
Until TeXLive 2019, the following file produces a condensed italic "a". 
But since 2020, LaTeX uses the upright fallback font.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{minimal}
\DeclareSymbolFont{letters}{T1}{yvt}{mc}{it}%venturisADF package
\begin{document}
$a$
\end{document}
```

## Log file (required) and possibly PDF file  
[test.log](https://github.com/latex3/latex2e/files/9547814/test.log)

**Comment by FrankMittelbach** [comment]
Even though this is nicely cut down to just use kernel commands, the fact remains that since 1994 series values are not supposed to contain more than a single "m" and the error is therefore in the .fd file. It is true that in this case it never mattered until 2019, but still ...

Your example would work if you use `c` in the series argument  (despite the fact that the .fd file contains the incorrect `mc`). However, I see your point and it will probably never be the case that all of the remaining incorrect .fd files are going to be fixed, so I followed your suggestions and have `\DeclareSymbolFont` drop the surplus `m` if necessary .

**Comment by giovanni111** [comment]
Thank you!
Concerning the incorrect .fd files: I fear that even since 1994 a lot of those files have been produced because this is what fontinst has done -- and in fact does until today (version 1.933). Therefore, the problem might actually be a bit more relevant than my artificial minimal example suggests (even though fontinst in times of OpenType becomes more an more obsolete, of course).

**Comment by FrankMittelbach** [comment]
yes I know, which is why I added some initial maybe-drop-m. I also added it to `\SetSymbolFont` but perhaps one should have a quick check if that would be needed elsewhere and if so add it there too. But I must confess it is not a priority for me.
