### ISSUE TITLE
T1def does not define \_

### ISSUE THREAD

**Issue by ilyaza** [latex3/latex2e#935]
## Brief outline of the bug

Since `T1def` does not define `\_`, any encoding which would define it is not compatible with `T1`.  To report this bug, I use `T4` as an example.  So `latexbug` is disabled below.

Uncommenting `\DeclareTextSymbol{\_}{T1}{95}` below makes the run successful.

(It seems that `T1def` [etc] should define all the symbols handled by the base `LaTeX`.  I do not know how to get this list, so do not know how to check which other symbols are missing…)

## Minimal example showing the bug

```latex
% \RequirePackage{latexbug}	% Triggered by T4 -- but it has no way to fix shortcomings of T1
\documentclass{article}

\usepackage[T3,T4,T2A,T1]{fontenc}	% The last one is the default.
% \DeclareTextSymbol{\_}{T1}{95}	% missed in T1enc.def; with T4 gives ! LaTeX Error: Command \_ unavailable in encoding T1.

\begin{document}

\texttt{N\_n}

\end{document}
```

## Log file (required) and possibly PDF file  

[try-bug.log](https://github.com/latex3/latex2e/files/9804695/try-bug.log)

**Comment by zauguin** [comment]
This is not a `T1` issue but a `T4` bug. Instead of overwriting `\_` (and therefore breaking other encodings and it's use in math mode) `T4` is supposed to define `\textunderscore` which will then automatically get picked up by `\_`.

**Comment by ilyaza** [comment]
Thanks!  But: you write “… is supposed …”.  This brings the question: **supposed by who**?  

In other words: is there a place where such such “assumptions” are collected/documented?  (If not, this kind of weakens the argument — significantly…)

**Comment by FrankMittelbach** [comment]
By the 5 people in the world that write encoding .def files. Such files are supposed to set up encoding specific commands not other commands that are shorthands. It remains a bug in T4 whether it is explicitly or implicitly documented

**Comment by zauguin** [comment]
[`texdoc encguide`](https://texdoc.org/serve/encguide/0) in section 4 lists the encoding specific commands defined in OT1 and T1, including `\textunderscore`. Of course other encodings might add other commands, but they should not do so for glyphs which already have standard commands and they shouldn't use names like `\_` which are already used by standard macros which are not listed as encoding specific.

The last part is probably not explicitly documented by falls under the general: If you redefine standard commands things are likely to break unless you know exactly what you are doing.

**Comment by ilyaza** [comment]
@Frank: I write a lot of code which is *essentially equivalent* to writing a `def` file.  I cannot wrap it into a formal `def` file **since it is so damned unclear how to do**.  If I code this, hundreds of other people should do it too.

So your estimate of “5” may be formally correct, but it definitely gives a wrong impression of what is a cause and what is a consequence.

@zauguin: Thanks!  However, IMO what you wrote is “too fuzzy”: it is a long chain of (double/triple?) negatives which is unclear how to convert to “positives” (“What to do?”).  Like this (silly?) attempt of mine:

  * Feel free to redefine what is mentioned in [texdoc encguide](https://texdoc.org/serve/encguide/0) (**but only those in Section 4, and *not* those defined in `def` files discussed in this document**).
  * Feel free to define new commands which do not exist in base `LaTeX`.
  * If a base `LaTeX` command (not from `T1`/`OT1`) is not compatible with your encoding, you cannot redefine it to become encoding-specific.  (**And how one does an encoding-sensitive but not encoding-specific command?!**)

Did I miss some cases?

    

>

**Comment by FrankMittelbach** [comment]
Am 18.10.22 um 01:30 schrieb ilyaza:
> @frank <https://github.com/frank>: I write a lot of code which is 
> /essentially equivalent/ to writing a |def| file. I cannot wrap it into 
> a formal |def| file *since it is so damned unclear how to do*. If I code 
> this, hundreds of other people should do it too.

I'm not sure why it is so *damned unclear how to do*.

encoding-specific commands are commands that are changing their behavior 
when the current font encoding is changed. That means they do need to have

  - a definition in every encoding that is used
  - or they have to have a default encoding-specific definition

If somebody overwrites a non-encoding-specific command with an 
encoding-specific definition for one encoding without arranging that 
this change of command nature is reflected for all other encodings then 
obviously he or she will break the former definition of that command.

That is the case for \_  where T4 incorrectly makes it 
encoding-specific. But since there is no default and no definition for 
other encodings it obviously breaks in other encodings once the T4 
definition is loaded. You concluded from that that T1 is missing a 
definition while we said, no T4 shouldn't have overwritten the existing 
definition but instead defined the correct slot for \textunderscore

That is not different to, say, a style file is overwriting a command 
definition with 2 arguments to have only 1 or have 3 arguments then 
clearly any other already existing use will break

\_ is one of a few (if you like historical) commands that are usable in 
text and math and produce symbols. In text they have to be encoding 
specific so all of them are implemented by pointing to an encoding 
specific definition. Other examples are \copyright \pounds \S \P

It would perhaps be helpful if those are explicitly listed as just being 
aliases to encoding specific commands (they are so documented in the 
LaTeX Companion)

However, I would be really interested to understand what kind of 
existing LaTeX commands you consider encoding-sensitive but which are 
not defined as encoding-specific (and not one of these alias commands).
