### ISSUE TITLE
top float in two column mode leads to nesting error for links

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#94]
## Brief outline of the bug

The output routine boxes pages with top floats differently to other pages. This leads to error for links broken across pages as the box levels differ. 

~~~
! pdfTeX error (ext4): \pdfendlink ended up in different nesting level than \pdfstartlink.
~~~

In https://tex.stackexchange.com/a/249743/2388 Heiko Oberdiek analysed the problem and suggested as patch (with the comment "maybe the vertical glue assignments might change")

~~~
\usepackage{etoolbox}
\makeatletter
\patchcmd\@combinedblfloats{\box\@outputbox}{\unvbox\@outputbox}{}{%
  \errmessage{\noexpand\@combinedblfloats could not be patched}%
}%
\makeatother
~~~

I'm moving this from https://github.com/ho-tex/hyperref/issues/19 as the suggest patch seems to indicate that it is a problem that should be resolved by the output routine.

## Minimal example showing the bug
(uses hyperref)

```latex
\RequirePackage{latexbug}
\documentclass[twocolumn]{article}

\usepackage{hyperref}

\begin{document}
\begin{figure*}\end{figure*}

\null\vfill\newpage
\null\kern.95\textheight

\href{http://tex.stackexchange.com}{This is a very very
  very very very very very very very very very very very very very
  very very very very very very very very long link.}
\end{document}

```

## Log file (required) and possibly PDF file  

[test-utf8.log](https://github.com/latex3/latex2e/files/2621750/test-utf8.log)

**Comment by FrankMittelbach** [comment]
I would like to better understand why that error happens: is there a real requirement on the nesting level or is it just a precautionary check that is not fulfilled?

I mean there is no known reason that text that is split afterwards is recombined in different box levels (I could think of several scenarios how that could come about).

So while the suggested unboxing cures the symptom it doesn't cure the problem (or does it). In other words is that checking correct in the first place or should hyperref be a bit more friendly in that situation?

If there *is* a valid reason why the box levels need to be the same (I mean we are talking about levels on different pages even!) then I think we need a clear set of requirements because that essentially means that if you want this working safely you would need to ensure that a galley that gets split always keeps their data on the same nesting level ... which is a bit weird on first glance.

**Comment by car222222** [comment]
But what does the pdf standard say?  And do pdf viewers, or analysis by Acrobat Pro, care about the different nesting levels?

**Comment by u-fischer** [comment]
@car222222 The pdf standard is irrelevant here. Inside the pdf there are no box levels. Imho the reason for the requirement is that it allows pdftex to interrupt links:

~~~~
\documentclass{article}

\begin{document}
\mbox{\leavevmode\pdfstartlink 
  attr {/Border[0 0 1]}
  user{
       /Subtype/Link%
       /A<<%
         /Type/Action%
         /S/URI%
         /URI(blkub)%
       >>%
      } Link}  not linked \mbox{Link  \pdfendlink} 
\end{document}
~~~~

This means that one can e.g. avoid that headers are links too.

**Comment by davidcarlisle** [comment]
> But what does the pdf standard say? And do pdf viewers, or analysis by Acrobat Pro, care about the different nesting levels?

the pdf ends up being malformed. the requirement about box levels of course doesn't translate to PDF, but the tex back-end's ability to close a stack of link start annotations at the end of a page and re-open them at the next page in a way such that the link-end annotations that appear in the main list on the next page pop the stack correctly is limited to the startlink and endlink specials being at the same group level.

**Comment by FrankMittelbach** [comment]
@u-fischer or perhaps an engine missrequirement.  @car222222  as boxes are internal to TeX I doubt that they end up 1-2-1 in the pdf necessarily. My guess is that check is really a precaution to ensure that one has identified the "right" end to some start bit. I mean in the example it is (after unboxing in the OR) the same level and then it work, but it is same level in 2 totally different box structures on 2 different pages. so my guess (but only a guess) that some programmer thought this is a good idea for checking.

Anyway you are right, it would be good to understand if this is due to some requirement from the pdf side and if so what the requirement really is, or just due to some engine "feature" that could be done differently.

But assuming it is the way it is then fixing as Heiko suggested will only cure that particular example but not necessarily the problem. Might be enough for 2e, but it then means there is a requirement for gally processing lurking for L3 here!

As an aside: I initially thought that the unboxing would be fairly dangerous, perhaps messing up column alignment etc, but after looking into latex.ltx I don't think it can do any harm (in that particular spot with the std LaTeX code.

**Comment by FrankMittelbach** [comment]
@davidcarlisle ok then, in that case we would need to track that level in theory and avoid that any text that is getting split (in some sense arbitrarily, eg through page breaking or vsplitting) is always at the same level of boxes at shipout time.

**Comment by davidcarlisle** [comment]
@FrankMittelbach  yes or I suppose we could stare at the pdf back end code in pdftex/luatex and see if enhancements could be suggested. but not tonight....

**Comment by FrankMittelbach** [comment]
@davidcarlisle no not tonight :-)  but it begs the question if xetex doesn't care whether that is because it generates a malformed pdf or whether it does handle this situation better because in all honesty tracking
 the TeX box level because of this wouldn't be fun

**Comment by car222222** [comment]
Yes, I understand that boxes disappear in the creation of the pdf.   Thanks to Ulrike for the example showing that the pdf creation process (in pdftex derivatives, at least, allows links to be split across boxes but to not be expressed in the nterbening material.

I agree that we really need to know what algorithm is used by the pdf creator to decide what happens to links in the text that is arbitrarily split at a page break, and whether the current processing is sufficiently adaptable to more general page-makeup requirements, both current and future.

**Comment by u-fischer** [comment]
One doesn't end "only" with a malformed pdf when the links are not nested correctly. The error is fatal:
`!  ==> Fatal error occurred, no output PDF file produced!`. 

xetex cares in some sense also about the box level too. Like with pdftex you get a "linked" footer is you use fancyhdr (which adds boxes to the footer). But you don't get errors when the boxing level of the end special is different, and it has specials to "interrupt" the links. On the whole this looks like a saner approach. Looks like this issue should wander ...

~~~~
 \documentclass[12pt,a4paper]{article}
 \usepackage{hyperref}
 \usepackage{fancyhdr}
 \pagestyle{fancy}
 %\cfoot{\special{pdf:nolink}\thepage\special{pdf:link}}
\usepackage{lipsum}

\begin{document}
\vspace*{39\baselineskip}
xxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxx
\href{xxxxx}{herrmann blub}

\end{document}
~~~~

**Comment by FrankMittelbach** [comment]
Am 27.11.18 um 23:56 schrieb Ulrike Fischer:
> One doesn't end "only" with a malformed pdf when the links are not 
> nested correctly. The error is fatal:
> |! ==> Fatal error occurred, no output PDF file produced!|.

I know, but isn't that just because the engine decided to bail out? it 
could still continue and would then produce a malformed pdf as David said.

> xetex cares in some sense also about the box level too. Like with pdftex 
> you get a "linked" footer is you use fancyhdr (which adds boxes to the 
> footer). But you don't get errors when the boxing level of the end 
> special is different, and it has specials to "interrupt" the links. On 
> the whole this looks like a saner approach. Looks like this issue should 
> wander ...

so it seems as if the engines could do that in a better way. As I said 
trying to track the boxing levels at the macro level would be more than 
painful if not outright impossible

doesn't prevent us from applying the unboxing patch, though if we agree 
that is safe. Initial run through the base tests got me 6 hits for 
pdftex tests (only looked at 2 but they are obvious as the do Completed 
page displays)

but yes, I think ultimately this is an engine question as this seems to 
be in some sense a questionable design that is very limiting and xetex 
may has the better answers here.

**Comment by u-fischer** [comment]
> One doesn't end "only" with a malformed pdf when the links are not nested correctly. The error is fatal: |! ==> Fatal error occurred, no output PDF file produced!|.
> I know, but isn't that just because the engine decided to bail out? it could still continue and would then produce a malformed pdf as David said.

I don't see this. At the end the link simply produces a  list of rectangles. The last one must have a top right coordinate, but any would do - the link area could be wrong then but the pdf would be valid.  The case that the \pdfendlink is missing is handled without problems: then everything is in the link area. 


> As I said trying to track the boxing levels at the macro level would be more than painful if not outright impossible doesn't prevent us from applying the unboxing patch, though if we agree that is safe. Initial run through the base tests got me 6 hits for pdftex tests (only looked at 2 but they are obvious as the do Completed page displays) 

Imho the danger to get more of such box-level problems is more theoretical. Start and end of links are normally not set individually and so quite seldom end in different box levels. I did a bit research about older reports of the error and all which gave enough info about the document seem to be caused by the twocolumn/topfloat problem described here. So if the patch can be applied it would be quite good. 
 

> but yes, I think ultimately this is an engine question as this seems to be in some sense a questionable design that is very limiting and xetex may has the better answers here.

At least the `\special{pdf:nolink}`  looks rather useful, as it would allow to get around the problem that footers get linked sometimes.

**Comment by FrankMittelbach** [comment]
Am 28.11.18 um 09:34 schrieb Ulrike Fischer:
>     As I said trying to track the boxing levels at the macro level would
>     be more than painful if not outright impossible doesn't prevent us
>     from applying the unboxing patch, though if we agree that is safe.
>     Initial run through the base tests got me 6 hits for pdftex tests
>     (only looked at 2 but they are obvious as the do Completed page
>     displays)
> 
> Imho the danger to get more of such box-level problems is more 
> theoretical. Start and end of links are normally not set individually 
> and so quite seldom end in different box levels. I did a bit research 
> about older reports of the error and all which gave enough info about 
> the document seem to be caused by the twocolumn/topfloat problem 
> described here. So if the patch can be applied it would be quite good.
> 

The danger may be fairly theoretical in current 2e because the twocolumn 
is is the only one of that nature in the kernel and there aren't that 
many packages that attempt more complex page building that involves 
splitting the galley and reassembling it later on. But that wouldn't be 
the case if a more general OR is being build (which eventually is the 
goal). But even in 2e I wouldn't be too surprised if something like 
flowfram could end up with generating this problem. I mean all you have 
to do is to take paragraph material split it (which could be the OR 
action as in the twocolumn case) and then mount the parts somehow and 
end up mounting with different number of nested boxes.

**Comment by FrankMittelbach** [comment]
Anyway, the twocolumn/topfloat problem is now address in the LaTeX kernel and the more general question about "is this fatal error needed or can it be avoided without keeping track of box nesting levels" should probably be addressed elsewhere.
