### ISSUE TITLE
Using \\[ex4] in tabular instead of \\[4ex] causes apparent infinite loop in compile

### ISSUE THREAD

**Issue by mqrzbw** [latex3/latex2e#941]
## Brief outline of the bug
Using \\[ex4] instead of \\[4ex] causes compiler to go into apparent infinite loop.

## Minimal example showing the bug

\RequirePackage{latexbug} 
\documentclass{article}
\usepackage[utf8]{inputenc}
\begin{document}
\begin{tabular}{c | c}
A B \\[ex4]
\end{tabular}
\end{document}

## Log file (required) and possibly PDF file  

Compiled on Overleaf. No log file produced since compiler times out.
I have resolved this issue. Submitting this issue as community service.

**Comment by FrankMittelbach** [comment]
Thanks for the report. It is unfortunately always possible to produce a looping document, the most simple one would be
```
\newcommand\foo{\foo}
\foo
```
but LaTeX tries hard not to generate loops when there are errors. In this particular case there is a clear error first, namely:
```
Missing number, treated as zero.
<to be read again> 
                   e
l.5 A B \\[ex4]
```
only by default you don't see this on Overleaf because Overleaf runs without stopping when encountering errors. This is then followed by for more low-level erros after which LaTeX does indeed go into a loop (and that would be pretty hart to prevent from the LaTeX side).

The solution on Overleaf is to tell it to stop on the first error (which you can in the menu next to the "recompile" button) a and perhaps even set as your default. In fact Overleaf does tell you that:

> Sorry, your compile took too long to run and timed out. The most common causes of timeouts are:
 - Large or high-resolution images are taking too long to process. 
You may be able to [optimize them](https://www.overleaf.com/learn/how-to/Optimising_very_large_image_files).

 - A [fatal compile error](https://www.overleaf.com/learn/how-to/Why_do_I_keep_getting_the_compile_timeout_error_message%3F#Fatal_compile_errors_blocking_the_compilation) may be completely blocking compilation.
 - Enable “Stop on first error” to help you find and fix errors right away.
