### ISSUE TITLE
Better error messages for tabular

### ISSUE THREAD

**Issue by Friedrich2** [latex3/latex2e#961]
## Brief outline of the bug
`tabular` gives often wrong or at least misleading error messages (e. g. `extra alignment tab has bin changed to \cr`, despite that the alignment tab is not the problem).

I've created a minimal example proposing better error messages and when to give them -- in the hope that table development gets much easier in the future.

Similar misleading error messages occur while using other environments like `align`, but let us begin with `tabular`.
## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}\begin{document}
The following is a correct example table:

\begin{tabular}{ l c r }
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9 \\
\end{tabular}

The following should give: column specifier number (3) and column number (= column number which occurs most often, here: 4) disagree:

\begin{tabular}{ l c r }
0 &  1 & 2 & 3 \\
 0 & 4 & 5 & 6 \\
 0 & 7 & 8 & 9 \\
\end{tabular}

The following should consider: 3 columns within the specification, at least half of the lines are 3 columns (and the critical line has 2n = 6 entries instead of n = 3)-> message: forgotten \verb|\\| in table line 2. Exemption: last line.

\begin{tabular}{ l c r }
  1 & 2 & 3 \\
  4 & 5 & 6
  7 & 8 & 9 \\
\end{tabular}

The following should consider: 3 columns within the specification, at least half of the lines have 3 columns -> message: forgotten \& in table line 2

\begin{tabular}{ l c r }
  1 & 2 & 3 \\
  4 & 5   \\
  7 & 8 & 9 \\
\end{tabular}

The following should see: No opening curly brace before first ampersand -> error message: Was {l c r} instead of [l c r] intended?

\begin{tabular}[ l c r ]
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9 \\
\end{tabular}

Entirely forgotten \verb|\\| should be recognized too and with higher priority, if the number of column entries does not agree with the number of column specifiers (here: 3). Proposed error messages: The tabular environment needs \verb|\\| to separate table rows.

\begin{tabular}[ l c r ]
  1 & 2 & 3
  4 & 5 & 6
  7 & 8 & 9
\end{tabular}

To be continued (... forgotten math delimiters ...)
\end{document}
```

## Log file (required) and possibly PDF file  

[20221118_eckige Klammern.log](https://github.com/latex3/latex2e/files/10045181/20221118_eckige.Klammern.log)
[20221118_eckige Klammern.pdf](https://github.com/latex3/latex2e/files/10045182/20221118_eckige.Klammern.pdf)

**Comment by davidcarlisle** [comment]
Sorry but your proposed errors assume latex has the information available which is not the case.

In your first example

```
\begin{tabular}{ l c r }
0 &  1 & 2 &
```

tex gives an error at the `&` the rest of the table has not been read at all. All it knows is an `&` appears where an end of row should be, hence

```
extra alignment tab has been changed to \cr
```
> , despite that the alignment tab is not the problem).

the extra `&` is _exactly_  the problem here.

This error comes from the TeX engine and the wording can not be changed from latex, but other than using the primitive `\cr` rather than latex name `\\ `,  it is quite accurate.

**Comment by FrankMittelbach** [comment]
In theory it is possible to  manually parse the whole table without involving the underlying TeX method of using `\halign`at all but that is quite different from "improving the error message given" and has enormous side effects and would require a totally different approach (and most likely quite different syntax to be effective); the same is true for all the `amsmath` environments. They work because they use the underlying internal `\halign` TeX mechanism and that can't be ripped out or replaced. And since that uses the engine error level you end up with the `\cr` in the message (which is what `\\`after some extra work actualy calls). This is similar to `\renewcommand` telling you about something never been `\def`ed, etc. It is not perfect but these low-level engine errors are hardwired without a possibility to adjust them.

**Comment by Friedrich2** [comment]
Thanks for your detailed explanations! Would it be acceptable, however, to post-process the complete table with non-TeX-tools after such an error, to yield additional, more informative error messages? Please observe that

- ... the proposed error messages would make sense even if they were presented in addition to the errors given by TeX internals. In this way, they enrich the log without hiding the internal errors.
- ... these errors are so serious that the code must be rewritten. Hence, the user is perhaps willing to appreciate time-consuming postprocessing / error generation, which will save him time in the long run due to a shorter error search.

**Comment by FrankMittelbach** [comment]
The user alternatively may have good documentation to look at, for example (obviously biased as I'm an author of it) _The LaTeX Companion_ has a whole section on all LaTeX core error messages and says about that one:

<img width="859" alt="Screenshot 2022-11-20 at 11 03 14" src="https://user-images.githubusercontent.com/1062981/202896112-df726f45-21c7-4a31-acb5-0d95a46eb1ec.png">

Would it be aceptable if somebody produces a post-processing program for the TeX .log file? Sure, but it is not going to happen at our end if that what you meant. But if somebody else want to do that ... it certainly wouldn't hurt. However, I personally don't believe that there is much gain compared with the effort; the low-level errors can have many causes often and only in a few cases you will be able to pinpoint the real cause in a single short error message, i.e., in most cases the user would need additional documentation even then.

**Comment by Friedrich2** [comment]
Thanks for your assessment! I am convinced.
