### ISSUE TITLE
\hspace may start a paragraph in a group. 

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/latex2e#967]
## Brief outline of the bug

Since 2020, to support `calc`, `\hspace` uses a local group.  This breaks `wrapfig` as reported at

https://tex.stackexchange.com/a/666731/1090

The issue though is unrelated to `wrapfig` as shown with the par hooks example below where cccc is not italic but dddd is.

Suggested fix would be to add `\leavevmode` before the group

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\AddToHook{para/before}{\itshape}
\AddToHook{para/end}{\upshape}

\begin{document}

aaaa

{b}bbbb

\hspace{5pt} cccc

\hspace*{5pt} dddd

\end{document}

```

![image](https://user-images.githubusercontent.com/1268738/204340518-a2569085-bbb3-45bc-8c30-70ed114aa3c0.png)

## Log file (required) and possibly PDF file  

[gr.log](https://github.com/latex3/latex2e/files/10106046/gr.log)

**Comment by car222222** [comment]
This is not exactly the actual reasoning: 
"to support calc, \hspace uses a local group"
since the group is there only to keep local the 
assignment to the skip register.
If an extra skip register were used here, with a 
name clearly indicating that it is to be used *only 
in this definition*, then the assignment need not be 
local, and thus it would not be necessary to use a local 
group here.

**Comment by FrankMittelbach** [comment]
true - streamlined

**Comment by FrankMittelbach** [comment]
fixed in patch-level 1
