### ISSUE TITLE
\do defined at \begin{document}

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#975]
```
\documentclass{article}
\newcommand{\do}{hello}
\begin{document}
\show\do
\end{document}
```
results in
```
> \do=\noexpand.
```

That is, LaTeX defines \do at \begin{document}, thus overwriting the previous definition. This was unexpected to me (though not exactly surprising, given history :).

I'm not sure if there are other (unprefixed/not-private) control sequences like this defined by the internals of LaTeX, especially at \begin{document}. And I'm also not sure if they are already documented -- I couldn't find any mention of \do being defined like this, but it's not an easy thing to search for.

So, perhaps something for the documentation? Or perhaps change the code so as not to overwrite \do? Or \do nothing, that's ok too ... --thanks, karl.

**Comment by davidcarlisle** [comment]
`\do` has always (even in 2.09 days) been used to maintain internal lists, eg list of special characters for `verbatim` is 

```
\def\dospecials{\do\ \do\\\do\{\do\}\do\$\do\&%
  \do\#\do\^\do\_\do\%\do\~}p
```
Which is also the form in plain tex so documented in the texbook.

Generally used with `\let\do\something\dospecials`  As this is usually in a group, an outer level custom definition doesn't always break things but is skating on thin ice...

> something for the documentation?

perhaps, not sure where...  Currently source2e (ltfiles.dtx) says

```
%    The next line is a pure safety measure in case a do list is ever
%    expanded at the wrong place. In addition it will save a few
%    tokens to get rid of the above definition.
%    \begin{macrocode}
  \global\let\do\noexpand
```

Happy Christmas for those an hour ahead of GMT :-)

**Comment by kberry** [comment]
I am well aware of the "standard" meaning of \do. My question/request was to document it. And other (non-private) control sequences. There has to be a place. To be honest, I find the collection of base documents such a grab-bag, I cannot guess where it might be. Sorry. In general, shouldn't all public control sequences defined by latex be listed/defined? And whether they are defined \atbegindocument is also crucial information, since such definitions overwrite anything done in the preamble.

**Comment by FrankMittelbach** [comment]
The underlying problem is that plain TeX has taken a lot of good names for internal stuff (\do is an example, but certainly not the only one) and that LaTeX way back decided to keep that layer). Not sure documenting would help (and there isn't really a good place for that either imho). Better would be  if LaTeX would not use them in the first place, but even that wouldn't help because they are also used in many packages modeling plain TeX or LaTeX or both.

Better than documenting it in an additional place other than source2e (which nobody reads) might be to set it to `\noexpand` in the kernel  (not sure why it happens only at `\begin{document}`), then your definition would fall over right at `\newcommand` telling you that it is not a command to define

**Comment by kberry** [comment]
might be to set it to `\noexpand` in the kernel then your definition
    would fall over right at `\newcommand` telling you that it is not a
    command to define

Yes, good idea, IMHO. That would be much better than silently throwing
away the definition I make in the preamble, which is what happens
now. --thanks, karl.

**Comment by FrankMittelbach** [comment]
yes, it needs some verification/thinking why it was thought to have the definition being done only at begin document but I can't really see a good reason for that.

**Comment by car222222** [comment]
Maybe look also at other such names still present in this layer and decide whether they need similar treatment?

"The underlying problem is that plain TeX has taken a lot of good names . . . LaTeX way back decided to keep that layer"

**Comment by car222222** [comment]
Some further analysis and suggestions following
 @FrankMittelbach 's  comment:
"it needs some verification/thinking why it was thought to 
have the definition being done only at begin document 
but I can't really see a good reason for that".

It is the way it is!  And this is the way simply because plain.tex never defines it (until needed) and this was not changed (why would it be?).  In plain it is never given any type of a harmless definition, but it is also only ever defined locally and 
so remains undefined at the global level.

It got a harmless definition in LaTeX just after it was used (not in a group, see below) to disable the “preamble only” commands.  

It probably should have been given a harmless definition when it was first introduced (rather than at its first usage) but no one thought to do this.  An even safer default definition would be to use \@gobble since this would magic away the whole list if it ever got accidentally expanded; maybe also add a warning/error to this global default definition?

Note: It is not clear why it got defined globally for this use in LaTeX (as part of \begin{document}): a group could have been used. 
This change dates from 1995 and no reason is documented.

Finally:
I think that there are no other such commands from plain (not defined until \begin{document}); this is simply because plain contains no other undefined commands: \do is singular in this, and many, ways!

**Comment by FrankMittelbach** [comment]
> Note: It is not clear why it got defined globally for this use in LaTeX (as part of \begin{document}): a group could have been used.
> This change dates from 1995 and no reason is documented.

other than a few more  settings that were made global by the change 1.0v as well. I looked a bit in my archive from 1995 but I couldn't find any anything related to that either.  But I don't think that it is helpful to change that just to eventually find out why it was done :-). Might have to do with those classes that support multiple documents loaded "locally".

So I'm going to leave it alone but only provide a global harmless definition for it on top-level already in the kernel as well. Doubt that it needs a warning or error given that it never showed up as an issue for more than 30 years.
