### ISSUE TITLE
Arguments read verbatim: necessary mandatory?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#997]
In the `usrguide` documentation, the only argument type read verbatim is `v` which is _mandatory_. Is there any reason for not providing an _optional_ argument type read verbatim?

**Comment by PhelypeOleinik** [comment]
I see one and a half reason not to.  The half reason is that after:
```latex
\NewDocumentCommand \foo { v } {#1}
```
you can use the command as `\foo|v&rb|` or `\foo*v&rb*` or `\foo{v&rb}` or... so you can't know, just by looking ahead of `\foo`, if it should grab an argument verbatim or not.  Of course it's possible to enforce a delimiter, like `\NewDocumentCommand \foo { v{|} } {#1}`, so that the verbatim argument _must_ be surrounded by `|...|`.  But then it defeats half the purpose of the verbatim, that now you cannot have a `|` char in the argument, which you could before by simply changing the delimiter.  (Add to this half reason, the technical difficulties of looking ahead for a verbatim char and finding out that it is not verbatim and then you have to put it back in the stream unchanged).

The one reason is that the whole point of commands that take verbatim arguments _is_ the verbatim part.  What would you do with a command, say, `\lstinline`, that may or may not take an argument?

**Comment by FrankMittelbach** [comment]
another half reason: there is not a real good use case (imho) why one would need that as an optional argument. But in any case Phelype's reasons are enough to state that we do not plan anything like that.

**Comment by dbitouze** [comment]
OK, thanks.

Here is a use case: suppose I want to create small Python exercises in a monthly Python journal (typeset thanks to LaTeX), with a command, say `\test`, which has two arguments for the question and the (possible) solution (depending on if I want to give immediately or not the answer). 

This could be used in one of the two following ways:

- `\test{Which character starts comments?}`
- `\test{Which character starts comments?}[#]`

Okay, quite a niche.

**Comment by PhelypeOleinik** [comment]
It's not too complicated to emulate that:
```latex
\documentclass{article}
\ExplSyntaxOn
\NewDocumentCommand \test { m t{|} }
  {
    \textbf {#1}
    \IfBooleanT {#2}
      {
        \exp_after:wN \exp_after:wN
        \exp_after:wN \testanswer
          \char_generate:nn { `| } { \char_value_catcode:n { `| } }
      }
  }
\NewDocumentCommand \testanswer { v }
  { \textit { ~ Answer: ~ } {#1} }
\ExplSyntaxOff
\begin{document}
\test{Which character starts comments?}

\test{Which character starts comments?}|#|
\end{document}
```

But you could also use two commands, `\question` and `\answer` (which is likely better if you want to make things modular).

**Comment by FrankMittelbach** [comment]
In that case a mandatory argument work (more or less) equally well. In your code you could test for it being empty or you could use 2 commands question and answer as suggestion by Phelype which I think is actually the better choice.

**Comment by muzimuzhi** [comment]
Drawback: the arg-spec `t{|}` restricts the choices of delimiters to be `|` only, and `t` can't emulate a verbatim arg enclosed between `{` and `}`.

**Comment by PhelypeOleinik** [comment]
@muzimuzhi Yes, but I don't see a way to have an optional verbatim argument with an arbitrary delimiter.  If you have optional verbatim with an arbitrary delimiter, you can't know if what follows is a delimiter or just any other token.  In other words, you can't differentiate these:
```
\foo=code=
\foo=math
```
unless you know what the delimiter is, or the argument is mandatory.
